### PR TITLE
fixes issue #1907

### PR DESCRIPTION
**Pull request by MichaelReichertOnGitHub**
modified:   src/languages/sql.js
	new file:   test/markup/sql/interval.expect.txt
	new file:   test/markup/sql/interval.txt
	new file:   test/markup/sql/join.expect.txt
	new file:   test/markup/sql/join.txt
	new file:   test/markup/sql/lateral-view.expect.txt
	new file:   test/markup/sql/lateral-view.txt
	new file:   test/markup/sql/numeric-types.expect.txt
	new file:   test/markup/sql/numeric-types.txt
	new file:   test/markup/sql/set-operator.expect.txt
	new file:   test/markup/sql/set-operator.txt
	new file:   test/markup/sql/tablesample.expect.txt
	new file:   test/markup/sql/tablesample.txt
	new file:   test/markup/sql/values-statement.expect.txt
	new file:   test/markup/sql/values-statement.txt
	new file:   test/markup/sql/window-function.expect.txt
	new file:   test/markup/sql/window-function.txt

### CODE REVIEW

**Comment by marcoscaceres** [comment]
I agree. We should probably split this up in the future.

**Comment by MichaelReichertOnGitHub** [comment]
@marcoscaceres @egor-rogov Thanks guys for reviewing my PR. Is there anything to do from my side to ensure that this PR is merged and included in the next release? Thanks.

**Comment by marcoscaceres** [comment]
Nope, you are all good. I’ll merge it tomorrow. Will try to do another release soon (we trying to do a release every 6 weeks).

**Comment by MichaelReichertOnGitHub** [comment]
Thanks for the heads up!

**Pull request merged**
