### PR TITLE
Add ShExC

### PR DESCRIPTION
**Pull request by ericprud**
This module was partially transliterated from the grammar for ShExC, ensuring completeness of the terminals and resulting in a validating highlight module.

### CODE REVIEW

**Comment by ericprud** [comment]
Something in the browser production chain is allergic to `const` and `let` so I [changed everything to `var`](https://github.com/highlightjs/highlight.js/compare/0518415ce9372b17d41024f1570b62fb063c024d..733ad7bfecf1216f6838e2e153ddeab9409a1ab8). I propose adding a line to that effect in [language-contribution](https://github.com/highlightjs/highlight.js/blob/master/docs/language-contribution.rst) §1 and add a §3½ with
```
node tools/build.js -t node && npx mocha --globals document test
node tools/build.js && npx mocha --globals document test/browser
```
so folks don't have to work it out from [`travis.yml`](https://github.com/highlightjs/highlight.js/blob/master/.travis.yml#L23).

While debugging the `const` and `let` issue, I created a tiny language to get module authors started:
```
	new file:   src/languages/_template.js
	new file:   test/detect/_template/default.txt
	new file:   test/markup/_template/_template-written.expect.txt
	new file:   test/markup/_template/_template-written.txt
	new file:   test/markup/_template/_template-read.expect.txt
	new file:   test/markup/_template/_template-read.txt
```
I made sure it wouldn't conflict with any other languages (relevance 0 except on a distinctive keyword) but maybe it would be better as a tarball under `/docs` than as a language choice the pops up in everyone's face? Anyways, yours if you think it will be useful.

**Comment by ericprud** [comment]
This has migrated to `https://github.com/highlightjs/highlightjs-shexc` but I'm not sure how to set up automagic build tests (i.e. produces expected markup, appropriate priorities). This was automatic on PRs in the monolithic highlightjs.

Also, where do additions to docs/css-classes-reference.rst go now? In particular, how to I add the suffixes `shex` and `shx`?

**Comment by marcoscaceres** [comment]
@ericprud true about the testing. We need to figure out a solution for that. I set up my own thing for a different project:

https://github.com/w3c/respec-hljs/blob/hljs/spec/highlight-spec.js

**Comment by ericprud** [comment]
It seems like the most important test is the [epic hljs.highlightAuto() test](https://travis-ci.org/highlightjs/highlight.js/jobs/502446997#L840-L841). If someone screws up their own module, so be it, but you don't want them to have inappropriate priorities which steal auto from others. I noticed that languages with URLs are prone to that (had to turn mine down to 0). Feel free to prototype some sort of prospective shared `.travis.yml` in `https://github.com/highlightjs/highlightjs-shexc`. I'm trying to make it a model highlight module and was planning on writing module authoring instructions for grammar geeks (i.e. using `contents` to create a sort of context-sensitive grammar, like a BNF but with no order on the components in the production).
 
So what's the next step now that I populated the shexc repo?

**Comment by yyyc514** [comment]
I’ve only just begin to look into this now that the new build system is coming along. Nothing to report yet though.

**Comment by yyyc514** [comment]
> Something in the browser production chain is allergic to const and let so I changed everything to var. 

@ericprud The new build process fixes this for good.

**Comment by yyyc514** [comment]
@ericprud Perhaps of interest: 

https://github.com/highlightjs/highlight.js/issues/2328

**Comment by yyyc514** [comment]
Since you're actively working on your grammar and you're already listed in the README I'm going to go ahead and close out this PR.

**Pull request closed without merging**
