### PR TITLE
Add Robot Framework

### PR DESCRIPTION
**Pull request by Harri**
This PR adds support for Robot Framework (http://robotframework.org/). While RF supports multiple different formats, this PR only handles white space separated format; http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#space-separated-format.

### CODE REVIEW

**Comment by gusbemacbe** [comment]
As I am not a collaborator yet, I will leave it to @marcoscaceres. 

@marcoscaceres, as I am graduated and done with the college, I will be ready to join the community and the team, but I can join only in January because I am solving to finish all my things I froze for 4 years.

**Comment by Harri** [comment]
Any chance to get this progressed? Happy to fix the conflict in the CHANGES.md if someone is willing to consider accepting this change. Thanks.

**Comment by marcoscaceres** [comment]
Hi @Harri - apologies for the radio silence. We are moving new languages into their own repositories under the hljs organization. If I spin you up a repo, would you be ok to maintain the language definition. You can see others here:

https://github.com/highlightjs/

**Comment by Harri** [comment]
Yes, I would be happy to maintain this under hljs organization. I'm traveling this week, so my Internet access is bit iffy until Monday.

**Comment by marcoscaceres** [comment]
Only just getting back to this now... created https://github.com/highlightjs/highlightjs-robot/ and sent you an invite @Harri.

**Comment by marcoscaceres** [comment]
@Harri, take a look at https://github.com/highlightjs/highlightjs-solidity or other languages at the org level. They all use basically the same structure.

**Comment by Harri** [comment]
Thanks. Just pushed the changes to https://github.com/highlightjs/highlightjs-robot I'll figure out the tests in place some other day. For now demo can be seen here https://spage.fi/highlight-robot

**Comment by yyyc514** [comment]
@Harri Thanks for the time and work on this!  Closing this PR since you seem to have things rolling with your new repository.

Regarding tests if all you need are detect/markup tests the new build system stuff I'm working on should really help. https://github.com/highlightjs/highlight.js/issues/2328

**Pull request closed without merging**
