### PR TITLE
3rd-party support for Oak

### PR DESCRIPTION
**Pull request by smithtim**
Oak is a proof checker focused on simplicity, readability, and ease of use: https://oakproof.org/

### Changes
Added Oak to supported languages (3rd party).

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
This looks good.  For your grammer I'd suggest:

- Use `scope`, not `className`
- Use `match` not begin
- Use our actual `keyword` support  for best forward compatibility without inventing your own custom modes

**Review by joshgoebel — APPROVED** [review]

**Comment by smithtim** [comment]
Thanks for the feedback.  I have made the first two changes.  For the third, my keywords use regular expressions rather than strings, and I don't know how to do that with `keywords`.

**Comment by joshgoebel** [comment]
A lot of your keyboards are simple and could use the regular engine, for the others you can use a mix, using the regex to find the combos but then still using the keyword engine to do the highlighting of each individual word.

```
      {
        match: regex.concat(/\b/, regex.either(...MULTI_WORDS), /\b/).
        keywords: { "built_in" : INDIVIDUAL_KEYWORD_ARRAY }
      },
```

**Comment by smithtim** [comment]
I see, thanks for looking into it.  I would prefer to keep it as is if that's okay — that will be easier for me.

**Pull request merged**
