### PR TITLE
enh(sql): added `ilike` keyword

### PR DESCRIPTION
**Pull request by 0xflotus**
### Changes

I added `ilike` to keyword list in sql

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please provide a list of which major databases suppose ILIKE and which do not.  We're quite selective about what we add to the main SQL grammar as there are individual grammars for the different DBs.

**Comment by 0xflotus** [comment]
> Please provide a list of which major databases support ILIKE (do they all?). We're quite selective about what we add to the main SQL grammar as there are individual grammars for the different DBs.

PostgreSQL supports it. That's the major DB I use.

**Comment by joshgoebel** [comment]
This appears to be a non-standard Postgres feature.  Please use the `pgsql` grammar instead.  We won't be adding this to `sql`.

**Comment by 0xflotus** [comment]
> Thanks for the PR, but this appears to be a non-standard Postgres feature. Please use the `pgsql` grammar instead. We won't be adding this to `sql`.

Thanks for the hint.

**Pull request closed without merging**
