### PR TITLE
(LSL) update to SL server v16.12.03.322072

### PR DESCRIPTION
**Pull request by buildersbrewery**
Compare <http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/16#16.12.03.322072>

---

/cc @codeviolet

### CODE REVIEW

**Comment by egor-rogov** [comment]
Merged, thanks.

**Comment by yyyc514** [comment]
Do you know why it was stuck?  It looks like it was waiting for something else to happen but it didn't show any hold ups int he UI?  Or else I would have merged it myself.

**Comment by egor-rogov** [comment]
I think it's because it was a very old PR. Something has changed in gitlab statuses since then.
I'd prefer to open a new PR for something more complex, but this one was straight and plain, so I just merged it.

**Comment by yyyc514** [comment]
Yeah, I've been trying to close out easy wins that are easily reviewed.  Get our PR queue down to noting but grammars and then figure out that problem. :-)

**Pull request merged**
