### PR TITLE
IRC logs,lang

### PR DESCRIPTION
**Pull request by svbeon**
So, I'm not expecting this to be merged - at least not in it's current state, because errors.
1. the nick groups `begin: ' <', end: '> '` and `begin: ' -', end: '- '` should of course preferrably be merged with those that have `begin: '^<'` and `begin: '^-'` the reason they are splitted is to have spaces in the first two examples so dates won't get caught with the `-nick-` ones (notices) 
2. in some way  `begin: ' <', end: '> '` and `begin: ' -', end: '- '` shouldn't be caught if they don't appear after a `\n` or `]\s` (note the whitespace)

so this PR is more a request for help with the above two things

### CODE REVIEW

**Comment by yyyc514** [comment]
IRC logs from what software?  Is there some sort of standard for these logs?

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
Possibly related to #1509

**Comment by svbeon** [comment]
Hey, sorry I started this and completely forgot about it... There isn't really a standard but most of them föllow a sort of convention. This was a while ago but I think it should be tailored to znc logs iirc. #1509 is probably a better point to work from

**Comment by yyyc514** [comment]
> This was a while ago but I think it should be tailored to znc logs iirc. #1509 is probably a better point to work from

I will close this PR then.  We're no longer accepting languages into the core repository (lack of time to maintain and support them) but if you wanted to press forward we'd be happy for you to write a 3rd party language module that users could add to Highlight.js on their own if you're still interested.  Let me know and I can tell ya more.

**Pull request closed without merging**
