### PR TITLE
Added mIRC Scripting Language

### PR DESCRIPTION
**Pull request by Kedyn**
Adds support for mIRC Scripting Language.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@Kedyn, we are currently in the process of moving languages to their own repositories. For example:

https://github.com/highlightjs/highlightjs-solidity

If I make a repository for you, could you maintain the language there?

**Comment by Kedyn** [comment]
Thank you for the information, sounds like a great plan.

Yes, I  would greatly appreciated if you could create the repository for me, so that I can maintain it from there.

**Comment by marcoscaceres** [comment]
@Kedyn, done: https://github.com/highlightjs/highlightjs-mirc

You should receive an invite.

**Comment by yyyc514** [comment]
@marcoscaceres Can you close issues?  I've seen you on so many. :)

**Comment by yyyc514** [comment]
Oh, I missed the "collaborator" vs "contributor" distinction. :-)  @marcoscaceres  Do you mind if I flag you on others that seem to be clearly closable?

**Comment by marcoscaceres** [comment]
Sure. Go for it. I might not get to them all today tho.

**Pull request closed without merging**
