### PR TITLE
Create language file for the Caboose language

### PR DESCRIPTION
**Pull request by RailRunner166**
The Caboose language is a functional language I made and is fully open-sourced at https://github.com/CabooseLang/

Please tell me if there is something I missed, since I am new to this :)

### CODE REVIEW

**Comment by RailRunner166** [comment]
I see that it failed, I wonder why that is...

**Comment by RailRunner166** [comment]
Oh, I see now, it mistook Kotlin for Caboose...

**Comment by RailRunner166** [comment]
If you want, rename my commit, I have a hard time naming things

**Comment by RailRunner166** [comment]
Is this something I should be worried about?
image

**Comment by RailRunner166** [comment]
OK I requested a review because from what I can tell that's not caused by me lol.

**Comment by yyyc514** [comment]
You can't run the browser tests unless you've build the browser version of the library.  `build -t browser`... otherwise you can only run the main test suite.

We are no longer accepting new languages into the core library but if you'd be willing to maintain a 3rd party language modules we'd love to have you.  We can even create a repository for you at the main "highlightjs" organization.

See:

https://github.com/highlightjs/highlight.js/blob/ddd34a43f96ee58b76d4338a5261527b85b09721/extra/3RD_PARTY_QUICK_START.md

**Comment by RailRunner166** [comment]
ah, thanks :) i will look into that and get back with you. Thanks for a quick response!

**Comment by RailRunner166** [comment]
OK I'm going to close this as I have decided to host it under Caboose's org, thanks again and I hope you have a great day :)

**Comment by yyyc514** [comment]
The repository can be wherever you want but you can still make it a 3rd party module (if you so desire).

**Pull request closed without merging**
