### PR TITLE
Lua Luup library grammar

### PR DESCRIPTION
**Pull request by mossarelli**
Here's a Lua language file that also includes all the Vera luup library methods and properties.
Luup is a library available for the Z-wave controller Vera that thousands of people use to automate their home using different devices.
The luup module is the controller unit's method of communicating with the Z-wave devices, making the names of methods and properties of this library essential for people that describe and work with Vera scripts.

You might want to change the name of the file and add a submenu for this under Lua.
I will make one for Home Center 2 as well, which is Fibaros unit.

image

### CODE REVIEW

**Comment by mossarelli** [comment]
The autodetect function can't parse two files with the same language. I don't know how to fix it and I don't have the time to dig through it.

It's hard to autodect luup because you can only detect it based on using the luup module and not on the filename.

**Comment by yyyc514** [comment]
**Sorry for the LONG delay.**  

>The autodetect function can't parse two files with the same language. I don't know how to fix it and I don't have the time to dig through it.

I'm not sure I understand what you mean here, can you clarify?

> It's hard to autodect luup because you can only detect it based on using the luup module and not on the filename.

Well, don't the keywords help?  If it's really impossible to autodetect you can always simply turn off autodetect with `disableAutodetect: true` in your grammar.

**Comment by yyyc514** [comment]
@mossarelli 

Currently we are no longer accepting new languages into the core repository.  The existing library maintainers don't simply have time to maintain any new languages (fixing bugs, dealing with issues, etc).  Luckily, it's pretty easy to turn your language into a 3rd party module that anyone who likes can easily integrate with Highlight.js with a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<script src="/path/to/highlightjs-lua-luup.js" /> <!-- they'd add this single line -->
<script>hljs.initHighlightingOnLoad();</script>
```

If you'd like to become the maintainer for this language then we're also happy to create a new repository in the `highlightjs` organization to host the repository.  That means you'd be open to reviewing issues and fixing bugs as they arise.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  

My own `robots.txt` repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Pull request closed without merging**
