### PR TITLE
New language: GraphQL

### LINKED ISSUE #1471: GraphQL (needs package & maintainer)
[GraphQL](http://graphql.org/) can describe both a type system and a query language, both in a consistent manner.

Example of a type (GitHub code blocks support GraphQL):

```graphql
type Project {
  name: String
  tagline: String
  contributors: [User]
}
```

Example of a query:

```graphql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {
      primaryFunction
    }
    ... on Human {
      height
    }
  }
}
```

### PR DESCRIPTION
**Pull request by dpeek**

### CODE REVIEW

**Comment by dpeek** [comment]
Not too sure about my workaround for awk detection, I guess I need more structure in my parsing so that enum (all caps identifier) named BEGIN doesn't fail detection?

**Comment by isagalaev** [comment]
I'll have a look at it all whenever I have time. Don't bother with cross-detection bugs just yet :-)

**Comment by schickling** [comment]
Any progress on merging this? Would love to use this in our Discourse forum that's using this package :)

**Comment by wyattjoh** [comment]
Also interested to get a progress update.

**Comment by schickling** [comment]
@isagalaev would be great if you could merge this!

**Comment by MoOx** [comment]
@isagalaev I am seeing a timeout that failed the entire suit https://travis-ci.org/isagalaev/highlight.js/jobs/242230250#L693

Do you we think you could try to rebuild the PR just to see if that's all green?
It would be nice to have this language in the core :)

**Comment by chollier** [comment]
that would be great

**Comment by morleym** [comment]
Did anyone ever revisit these failed checks? @dpeek

**Comment by FingerLiu** [comment]
any update?

**Comment by marcoscaceres** [comment]
Looking for someone to maintain this language (we are moving language requests outside the main repository so to avoid them getting stuck in a review queue a year 🥺). Example of an external repository:
https://github.com/highlightjs/highlightjs-solidity

**Comment by zeke** [comment]
Hey folks! We'd like to use this on a project at GitHub.

@dpeek would you be open to creating a new repo for this, per @marcoscaceres's suggestion above?

**Comment by dpeek** [comment]
Apologies for the delayed response. Have extracted into a repo based on the example and published v1 to NPM with no testing whatsoever. YOLO?

https://github.com/dpeek/highlightjs-graphql
https://www.npmjs.com/package/highlightjs-graphql

Will look into testing that it works this evening.

**Comment by marcoscaceres** [comment]
closing as done. thanks again @dpeek!

**Comment by yyyc514** [comment]
@dpeek You might want to follow along here.  Adding detects and markup tests should be trivial once this gets merged.

**Pull request closed without merging**
