### PR TITLE
Add SPARQL and Turtle languages

### PR DESCRIPTION
**Pull request by Comonut**
This pull request is a continuation of this pull request
https://github.com/highlightjs/highlight.js/pull/1746#issuecomment-408692676

### CODE REVIEW

**Comment by VladimirAlexiev** [comment]
hi @egor-rogov! the reason is some conflict in auto-recognition between `pie` and `arcade`, see https://travis-ci.org/highlightjs/highlight.js/jobs/432913230. 

I can't understand why the conflict happens, and don't know the `arcade` lang to be able to fix it :-(

**Comment by yyyc514** [comment]
@ellismarkf @VladimirAlexiev 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-turtle.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
> I can't understand why the conflict happens, and don't know the arcade lang to be able to fix it :-(

You don't necessarily have to know arcade.  The tests is failing because we have a file we KNOW is `arcade` code but your new `pie` grammar is trying to say it's pie code instead (because it scores higher when parsed as pie).

So you'd need to look at the arcade file: `/test/detect/arcade/default.txt` and see WHY your `pie` grammar is producing a false positive.  Usually it's because you're matching duplicate keywords or your relevance scores are tuned too high.

**Comment by yyyc514** [comment]
See #1553 .

Closing as dup and since we already have: https://github.com/highlightjs/highlightjs-turtle and https://github.com/highlightjs/highlightjs-pie

**Comment by IS4Code** [comment]
I wish this was merged into the core repository; it is so annoying having no support for this in Discord ‒ web standards should be in core!

**Comment by joshgoebel** [comment]
ChatGPT:

> SPARQL (SPARQL Protocol and RDF Query Language) is not a web standard in the sense of being a formal standard developed and maintained by a web standards organization like the World Wide Web Consortium (W3C) or the Internet Engineering Task Force (IETF). Instead, SPARQL is a query language and protocol specifically designed for...

---

Also: adding a language to core does not guarantee that Discord supports it.

**Comment by IS4Code** [comment]
@joshgoebel 
> ChatGPT:
> 
> > SPARQL (SPARQL Protocol and RDF Query Language) is not a web standard in the sense of being a formal standard developed and maintained by a web standards organization like the World Wide Web Consortium (W3C) or the Internet Engineering Task Force (IETF). Instead, SPARQL is a query language and protocol specifically designed for...
> 
> Also: adding a language to core does not guarantee that Discord supports it.

W3C:
> A W3C Recommendation is a specification or set of guidelines that, after extensive consensus-building, has received the endorsement of W3C Members and the Director. W3C recommends the wide deployment of its Recommendations. Note: W3C Recommendations are similar to the standards published by other organizations.

A W3C Recommendation, which both [Turtle](https://www.w3.org/TR/turtle/) and [SPARQL](https://www.w3.org/TR/sparql11-query/) as languages are, *is* the closest to a web standard as far as W3C is considered. It's not some proprietary language someone created and got traction, it is a standard and the primary language for encoding and querying RDF.

**Comment by VladimirAlexiev** [comment]
@joshgoebel Don't cite GPT as an authority, lest you fall into the trap of the lawyer who had to explain in shame to the judge how come the case law he cited, did not exist.

**Comment by vemonet** [comment]
@joshgoebel it would be really nice to add SPARQL and Turtle in the core languages. We understand more languages makes maintenance harder, but as other participants of the thread mentioned: they are web standards that are more than 20 years old and here to stay. They are particularly used for public data sharing (Wikidata, European Commission) and scientific research data (UniProt, PubChem, PathwayCommons...).

And they don't require a lot of maintenance per say, as the standards evolves relatively slowly, note that other popular highlighting libraries like prismJS have them integrated in the core

I actually just asked the question myself to chatGPT in a new chat: "Are SPARQL and turtle web standards?"

And got a completely different answer than you (wow could it be that LLMs are not deterministics truth machines? :D)

> Yes, both SPARQL and Turtle are web standards maintained by the **World Wide Web Consortium (W3C)**. Here's a bit more detail:
>
> 1. **SPARQL**:
>    - SPARQL is the **SPARQL Protocol and RDF Query Language**, used to query and manipulate data stored in RDF (Resource Description Framework) format.
>    - It is a **W3C Recommendation**, meaning it is an official standard designed for interoperability on the web.
>    - The most recent version is **SPARQL 1.1**, which includes advanced features like property paths, federated queries, and update operations.
> 2. **Turtle**:
>    - Turtle (Terse RDF Triple Language) is a compact and human-readable syntax for expressing RDF data.
>    - It is also a **W3C Recommendation**, providing a simplified and more readable alternative to RDF/XML for serializing RDF graphs.
>    - Turtle is widely used in Linked Data and Semantic Web projects due to its simplicity.
>
> Both standards are part of the W3C's efforts to advance the **Semantic Web** by enabling the sharing and querying of structured data across the web.

Let us know if you want to help to refresh the PR

**Comment by brettz9** [comment]
What may be required now to get SPARQL added?

**Pull request closed without merging**
