### PR TITLE
Added support for SAS language

### PR DESCRIPTION
**Pull request by mcaceresb**

### CODE REVIEW

**Comment by tglines** [comment]
@isagalaev can we consider adding SAS to hljs?  Currently pulling in his work here from https://github.com/mcaceresb/highlight-sas-stata in order to achieve this.

**Comment by 77QingLiu** [comment]
@isagalaev please add SAS Language to highlight.js

**Comment by antonsarov** [comment]
The PR seems to be fine, is there any reason why it has not been accepted?

**Comment by gusbemacbe** [comment]
See if the new SAS language file follows new policy and new rules released in the updated documentation.

**Comment by mcaceresb** [comment]
@gusbemacbe I'm not entirely sure what you mean? I followed [the language contribution guide](http://highlightjs.readthedocs.io/en/latest/language-contribution.html) which does not seem to have changed.

**Comment by gusbemacbe** [comment]
Then, Maurice, let me call @ldct and @SirCmpwn to review and approve. 

Please wait for the approval.

**Comment by gusbemacbe** [comment]
Ah, Maurice, I saw you sent the external  documentation. Maybe in the next release the external documentation must be changed.

**Comment by mcaceresb** [comment]
@gusbemacbe Do you mean that the docs are not updated? I diffed that I had locally 2 years ago with the master branch. The changes seemed like minor clarifications and I did not see anything I missed in my original submission.

**Comment by gusbemacbe** [comment]
See: https://github.com/highlightjs/highlight.js/issues/1759

**Comment by antonsarov** [comment]
@gusbemacbe would you be able to give some directions on what is left open. We are relying on this feature and currently as @mcaceresb I don't see what is to be done. Do we have to wait for #1759 ?

**Comment by marcoscaceres** [comment]
This looks good. I'm not seeing any blockers @gusbemacbe?

**Comment by marcoscaceres** [comment]
No. Not for at least 1 year until as a community we figure out how to do it.

**Comment by marcoscaceres** [comment]
Could someone please send a PR for updating the CHANGES.md file?

**Comment by antonsarov** [comment]
@marcoscaceres Please see #1841

**Pull request merged**
