### PR TITLE
[PHP] PHP 8 updates

### PR DESCRIPTION
**Pull request by Ayesh**
- PHP introduces a new [`match` keyword in PHP 8.0](https://php.watch/versions/8.0/match-expression). This PR adds the `match` keyword to the list of keywords for PHP.
 -  Add 'php8' as an alias for PHP

Thank you.

### CODE REVIEW

**Comment by joshgoebel** [comment]
Looks good.  Please add entry to CHANGES.md.

**Review by joshgoebel — APPROVED** [review]

**Comment by Ayesh** [comment]
Thank you - I just pushed a commit with a new CHANGES.md entry 🙏🏼.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
@Ayesh Thanks so much!

**Comment by Ayesh** [comment]
Thanks a lot for the merge, quick responses and reviews too :)

**Comment by joshgoebel** [comment]
Easy PR == fast response.

**Pull request merged**
