### PR TITLE
Add grep to bash keywords

### PR DESCRIPTION
**Pull request by splch**
### Changes

grep is a very common bash command, so I'm adding to the list.

### Checklist
- [ ] Markup tests don't apply since it's a single word being added
- [x ] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Is it a GNU core utility though? If not we need a new list...

**Comment by splch** [comment]
> Is it a GNU core utility though? If not we need a new list...

It's referenced in the [coreutils](https://www.gnu.org/software/coreutils/manual/coreutils.html) but I don't know if it's included. In any case grep is part of [every *nix OS](https://wikipedia.org/wiki/Grep) so it's either included there or in the kernel.

**Comment by joshgoebel** [comment]
Doesn't seem to be.

https://github.com/coreutils/coreutils

So lets create a new `POPULAR_UTILS` collection to hold such things...

**Comment by splch** [comment]
> Doesn't seem to be.
> 
> https://github.com/coreutils/coreutils
> 
> So lets create a new `POPULAR_UTILS` collection to hold such things...

Oh thanks for checking, I wasn't sure where to look 😅

That sounds like a great idea! I'll look into it in a little.

**Comment by joshgoebel** [comment]
Ping?

**Comment by joshgoebel** [comment]
Closing for inactivity.  Whenever you have time to work on this again it can be reopened.  Thanks.

**Pull request closed without merging**
