### PR TITLE
(swift) improvements: support `some`, `@main`; Fix `#` keywords .

### PR DESCRIPTION
**Pull request by mportiz08**
General enhancements and a bug fix for highlighting Swift code.

### Changes
Adds highlighting support for new Swift 5.1 and 5.3 features that are heavily utilized in SwiftUI code:

1. [`some` keyword][1] (Introduced in Swift 5.1)
2. [`@main` attribute][2] (Introduced in Swift 5.3)

Fixes a bug where keywords that start with the `#` character (like `#endif` as an example) are not matched.

[1]: https://github.com/apple/swift-evolution/blob/main/proposals/0244-opaque-result-types.md
[2]: https://github.com/apple/swift-evolution/blob/main/proposals/0281-main-attribute.md

### Checklist
- [X] Added markup tests
- [X] Updated the changelog at `CHANGES.md`
- [X] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

**Comment by joshgoebel** [comment]
@svanimpe Could you take a quick look here.  Does this look good to you?  I think the changes look good, I just don't know the language itself.

@mportiz08  https://github.com/highlightjs/highlight.js/issues/2847

Do you know anything about `c`?   If not and you agree would you mind yanking that out as part of this PR also?

**Comment by svanimpe** [comment]
I wonder if @mattt would be willing to help out here. Perhaps https://github.com/SwiftDocOrg/swift-doc can be used to generate a list of global functions in the Standard Library?

**Comment by joshgoebel** [comment]
There are a number of Swift issues open right now (many of them of the more trivial variety) if a Swift champion were to show up on the scene. :)  https://github.com/highlightjs/highlight.js/issues/2825

**Comment by joshgoebel** [comment]
> Perhaps https://github.com/SwiftDocOrg/swift-doc can be used to generate a list of global functions in the Standard Library?

I do worry that what we have now is perhaps someones list of "frequently used" rather than ever having been "all globals" (I really have no idea though), but now I'm curious.  Swift is shipped as part of the `common` group so that makes me think about it's ultimate size perhaps a bit more than other grammars...  like if we were suddenly going to add 1000 keywords that might be something we need to look at.  Right now though Swift is a pretty small grammar, so we certainly have room to grow.

**Comment by joshgoebel** [comment]
If we're going to totally rewrite the keywords section overall I'd save that for another PR though and also switch to the new one keyword per line array style to make future maintenance easier.

**Comment by mportiz08** [comment]
> Do you know anything about `c`? If not and you agree would you mind yanking that out as part of this PR also?

I don't, but that is really interesting/surprising—I'm honestly not aware of `c` being a keyword on its own. It looks like it was introduced with e5c1b0c59014a9f35c55fb7de0bcc29ab4b752a6.

**Comment by joshgoebel** [comment]
@natecook1000  You added `c` to the list of Swift keywords in e5c1b0c.  Can you shed any light? :)

**Comment by joshgoebel** [comment]
Since we don't have any immediate answer on `c` I don't see a need for that issue to hold up this work.  I glanced at the links provided and this looks entirely reasonable. 

Thanks for the contribution!

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
If you'd perhaps like to continue helping out with Swift: #2578 #2819

Now quite as low-hanging fruit, but close.

**Comment by svanimpe** [comment]
W.r.t. the built-ins: I've noticed that methods like `Array.count` also highlight because `count` is listed as a built-in, even though it's not a global function anymore.

**Comment by joshgoebel** [comment]
Well if the language has changed then count be perhaps removed but ultimately this will be solved when the Swift grammar adds property access and method dispatch since that rule matching would win prevent the keyword from matching, etc.

**Pull request merged**
