### PR TITLE
Add ABAP language

### PR DESCRIPTION
**Pull request by cassioiks**
Adding initial language definition for **SAP ABAP**.
Markup test not supplied.

### CODE REVIEW

**Comment by Psidium** [comment]
Any updates on this pull request?

**Comment by isagalaev** [comment]
It's waiting its turn. There's only so much we can do with whatever time available :-)

**Comment by cassioiks** [comment]
Hi @isagalaev,

Is there something we can do to speed up the merge of this PR?

Thank you

**Comment by larshp** [comment]
@cassioiks I have updated your code, see https://github.com/larshp/highlight.js/commit/e1b8756c8a70b38b98af1e8609f52b16d86f4647 so the unit test does not fail, can you update your branch with the code?

**Comment by cassioiks** [comment]
@larshp Thanks, I just updated the code.

**Comment by jaulz** [comment]
Any idea if this will be merged at some point? Would be great 👍

**Comment by cassioiks** [comment]
@jaulz I agree... it's almost 1 year and still nothing. @isagalaev Is there anything we can do?

**Comment by hismayilov** [comment]
any update?

**Comment by neooblaster** [comment]
Hi all.

I'm also interessed for ABAP highlight

Is the request approved ?

Thanks,
Best Regards
Nicolas DUPRE

**Comment by cassioiks** [comment]
@isagalaev any news? anything we can do?

**Comment by marcoscaceres** [comment]
We are starting to move languages outside the main repository into their own repository (but still part of the hljs org). That will avoid problems of things not getting merged in a timely manner- but it means authors will be responsible for publishing and maintaining their own languages. Would folks here be interested in taking part in that?

**Comment by larshp** [comment]
yes 🙋‍♂️ 

if you create the highlightjs-abap repo, then I'm sure someone(perhaps @cassioiks) will open the PR for it 😄 

guess https://github.com/highlightjs/highlightjs-cshtml-razor can be used as reference?

**Comment by neooblaster** [comment]
I think it's a good idea. It should be more easier to maintain and contribute for people like me.
This PR is not critical for me because I directly altered the highligh lib in my node_module dependencies folder to include ABAP files (which work perfectly).

How must we do to request a new repository conventionnaly named "highlightjs-abap" to work on it ?

The documentation will be update in that way I suppose ?

Thank for your replies and availability.

Nicolas DUPRE

**Comment by yyyc514** [comment]
**First of all, truly sorry for the long delay in response.**

> As long as it means we can finally get ABAP language in highlight.js, I'm in.
Can you give some instructions how/where to create this separate repository and how to finally merge into hljs?

@cassioiks I'd be happy to create a repository for you in the `highlightjs` organization (or you can create one where-ever you want - and we can link to it from our README.  Unfortunately, we currently are no longer merging new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc). **Having a separate repository is an alternative to merging, not in addition to.**

But you can still make it easy for users of highlight.js to use your language as a 3rd party module (or CDN package). It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-abap.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by larshp** [comment]
✋ I'd like to help maintaining the ABAP highlighting for highlight.js

Its easiest to find if its a repo in the highlightjs organization. Any thoughts on publishing to npm, do you also have an organization there?

**Comment by yyyc514** [comment]
> Its easiest to find if its a repo in the highlightjs organization. Any thoughts on publishing to npm, do you also have an organization there?

No. Or, actually I'm not sure.  I just published robots-txt under my own account.  I'm not sure what the permissions are like for organizations on npm, do you know?  Is it easy to have a bunch of different siloed permissions for people within an organization (like it is here on GitHub)?  Perhaps it's finally time we took a look at GitHub packages?  I wonder if they would "just work" since we already have the repository permissions and stuff setup.

But I have no idea how easy it is to use npm with git package or if they are mutually exclusive things.

@marcoscaceres Any thoughts on this?

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlightjs-sap-abap

Sent you both invites.  I think it's ok if we name the grammar 'abap` but I went with the clearer more context filled name for the repo itself.

Or perhaps we should start using longer names and use aliases better?

So `sap-abap` is the grammar with `abap` as an alias?

**Comment by yyyc514** [comment]
@larshp I almost just forked it from robots-txt but I didn't know if that would be useful or a detriment.

**Comment by yyyc514** [comment]
@larshp I just realized we also have #1996.  :-|

**Comment by larshp** [comment]
thanks, I'm on it, suggest closing both pull requests in favor of https://github.com/highlightjs/highlightjs-sap-abap/issues/1

npm: I'm not sure, but personally I'd prefer everything on npm instead of on npm and GitHub package repos

**Comment by yyyc514** [comment]
After we have some code in the new repo I will close.

**Comment by cassioiks** [comment]
Thanks for the info @yyyc514. I was beginning to lose hope after 3 years, but I guess it's a Christmas miracle :)

I'll happily maintain the repo with you, @larshp 

Merry Christmas to all

**Comment by larshp** [comment]
@cassioiks I already added some code in https://github.com/highlightjs/highlightjs-sap-abap, and published to https://www.npmjs.com/package/highlightjs-sap-abap

do you have a user on npm? then I'll add you so you can also publish

**Comment by boghyon** [comment]
If anyone is interested in the highlight support for ABAP on Stack Exchange sites, please vote also for https://meta.stackoverflow.com/q/402607/5846045.

**Pull request closed without merging**
