### PR TITLE
Added fresh instance generation function

### PR DESCRIPTION
**Pull request by wisammechano**
### Changes
Moved the instance generation to a variable and attached a method `newInstance` to generate a fresh highlighter.

### Checklist
- [ ] No new markup
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please also add some minimal docs to `docs/api`.

**Comment by joshgoebel** [comment]
Ping.

**Comment by wisammechano** [comment]
Done

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
@wisammechano Thanks!

**Pull request merged**
