### PR TITLE
hljs playground

### PR DESCRIPTION
**Pull request by Hirse**
Adding a playground as a public version of `tools/developer.html` to be added to the website.
Currently does not include the localstorage, so not a complete replacement.
Generated using the same process as the demo page.
Working version (using CDN sources): https://codesandbox.io/s/hljs-playground-jomgi

playground

### CODE REVIEW

**Comment by joshgoebel** [comment]
This type of idea has come up in the past - I also think we already have our own (much simpler) take on this for the new website (that's not yet published).  I also have concerns whether we want this [the FULL utility] to be user facing for ALL users of the library - whether that's it's own support burden or not.  I feel like at the very least if we went this direction (fully public tool) it would need it's own small dedicated page of docs, etc.

I'll discuss with @highlightjs/core.

**Comment by joshgoebel** [comment]
Another idea (if we go this more ambitious route) is constantly saving the code into the URL (vs local storage) as a `#hashtag` so that problematic code can be tested, then the URL copied right into a GitHub issue, etc... which would link to the developer tool with that snippet already loaded (and the correct language, theme, etc)... might reduce the need for the JSFiddle we currently use for such things.

**Comment by Hirse** [comment]
> Another idea (if we go this more ambitious route) is constantly saving the code into the URL (vs local storage) as a `#hashtag` so that problematic code can be tested, then the URL copied right into a GitHub issue, etc... which would link to the developer tool with that snippet already loaded (and the correct language, theme, etc)... might reduce the need for the JSFiddle we currently use for such things.

Yes, I had that idea too, but wanted to showcase my current version before spending more time on it.

I'd be happy to work more on it if you decide to go this direction.

**Comment by joshgoebel** [comment]
I think the new website makes this redundant, yes?

https://highlightjs-web.herokuapp.com/demo

**Comment by Hirse** [comment]
> I think the new website makes this redundant, yes?
> 
> https://highlightjs-web.herokuapp.com/demo

Yeah, looks like it. :)

**Comment by joshgoebel** [comment]
Sorry this took so long to resolve - please don't feel bad. (I'm glad you're smiling)  If you see room for improvement on the new site's similar feature I'm sure we'd be open to ideas/PRs.

**Pull request closed without merging**
