### PR TITLE
fix(csharp) Fix assignments flagging as functions

### PR DESCRIPTION
**Pull request by joshgoebel**
Attemps to resolve https://github.com/exercism/v3-beta/issues/127#issuecomment-885352710

### Changes

- Disallowed `=` inside type expressions`<...>` to prevent them from being too greedy

If this isn't sufficient then we'll need a complex recursive regex like Java I think?

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Also requested review from Exercism team.

**Review by ErikSchierboom — APPROVED** [review]
It appears to be working! It's somewhat hard to see, but I think it's good!

**Review by allejo — APPROVED** [review]
LGTM :+1:

image

image

**Comment by ErikSchierboom** [comment]
Thanks @joshgoebel!

**Pull request merged**
