### PR TITLE
(chore) Fix typescript type exports

### LINKED ISSUE #2945: [Request] Expose TypeScript types.
**Is your request related to a specific problem you're having?**
Sometime I want to use some type from Highlight.js internal types. e.g. `Language`, `LanguageFn`.  
But I can't use it now.

**The solution you'd prefer / feature you'd like to see added...**
Expose all internal TypeScript types from `highlight.js`.  
So I can use it for more typing.

**Any alternative solutions you considered...**
No.

**Additional context...**
Types should be able to import like this.

```ts
import { LanguageFn, Language } from 'highlight.js';
```

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolved #2945.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@joshgoebel can you please backport this into v10? I'd be happy to migrate to v11, but unfortunately I can't, because I use dynamic imports, see https://github.com/webpack/webpack/issues/13865

**Comment by joshgoebel** [comment]
_V10.0 is about to drop off the supported list entirely._   The core team really does not have time to support multiple versions.  Even a PR here isn't super trivial as it would have to pull over the new changes but then also back out the changes to types that occurred between 10 -> 11.

> but unfortunately I can't, because I use dynamic imports, see webpack/webpack#13865

`import` isn't the only way to use the library.  You could use the stand-alone JS builds (as a separate file even) or even append our web build at the very end of your build process (I'm sure Webpack has a way of doing this).  So there are ways to use v11 with Webpack despite the bug.

**Comment by joshgoebel** [comment]
If the exports was a _huge_ issue we might perhaps drop them entirely, but it seems only a few broken tools are having issues and that mostly everything else works - unless others would like to chime in here.

**Comment by Hypnosphi** [comment]
More context: we're developing a component library, and our `Code` component loads languages on demand in runtime depending on the passed `language` prop value. How would I do that without using dynamic imports or migrating away from webpack?

Source: https://github.com/JetBrains/ring-ui/blob/typescript/components/code/code.tsx#L15-L21

**Comment by joshgoebel** [comment]
Well, I'm not a webpack person I have no idea what the magic comment is trying to do but I'd imagine for dynamic run-time dependencies (via import) you would just use the new ESM CDN builds that we publish (as of 11.2) unmodified... the grammars are all package up in individual files for dynamic usage... and the "main" Highlight.js bundle could be:

- loaded separately 
- concated to the end of your web pack build
- imported dynamically as well (via ESM CDN build)

**Pull request merged**
