### PR TITLE
WIP: Add Logtalk language

### PR DESCRIPTION
**Pull request by pmoura**

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Hi Paulo, please, if the error insists, try to copy the file cpp.js for your new language syntax to fix the errors.

Olá Paulo, por favor, se a falga insistir, tenta copiar o ficheiro cpp.js para o teu sintaxe de nova linguagem com a finalidade de corrigir as falhas

**Comment by pmoura** [comment]
The current problem is how to correctly distinguish between Logtalk, Prolog, and Mercury. Logtalk extends and thus subsumes Prolog. Mercury shares syntax constructs with Prolog and Logtalk. In 01b76f0, the Mercury sample is being misclassified as Logtalk. I will continue to look for a solution. Meanwhile, I have prefixed the pull request with a WIP tag.

**Comment by gusbemacbe** [comment]
@ldct, can you review the errors? I couldn't not find.

**Comment by gusbemacbe** [comment]
There is an error: 

```
232 passing (4s)
  1 failing
  1) hljs.highlightAuto() should be detected as mercury:
      AssertionError: expected 'logtalk' to be 'mercury'      
      actual expected
      
      logtalkmercury
      
      at Assertion.fail (node_modules/should/cjs/should.js:326:17)
      at Assertion.value (node_modules/should/cjs/should.js:398:19)
      at test/detect/index.js:28:23
      at tryCatcher 
```

**Comment by pmoura** [comment]
Yes, that's the error that I'm currently trying to fix. My current approach is to define the `illegal` tag (in the `logtalk.js` file) listing some directives that are only valid in Mercury. But so far I have not been able to make it work. The main difficulty is that the traditional definition of keywords don't work for Prolog/Logtalk/Mercury. I need to list e.g. the Mercury directives `:- implementation.` and `:- interface.` in the illegal tag **as-is**. Tried to define `lexemes` using the `^\s*:-\s+[a-z][a-z_]+` regular expression but it's not working.

**Comment by gusbemacbe** [comment]
I got it. You need to separate the `:-` from this regular expression. Derived from the [prolog.js](https://github.com/highlightjs/highlight.js/blob/master/src/languages/prolog.js), add a new function for `:-`:

```
var PRED_OP = { // relevance booster
    begin: /:-/
  };
```

**Comment by pmoura** [comment]
In what way that would help? Logtalk/Prolog/Mercury directives all start with `:-`. How to exclude just the directives that are Mercury-only without breaking the recognition of valid directives? I'm currently using:

```javascript
  var DIRECTIVES = {
    className: 'keyword',
    begin: /^\s*:-\s+[a-z][a-z_]+\b/, end: '\\.',
    relevance: 5,
    excludeBegin: false,
    excludeEnd: false,
    returnBegin: false,
    contains: [PARAMETERS]
  };
```
This allows recognizing all directives without being forced to list them all individually. Is there a way to list exceptions?

**Comment by gusbemacbe** [comment]
I have never learned your programming language. Please, send me the example file of codes in Logtalk, containing `:-`. I learned only Prolog, which was one of my semester disciplines of my computer science course.

The three files should be separated and can not be unified. The files mercury.js and prolog.js separate this `:-`. Since you use `^\s*` and `\s+`, these files do not use it. Derived from the file [mercurj.js](https://github.com/highlightjs/highlight.js/blob/master/src/languages/mercury.js), compare;

You can observe they do not use `\s` and `\s+`:

```javascript
var NUMCODE = {
    className: 'number',
    begin: "0'.\\|0[box][0-9a-fA-F]*"
  };

  var ATOM = hljs.inherit(hljs.APOS_STRING_MODE, {relevance: 0});
  var STRING = hljs.inherit(hljs.QUOTE_STRING_MODE, {relevance: 0});
  var STRING_FMT = {
    className: 'subst',
    begin: '\\\\[abfnrtv]\\|\\\\x[0-9a-fA-F]*\\\\\\|%[-+# *.0-9]*[dioxXucsfeEgGp]',
    relevance: 0
  };
```

In the file mercury.js, you can see how they added `\\`, but it depends on the formatting, indentation and space style the programmer prefers:

```javascript
var HEAD_BODY_CONJUNCTION = {
    className: 'built_in',
    variants: [
      {begin: ':-\\|-->'},
      {begin: '=', relevance: 0}
    ]
  };

  return {
    aliases: ['m', 'moo'],
    keywords: KEYWORDS,
    contains: [
      IMPLICATION,
      HEAD_BODY_CONJUNCTION,
      COMMENT,
      hljs.C_BLOCK_COMMENT_MODE,
      NUMCODE,
      hljs.NUMBER_MODE,
      ATOM,
      STRING,
      {begin: /:-/} // relevance booster
    ]
  };
```

What if the programmer prefers joining the `:-` and one word in Logtalk?

**Comment by pmoura** [comment]
Thanks for helping. A sample of Logtalk code is part of the pull request. A comprehensive sample is also available at:

https://github.com/LogtalkDotOrg/logtalk3/blob/master/coding/tests/source.lgt

In Prolog/Logtalk/Mercury, writing a single space between the `:-` operator and the operand is a pervasive code style.

Given the proximity of these languages, the only reliable way of detecting them is to look for the Logtalk specific directives and for the Mercury specific directives. The current `mercury.js` file uses a keyword solution that is fragile. Any atom used in a built-in directive can also be used as a predicate name.

**Comment by gusbemacbe** [comment]
Sorry, Paulo, for my absence, I was working a lot and went to bed. I reviewed again your codes and there was no error. Strange, maybe because of the alias as @ldct reported at his #1779.

**Comment by gusbemacbe** [comment]
I suspect it be a Mocha bug. It was not your fault, so in your source code there was no error. See https://github.com/highlightjs/highlight.js/pull/1781#issuecomment-408742991.

**Comment by pmoura** [comment]
Still getting a conflict with Mercury.  bd69bd9 defines:

```javascript
  return {
    aliases: ['lgt'],
    case_insensitive: false,
    contains: inner.concat([
      {begin: /:-$|\.$/} // relevance booster
    ]),
    illegal: /^:-\s(interface|implementation)\.$/
  };

```

as the `:- interface.` and `:- implementation.` are only valid in Mercury. These two directives are found in the Mercury sample file. Yet, that sample file is still misidentified. Any hints on what's wrong with the definition of the illegal regular expression above?

**Comment by gusbemacbe** [comment]
@pmoura 

Does the Highlightjs guide allow to use `/^` in the code `illegal: /^:-\s(interface|implementation)\.$/`? So see: https://highlightjs.readthedocs.io/en/latest/language-guide.html?highlight=illegal#illegal-symbols

Check the regex reference: https://highlightjs.readthedocs.io/en/latest/reference.html?highlight=regular

**Comment by pmoura** [comment]
No helpful information in the docs. Nothing there other than that the `illegal` value is specified to be a regular expression.

**Comment by yyyc514** [comment]
@pmoura 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-logtalk.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
> The current problem is how to correctly distinguish between Logtalk, Prolog, and Mercury. Logtalk extends and thus subsumes Prolog. Mercury shares syntax constructs with Prolog and Logtalk. In 01b76f0, the Mercury sample is being misclassified as Logtalk.

Sometimes these problems can be almost impossible to fix. (for languages that share a lot in common)

> These two directives are found in the Mercury sample file. Yet, that sample file is still misidentified. Any hints on what's wrong with the definition of the regular expression above for the illegal tag?

Matches and illegal are entirely separate things.  Your illegal will never be triggered because your match is matching the beginning of the string.

**Comment by yyyc514** [comment]
If you want to see a lot of thoughts on auto-detect:

https://github.com/highlightjs/highlight.js/issues/1213

I'm not even sure using illegal like that is the right long-term approach.  Languages should (mostly) focus on identifying themselves very well, not on NOT identifying other languages.  Our existing test suite has encouraged that behavior, but it's often not the correct behavior.

There is still a lot I'd like to get to with regard to auto-detection but I've been working on other things.

The good news is you can have a 3rd party module and publish it (and people can use it) even if some of the detect tests are still failing.

**Comment by pmoura** [comment]
@yyyc514 Thanks for the feedback. I'm happy with supporting Logtalk highlighting as a 3rd party module. I will look into the documentation and examples.

**Comment by yyyc514** [comment]
@pmoura Would you like us to setup a repository for you in the `highlightjs` organization?

**Comment by pmoura** [comment]
@yyyc514 Please do setup the repo. Thanks.

**Comment by yyyc514** [comment]
Done. https://github.com/highlightjs/highlightjs-logtalk

Closing this PR.

**Pull request closed without merging**
