### PR TITLE
(chore) fix CSS in the dev tool to be cross-browser once again

### LINKED ISSUE #3290: Dev Tools broken has CSS for structure
After #3133, the CSS has been broken for our dev tools on non-Gecko (i.e. Firefox) browsers.

**Gecko**

image

**WebKit/Blink**

image

### PR DESCRIPTION
**Pull request by allejo**
Related to #3133
Fixes #3290

Screen Shot 2021-08-01 at 1 36 21 PM

image

### Changes

Replace CSS that only worked on Gecko browsers with more generic CSS

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Snap? :) Does it look equally snazzy or did we revert to the older style?

**Comment by allejo** [comment]
Just added a screenshot, I think it looks just as snazzy :smile: It preserves the same behavior as far as I can tell.

**Comment by joshgoebel** [comment]
Screen Shot 2021-08-01 at 4 42 03 PM

Could we get maybe 2px of padding between the double dashed lines so it's easier to see the bounding rects? (ie bottom padding on the spans I think)  I'll merge either way but I think that would be  small improvement.

**Review by joshgoebel — APPROVED** [review]

**Comment by allejo** [comment]
image

I added a padding of 5px. 3px seemed like too little for me.

**Comment by joshgoebel** [comment]
Thanks.

**Pull request merged**
