### PR TITLE
updated tools/developer.html

### PR DESCRIPTION
**Pull request by shabbir23ah**
I have updated tools/developer.html as described  on issue #3729 

### Changes
3 lines changed and 2 new lines added

### Checklist
- [x] Tested nodejs build

### CODE REVIEW

**Comment by joshgoebel** [comment]
Awesome.  Lets add a changelog entry please.

**Comment by shabbir23ah** [comment]
Is this format correct for changelog?

Parser:

          - Replaced the old `hljs.highlight()` function call with the new one, as per the suggestion in the GitHub issue #3729.
          - Removed the click event binding for the `#update-highlighting` button and replaced it with a new `update()` function.
          - Added a `change` event listener for the `.languages` element that also triggers the `update()` function.

**Comment by joshgoebel** [comment]
And with a link/subscript to your GitHub, etc... just follow the pattern that's already there and I can edit it if it's not quite right.

**Comment by shabbir23ah** [comment]
Updated changelog on CHANGES.md

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
