### PR TITLE
Add highlighting support for Arturo

### PR DESCRIPTION
**Pull request by drkameleon**
Added highlighting support for the Arturo programming language:

Website: https://arturo-lang.io/
Repo: https://github.com/arturo-lang/arturo

### Changes

Added new language support

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Thanks so much for your contribution!  Sadly, due to lack of maintainer time we no longer merge additional languages into the core library - but we'd love to have your grammar as a 3rd party language module if you'd be willing to maintain it over time.  It's quite easy to convert what you've already got into a 3rd party module. (it really just involves moving some files around, building, then pushing into your own repository)

We can host that repository here at the `highlightjs` organization (and are happy to) or you can host it on your own GitHub. *The key thing is you need to be willing to maintain it, deal with any future issues, etc - i.e. become the de-facto maintainer of the module.*  Once you have your repository all setup we will happily accept a PR to add a link to our list of supported languages here in the official repo.

Please read https://github.com/highlightjs/highlight.js/blob/master/docs/language-contribution.rst.

An example 3rd party language repo:
https://github.com/highlightjs/highlightjs-robots-txt

**Comment by drkameleon** [comment]
> Thanks so much for your contribution! Sadly, due to lack of maintainer time we no longer merge additional languages into the core library - but we'd love to have your grammar as a 3rd party language module if you'd be willing to maintain it over time. It's quite easy to convert what you've already got into a 3rd party module. (it really just involves moving some files around, building, then pushing into your own repository)
> 
> We can host that repository here at the `highlightjs` organization (and are happy to) or you can host it on your own GitHub. _The key thing is you need to be willing to maintain it, deal with any future issues, etc - i.e. become the de-facto maintainer of the module._ Once you have your repository all setup we will happily accept a PR to add a link to our list of supported languages here in the official repo.
> 
> Please read https://github.com/highlightjs/highlight.js/blob/master/docs/language-contribution.rst.
> 
> An example 3rd party language repo:
> https://github.com/highlightjs/highlightjs-robots-txt

My main idea was to enable syntax highlighting for Discord, as - at least to my knowledge, they do use highlight.js for the code snippets. What would suggest?

**Comment by joshgoebel** [comment]
I'd suggest reaching out to their support team.  You could even put them into contact with me if you like.  3rd party grammars are trivially easy for any users of the library to integrate with.

Also worth noting: There is nothing magical about being in the core library.  Many integrators purposely only use a purposeful subset of the languages we provide (which we recommend) - ultimately first party or third party Discord will highlight the languages they wish to highlight.  No one is stopping them from using a 3rd party grammar if you should create one and they designed to highlight your language.

**Comment by joshgoebel** [comment]
Closing per existing policy (as mentioned).

**Pull request closed without merging**
