### PR TITLE
enh(parser) new highlight() API

### LINKED ISSUE #2277: Propose: Improve `highlight` API
The old API:

```js
highlight(language, code, ignore_illegals, continuation) {
```

The new API take an options object literal:

```js
highlight(code, { language, ignoreIllegals}) {}
```

So to upgrade your code:

```js
// before
html = highlight("vbscript","your code goes here", true)
// after
html = highlight("your code goes here", {language: "vbscript", ignoreIllegals: true })
```

Advantages:

- target of the verb [highlight] is now the first argument, which makes more sense, such as `format(drive)`, `highlight(code)`
- no need to remember order of the arguments
- we can still support the old API for legacy (ie, non-breaking change)
- fewer arguments are generally better (easier to understand, now at the call site you always see the names of the optional arguments, etc)

Checklist:

- [x] new `highlight` API as shown above
- [ ] <del>`highlightAuto` -> `highlight(code)`</del>
- [ ] <del>`highlightAuto` is deprecated</del>
- [x] `highlightBlock` -> `highlightElement` #3003
- [x] `highlightBlock` -> deprecated #3003
- [x] `fixMarkup` -> deprecated, will be removed with v11
- [x] `initHighlightingOnLoad` -> `highlightAll()`
- [x] `initHighlighting` -> `highlightAll()`

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2277.

### Changes

- Implements the new `highlight(code, options = {})` API
- `language` and `ignoreIllegals` are options now (vs params)
- `continuation` is for internal use only and hence not supported any longer

Compatibility:

- v10.7 supports BOTH old and new APIs fully.
- v11 will support both as well (to ease migrations) but drop `continuation` support from the old API.
- v12 will drop old API support entirely.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Review by allejo — APPROVED** [review]
Do we want to output a deprecation message for this?

**Comment by paladox** [comment]
I'm wondering if we could add support for continuation again? We use it for the gerrit project specifically here https://github.com/GerritCodeReview/gerrit/blob/master/polygerrit-ui/app/elements/diff/gr-syntax-layer/gr-syntax-layer.ts#L445.

**Comment by joshgoebel** [comment]
This has been removed for many different reasons.  

- Technically it's leaking parser internals. 
- It's not intended to "drive the parser" at all (line by line or otherwise).  
- It merely is a detail of our internal sublanguage implementation - one that's likely to change in the future.
- **Line by line driving is fundamentally broken.**  Grammars rules are not guaranteed to break cleanly at line boundaries - and some most definitely do not.
- It was added to our documentation in 2019 that this is not intended to be used to for line-by-line highlighting (93badf79c) [as soon as I found out people were doing so]. 

Many of the things we'd like to investigate in v11 may require deep internal changes.  We might switch from an iterative parser to a completely recursive parser. There is rethinking sublanguages (#1263), a potential new back-tracking parser (#1140), etc.   Just because a line has been processed may not even mean it's processed.  We might hit a rule mismatch a few lines later and then rewind and try again with an entirely different matching strategy.

To allow us to iterate as freely as possible without worrying about breaking changes that means our internals need to be fully internal.  As such `continuation` is gone... and `_top` becomes private API. No state in, no state out.

---

To do line-by-line content _properly and 100% correctly_  one should post-process the final output (which can be done with 10 lines of JS or so). There are other options with the **private** Emitter API, but use at your own risk.  Post-processing the final text output is the most stable choice and what most implementors should do.

**Comment by joshgoebel** [comment]
Someone should really write a `line_by_line` plugin using `after:highlight` that wraps this up nicely and then we could just point everyone to that.

**Comment by paladox** [comment]
@joshgoebel I guess it should be:

‘’’html

result = this.hljs.highlight(
        baseLine,
        {
            language: this.baseLanguage,
            ignoreIllegals: true
        }
        state.baseContext
      );

result.value = result.value.split('\n').map(line => {
     const prepend = tokenStack.map(token => `<span class="${token}">`).join('');
     const matches = line.matchAll(/(<span class="(.*?)">|<\/span>)/g);
     for (const match of matches) {
       if (match[0] === '</span>') tokenStack.shift();
       else tokenStack.unshift(match[2]);
     }
     const append = '</span>'.repeat(tokenStack.length);
     return prepend + line + append;
   }).join('\n');
this.baseRanges.push(this._rangesFromString(result.value, rangesCache));
‘’’

?

**Comment by paladox** [comment]
So this https://gerrit-review.googlesource.com/c/gerrit/+/302602 ?

**Comment by joshgoebel** [comment]
You tell me...?   I don't completely follow larger context of what you are doing here or what baseLine and revisionLine are...

**Comment by joshgoebel** [comment]
@paladox On an unrelated note: https://github.com/gerrit-review/gerrit/blob/master/polygerrit-ui/app/elements/diff/gr-syntax-layer/gr-syntax-layer.js#L349

If these are still actual issues today I'd love to see issues filed and perhaps we can fix them so you don't have to deal with them downstream.

**Pull request merged**
