### PR TITLE
PureBASIC 5.60

### PR DESCRIPTION
**Pull request by tajmone**
Update PureBASIC language definition to version 5.60 (new keywords)

### CODE REVIEW

**Comment by tajmone** [comment]
Sorry for the unclean commits history ... the changed file is just the language definition.

**Comment by azjio** [comment]
I used the script on the official forum PureBasic, but it is not enough highlighting code.

**Comment by tajmone** [comment]
@azjio:
> I used the script on the official forum PureBasic, but it is not enough highlighting code.

In what sense? It doesn't highlight at all or it doesn't highlight well?

I've used it in many projects and it's working fine. Here you'll find some prebuild hjs packages for PureBasic (modded version, slightly old hjs version) with full examples and instructions:

- https://github.com/tajmone/purebasic-archives/tree/master/syntax-highlighting/highlight.js

Here's a live example of PB code being highlighted:

- https://tajmone.github.io/doxter/

**Comment by azjio** [comment]
look here adapted script http://forum.ru-board.com/topic.cgi?forum=2&topic=5708&start=80#14
Check the way it works on the site here https://www.purebasic.fr/english/viewtopic.php?f=12&t=73662&sid=76d08736cb21fdf6e74cc1ab0ca99f69

**Comment by tajmone** [comment]
I don't see any PB code on the page of first link. 

The second link point to the PB forum, but the forum doesn't try to load the hjs package at all.

In order to make Highlight.js work on CMSs, Forums softwares, etc., you'll need to edit the application template to ensure:

1. It loads the precompiled Highlight.js package with the languages you need.
2. It emits the correct tags around code blocks, so that hjs can find them and auto-detect the code language.

But this is not an issue specific to the PureBasic language, but a general issue with setting up HJS.

You'll probably find better support by asking help on the community support forums for these specific web forum applications (phpBB, etc.), they might know how to adapt the underlying template, and if there are any conflicts with other JS plugins.

**Comment by azjio** [comment]
> I don't see any PB code on the page of first link
> you'll need to edit the application template to ensure:
The first link contains "edit template". Use Greasemonkey, Tampermonkey. When using javascript code highlighting [good](https://a.radikal.ru/a35/1909/fa/9ee6210c632d.png).

**Pull request merged**
