### PR TITLE
(scala) Add transparent keyword

### PR DESCRIPTION
**Pull request by mbovel**
### Changes

Add `transparent` to the list of keywords.

### Checklist
- [X] Added markup tests, or they don't apply here because...
- [X] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by mbovel** [comment]
cc @nicolasstucki

**Comment by joshgoebel** [comment]
We don't generally desire tons of sep 1 liner tests so I'd consolidate the `transparent-*` markup tests into a single test... just separate the cases by a blank line.

Otherwise looks good.

**Comment by mbovel** [comment]
Thanks for the quick review!

>  I'd consolidate the transparent-* markup tests into a single test... just separate the cases by a blank line.

Done.

**Comment by FlorianCassayre** [comment]
:+1:
Note that we are still missing a few Scala 3 soft modifiers/keywords, namely:
* `infix`, `opaque`, `open` (soft modifiers)
* `as`, `derives`, `end` (soft keywords)

([source](https://docs.scala-lang.org/scala3/reference/soft-modifier.html))

**Pull request merged**
