### PR TITLE
Add support for Metasploit Framework console output

### PR DESCRIPTION
**Pull request by todb-r7**
First time trying to create a definition for highlight.js, I think I'm doing it right, but I also think I'm abusing the built-in classnames.

What I think is more correct is to  invent a `className` of `print_good` and say that it should inherit from `literal` but I haven't figured out how to do that (ditto for the other classnames).

Anyway, my whole goal here is to provide minimal highlighting for Metasploit Framework output without it getting mistaken as shell/bash output (which is usually the case, so weird literals get highlighted).

### CODE REVIEW

**Comment by todb-r7** [comment]
If a miracle occurs and this gets added, it'll resolve rapid7/metasploit-framework#8832.

**Comment by todb-r7** [comment]
Heya @isagalaev , is this still under active development? No snark intended -- I know how it gets with open source projects -- but I just notice the last commit (as of this writing) was back in June of 2017.

If this isn't under active development, maybe I can help out with that?

**Comment by isagalaev** [comment]
I'm trying to find time to finally wrap up the post about looking for a new maintainer with explanations about the state of things and what's needed to be done. Since a few people asked the same question recently, I think I'm going to be shamed enough into finally doing it the week after next :-)

**Comment by todb-r7** [comment]
Hooray for public shame!

Good luck! It's tough maintaining a 11,000 ⭐️ project all by your lonesome. :)

**Comment by isagalaev** [comment]
@todb-r7 that still took me quite a while, but here it is: https://github.com/isagalaev/highlight.js/issues/1678

**Comment by yyyc514** [comment]
@todb-r7 

**First of all, truly sorry for the long delay in getting back to you regarding this PR.** I see you and isagalaev did communicate a bit previously at least.

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-metasploit.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

Of course, it's also possible for users to build a custom `highlight.js` library including specific 3rd party modules - all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by todb-r7** [comment]
Hi! Yes, I’m totally interested in maintaining this. Hopefully with our Ghost blog platform (which uses highlight.js) can actually make use of 3rd party plugins, but even if not, I assume there are other bloggers out there who want to share Metasploit output from time to time.

Thanks @yyyc514!

**Comment by yyyc514** [comment]
Good luck. Repo created:

https://github.com/highlightjs/highlightjs-metasploit

**Pull request closed without merging**
