### PR TITLE
PHP Comments inside function invoke & declaration

### PR DESCRIPTION
**Pull request by doiftrue**
PHP language not supported php comments inside function invoke and function declaration.

### Changes
Added:
`hljs.C_LINE_COMMENT_MODE`
`hljs.HASH_COMMENT_MODE`

Was:
image

Become:
image

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Wow, did PHP go all comment agnostic? Is that new?

**Comment by doiftrue** [comment]
> Wow, did PHP go all comment agnostic?

I'm not quite sure what is meant by the word "agnostic".

> Is that new?

No, it's not a new feature, adding comments anywhere in the code has always been supported as far as I know.

**Review by joshgoebel — APPROVED** [review]
Looks good, but please add an entry to the CHANGLOG as well!

**Comment by joshgoebel** [comment]
Ping.

**Comment by joshgoebel** [comment]
Closing due to inactivity/lack of response.  If you return and have time we're happy to reopen this in the future.

**Pull request closed without merging**
