### PR TITLE
feat(javascript): Add big number syntax (n postfix)

### LINKED ISSUE #1797: JavaScript BigInt / arbitrary precision number support
Per TC39: https://github.com/tc39/proposal-bigint

Though technically a proposal, this is shipped in Chrome stable and Node.js. The syntax change is an optional `n` postfix on literal numbers, like

```js
let x = 10n;
let y = 0x10n;
let z = 0b0101n;
```

I think the change might be something like this ↓, and I'll tinker with rolling a PR to implement.

```diff
diff --git a/src/languages/javascript.js b/src/languages/javascript.js
index 24d4ae9a..d6a824a3 100644
--- a/src/languages/javascript.js
+++ b/src/languages/javascript.js
@@ -29,9 +29,9 @@ function(hljs) {
   var NUMBER = {
     className: 'number',
     variants: [
-      { begin: '\\b(0[bB][01]+)' },
-      { begin: '\\b(0[oO][0-7]+)' },
-      { begin: hljs.C_NUMBER_RE }
+      { begin: '\\b(0[bB][01]+)n?' },
+      { begin: '\\b(0[oO][0-7]+)n?' },
+      { begin: hljs.C_NUMBER_RE + 'n?' }
     ],
     relevance: 0
   };
```

### PR DESCRIPTION
**Pull request by tmcw**
Fixes #1797 - allows a `n` postfix for the JavaScript big integer syntax: https://github.com/tc39/proposal-bigint

### CODE REVIEW

**Comment by yyyc514** [comment]
Does this affect typescript or livescript or any of the other JS derivative languages?  Do you have any idea? :-)

**Comment by marcoscaceres** [comment]
I don’t think it would. The others would eventually need to support this.

**Comment by yyyc514** [comment]
> The others would eventually need to support this.

That's what I'm asking if we should go ahead and figure tha tout now vs later. :)

**Comment by marcoscaceres** [comment]
I think we should go ahead.

**Comment by yyyc514** [comment]
@tmcw Could you by any chance help with that?

**Comment by tmcw** [comment]
I've added support to TypeScript. It doesn't affect LiveScript or any derivative languages afaict.

**Comment by yyyc514** [comment]
@tmcw Thanks so much.

**Pull request merged**
