### PR TITLE
Add Dream Maker (BYOND)

### LINKED ISSUE #1673: DM grammar (needs package & maintainer)
There's [BYOND](http://byond.com) game platform and there's [DM](http://www.byond.com/docs/ref) language to make your own games on it.

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #1673

### CODE REVIEW

**Comment by PJB3005** [comment]
I uh, have no idea how to fix the CI status here.

**Comment by PJB3005** [comment]
Could I get some help on how to solve the language autodetection causing CI to fail? Thanks.

**Comment by yyyc514** [comment]
@PJB3005 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-dream-maker.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
> Could I get some help on how to solve the language autodetection causing CI to fail? Thanks.

You'd probably first want to rebase and see if this is still an issue. But the problem is your grammar is "claiming" our XML sample file and declaring it to be "dm" instead of "xml" (when we know it's xml).

It's likely you might be using too much relevance in your grammar.

**Comment by yyyc514** [comment]
```
  var CONSTANT = {
     className: 'literal',
     begin: /\b[A-Z_][A-Z_0-9]*\b/
   };
```

Something like this probably matches every XML tag... so you might want to add `relevance: 0` to that.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by PJB3005** [comment]
Been kinda busy lately so I guess I got to be the one that took a while to respond this time.

Anyways, I initially made this PR in the hopes that the change would eventually bubble up to Discord's client (I'm 99% certain Discord uses highlight.js and it would be really useful for our community to have good syntax highlighting for this obscure language). However I obviously don't see that ever happening if it'll be a separate package. I don't really use JS very often so I don't think I'd want to take up the role as a package maintainer for it. Thanks for asking though.

**Comment by yyyc514** [comment]
Well, if you change your mind, we'll be here.  Building high quality 3rd party packages (_with maintainers on record_) is the first step in seeing them go wider.  It's true this might take longer now and be a more complex road (than when just anything was just merged into upstream), but it is what it is.  

Over in PHP land the maintainer of the PHP port @allejo is considering distributing all the 3rd party languages with his port.  There still exists room for someone to do something similar here in the Javascript space - ie ship a *larger* build with a zillion languages, but it will require time, commitment, etc...

If Discord does use HLJS and you know someone over there you could put me in touch with, I'd be happy to talk to them about the pros and cons of building a custom build.

**Pull request closed without merging**
