### PR TITLE
(chore) min change threshold for size report

### PR DESCRIPTION
**Pull request by bradleymackey**
±5 byte threshold to avoid reports for hash changes and tiny edits.

### Changes

- GitHub workflow change only.

### Checklist
- [x] markup tests don't apply
- [x] CHANGES.md change unneeded? Consider hotfix to #3400

### CODE REVIEW

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
Shouldn't we et a size report for this change? (even though it obviously won't change anything)

**Comment by bradleymackey** [comment]
It looks like the workflow ran - it probably doesn't comment if there's no changes.

**Comment by joshgoebel** [comment]
Error: compressed-size-action was unable to comment on your PR.
489
This can happen for PR's originating from a fork without write permissions.

**Comment by bradleymackey** [comment]
I'll look into this a bit more to see if there's a workaround in GitHub actions - I apologise for this oversight.

**Comment by joshgoebel** [comment]
https://github.com/preactjs/compressed-size-action/issues/54

**Comment by joshgoebel** [comment]
> I'll look into this a bit more to see if there's a workaround in GitHub actions - I apologise for this oversight.

Did you learn anything?

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
I'm merging since it's the right idea, even if it's not working properly yet.

**Comment by bradleymackey** [comment]
@joshgoebel Sorry for never getting round to this, this project fell off my radar for a bit! I'll still try to look into this after I work on a few outstanding grammar-level changes needed to Swift.

**Pull request merged**
