### PR TITLE
Support Swift multiline strings, update keywords

### PR DESCRIPTION
**Pull request by alejandro-isaza**

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
I tried to but I'm not well versed at node and couldn't get `npm test` to work...

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
```

**Comment by egor-rogov** [comment]
@alejandro-isaza First build for node, then run tests:
```
nodejs tools/build.js -t node
npm test
```

**Comment by egor-rogov** [comment]
@alejandro-isaza Fine! Please also add a line to `CHANGES.md` (in Improvements section under Master) and to `AUTHORS.md`, and you are done.

**Comment by alejandro-isaza** [comment]
Done

**Pull request merged**
