### PR TITLE
Add support for the Oz language

### PR DESCRIPTION
**Pull request by layus**
This adds minimal support for Oz.

### CODE REVIEW

**Comment by yyyc514** [comment]
@layus 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-oz.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by layus** [comment]
Hi @yyyc514,

I am all fine to be the maintainer of a plugin hosted at https://github.com/highlightjs.

What needs to be done ?

**Comment by yyyc514** [comment]
I created a repo for you: https://github.com/highlightjs/highlightjs-oz

Take a look at my own simple robots grammar for a pattern to follow:

https://github.com/highlightjs/highlightjs-robots-txt

---

If you check out the repository INSIDE your highlight.js checkout, you can use the new build process (https://github.com/highlightjs/highlight.js/pull/2312) to generate a CDN module for you: 

```
cd highlight.js
mkdir extra
cd extra
git clone [your repository]
cd ..
node ./tools/build.js -t cdn
```

Just building the CDN build (which will build ALL of the languages, including yours) will also helpful build a ready-to-go CDN module for you inside your own repos `dist` folder.

If that's too much you can just go without the `dist` folder until this is all folder into an actual release later this month.

**Comment by layus** [comment]
Thanks !

I stumbled on the fact that your new build system is not merged yet, but finally made it work (after updating node from v8 to v10...)

I did not find how to run tests, but this was okay back in the time of the PR. It should still be good enough.

**Comment by yyyc514** [comment]
If you have detect and markup files in the proper locations then just running the full suite will also run your tests.  In the future we hope to allow running them individually, easily.

**Pull request closed without merging**
