### PR TITLE
Add polish README translation

### PR DESCRIPTION
**Pull request by michaeltomasik**
As I discussed with @joshgoebel I translated README to polish. I will try to find now some polish people to review this.
Also if somebody could change the label to `hacktoberfest-accepted` It would be great

https://github.com/highlightjs/highlight.js/issues/2777### Changes

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please see thoughts on: https://github.com/highlightjs/highlight.js/issues/2777

I can't see a way to do this without at least a team of 3 (who know Polish)... do you have co-workers or others you'd know you'd like to volunteer long-term to help us keep this current?  And are you interested in helping with our other docs, or just the README?

**Comment by michaeltomasik** [comment]
@joshgoebel I will ask around

**Review by sa-orlov — APPROVED** [review]

**Review by sa-orlov — APPROVED** [review]

**Comment by joshgoebel** [comment]
@sa-orlov Please stop randomly approving all our PRs.  Thanks.

**Review by sa-orlov — APPROVED** [review]

**Comment by joshgoebel** [comment]
_Closing this PR for now._  The related issue remains open and this PR can always be reopened if we find enough of a team to handle ongoing translations.

**Pull request closed without merging**
