### PR TITLE
Add reference to 3rd party Dafny grammar

### PR DESCRIPTION
**Pull request by saltiniroberto**
### Changes
Add reference to 3rd party Dafny grammar

### Checklist
- [x] Added markup tests
- [ ] Updated the changelog at `CHANGES.md`. I am not aware that this is required for such a PR.

### CODE REVIEW

**Comment by joshgoebel** [comment]
> charset="UTF-8"

Shouldn't need this if you're using out build tools.

> hljs.initHighlightingOnLoad();

Could you please update the docs to use the new v11 API?

**Review by joshgoebel — APPROVED** [review]

**Comment by saltiniroberto** [comment]
@joshgoebel I have updated the docs. I hope that it looks good noew.

**Comment by joshgoebel** [comment]
Your react example still using the old API. :)

**Comment by saltiniroberto** [comment]
Thanks @joshgoebel for pointing that out.
I have now fixed it by referencing the official highlight.js documentation for any non-in-browser usage.

**Pull request merged**
