### PR TITLE
Add multiple: OCL, ATL, XCore

### PR DESCRIPTION
**Pull request by sunye**
Added an initial proposal for 3 MDE languages:

- OCL, Object Constraint Language (OMG Standard)
- ATL, Atlas model Transformation Langauge (Eclipse Foundation)
- Xcore, Textual notation for Ecore (Eclipse Foundation)

### CODE REVIEW

**Comment by sunye** [comment]
I changed the ATL and Xcore code samples for better automatic detection.

**Comment by yyyc514** [comment]
@sunye  

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-xcore.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
> Added an initial proposal for 3 MDE languages:

I'm not sure how these three are related.  What is an MDE language?

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by sunye** [comment]
> > Added an initial proposal for 3 MDE languages:
> 
> I'm not sure how these three are related. What is an MDE language?

What I called a Model-Driven Engineering (MDE) languages, are languages used within the Eclipse Modeling Framework (https://www.eclipse.org/modeling/emf/) ecosystem. 

Xcore is a (meta-)language for describing other modeling languages, OCL is a constraint language that is used with UML and also with Xcore to constraint the syntax of modeling languages.

Finally, ATL is a model transformation language, which can transform models from one language to another.

**Comment by sunye** [comment]
> **Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).
> 
> As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

Yes, I would like to.

**Comment by yyyc514** [comment]
So should these be 3 different language packages then or one big package with all three?

**Comment by sunye** [comment]
> So should these be 3 different language packages then or one big package with all three?

That's a very good question. These are not the only languages used in the MDE community, there are several others, which all have a small number of users. I believe that people that could be interested in one of these languages would also be interested in the others. I think that just one big package containing these languages would be fine, but it's upon to you to choose the best configuration.

**Comment by yyyc514** [comment]
> I think that just one big package containing these languages would be fine, but it's up to you to choose the best configuration.

Not really.  Your package, your call. :-) If I had a strong opinion I'd share, but I'm not sure I do.  If these indeed share a commonality regarding MDE then perhaps a single package could work... but what to call it?  

And then if someone else wants to add other MDE languages to your package, do you want to become the defacto package that all MDE languages drop into?

I think the "one package per language" simplified naming of repos, but we already have people publishing more than one language per repo so if that's much easier for maintainers, then I don't think we should stop that... so just tell me how you'd like to proceed and perhaps we can brainstorm on the naming of the repo (if you want one hosted here at the highlightjs organization).

**Comment by sunye** [comment]
> Not really. Your package, your call. :-) If I had a strong opinion I'd share, but I'm not sure I do. If these indeed share a commonality regarding MDE then perhaps a single package could work... but what to call it?
> 
> And then if someone else wants to add other MDE languages to your package, do you want to become the defacto package that all MDE languages drop into?
> 
> I think the "one package per language" simplified naming of repos, but we already have people publishing more than one language per repo so if that's much easier for maintainers, then I don't think we should stop that... so just tell me how you'd like to proceed and perhaps we can brainstorm on the naming of the repo (if you want one hosted here at the highlightjs organization).

In this case, since it's a small community, I think that a single repo is fine. I think that it could become the standard project for all MDE-related languages.

**Comment by yyyc514** [comment]
@sunye 

https://github.com/highlightjs/highlightjs-mde-languages

Repo created.

**Pull request closed without merging**
