### PR TITLE
I do not know if it is bad idea to update the CHANGE.md

### PR DESCRIPTION
**Pull request by gusbemacbe**
Since you, @ldct, allowed @TristianK3604 to update the CHANGE.md, I solved to improve CHANGE, adding missed improved and styles since you merged two weeks ago.

### CODE REVIEW

**Comment by gusbemacbe** [comment]
How?

**Comment by marcoscaceres** [comment]
https://github.com/github-changelog-generator/github-changelog-generator Is what I use for other projects. Works really well.

**Comment by gusbemacbe** [comment]
Have you already generated it? My name and my style name do not appear there in the CHANGES.md

**Comment by marcoscaceres** [comment]
@gusbemacbe no - not yet. Still doing it manually.

**Comment by marcoscaceres** [comment]
@gusbemacbe can you resolve the merge conflicts?

**Comment by gusbemacbe** [comment]
Yes, wait

**Comment by gusbemacbe** [comment]
I tried to merge new branch forked from your most recent repository into my own master, but due to conflicts, I had to delete my repository.

**Comment by gusbemacbe** [comment]
I have just forked, can I modify a bit? Or do I let you generate the changelog?

**Comment by marcoscaceres** [comment]
Just modify it manually :) We won't do the auto-generate just yet, because the styles are different. We might start autogenerating in 9.13, as it saves some times and reduces these kinds of merge conflicts.

**Comment by gusbemacbe** [comment]
It seems you have removed @ahmadawais and his style from the CHANGES.md. You have to be careful with merging the old CHANGES into new CHANGES.

**Pull request closed without merging**
