### PR TITLE
Add Omnis

### PR DESCRIPTION
**Pull request by jasongiss**
Support for the Omnis programming language, used by [Omnis Studio](https://omnis.net).

### CODE REVIEW

**Comment by yyyc514** [comment]
We're currently in a large discussion about how to handle language submissions:

https://github.com/highlightjs/highlight.js/issues/2149

Currently the maintainers don't have the time to review or maintain any new languages and related issues - so we've been recommending that they be published as separate packages/repos. To see what that looks like:

https://github.com/highlightjs/highlightjs-robots-txt

Just a heads up.

**Comment by jasongiss** [comment]
Thanks very much for the pointer, @yyyc514.

That is an interesting read, and I feel for the position you maintainers are in.

I am happy to wait until a decision is made on how best to handle new languages - good luck with that!

**Comment by jasongiss** [comment]
@egor-rogov I would certainly be willing to maintain a repo for the Omnis language.

@yyyc514 I'm very sorry, but I really don't have enough free time at the moment (and probably not the expertise) to be able to commit to helping maintain a "community" repo.
I can put time into maintaining the Omnis language, as I work on the Omnis development team, so I can do that on 'work time'. 
I'm happy whether that's in a separate repo, or a community repo (I just wouldn't be able to put much time into other languages).

For our particular use-case, it's nice to be able to build a single JS package with our language embedded (which I guess would be more likely with the community repo?), but happy to go with whatever the official technique becomes. 
The main thing for us is just having a central place where the language definition can be found and contributed to.

**Comment by yyyc514** [comment]
> I can put time into maintaining the Omnis language, as I work on the Omnis development team, so I can do that on 'work time'.

Nice. 

> For our particular use-case, it's nice to be able to build a single JS package with our language embedded (which I guess would be more likely with the community repo?)

Not sure likely is the right word. I want it to be easy no matter where the cards fall on structure of repositories. Just we aren’t there yet. 

It’s not particularly hard now - for a single language - just very manual.

**Comment by jasongiss** [comment]
> Not sure likely is the right word. I want it to be easy no matter where the cards fall on structure of repositories. Just we aren’t there yet.
>
>It’s not particularly hard now - for a single language - just very manual.

I agree - the process currently works well, it just needs a clever solution for adding languages in a maintainable way.

**Comment by yyyc514** [comment]
@jasongiss 

https://github.com/highlightjs/highlight.js/issues/2328

**Comment by yyyc514** [comment]
Closing this as discussion can continue on #2328.

**Pull request closed without merging**
