### PR TITLE
fix(devtool): use correct CSS to hide psuedo element used for hacking…

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
… the width of the wrapping content to be *at least* the width of the green class tag / decoration

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
This was broken for me in that the padding on the bottom was negative or something weird.  How does this look for you?

**Comment by NullVoxPopuli** [comment]
Just pushed this 
image
image
image
image

So far, it seems the best way to align things is to not touch the display property on the span element... which is obnoxious, because it makes aligning things to the baseline hard

**Comment by NullVoxPopuli** [comment]
_but_, I did find a _really_ weird display option that allowed the border to expand... idk 🤔 Gonna keep looking

**Comment by joshgoebel** [comment]
What was wrong with what I showed you again?

**Comment by NullVoxPopuli** [comment]
I don't remember you showing me anything?

**Comment by NullVoxPopuli** [comment]
also, I think this is in the best place _I_ can get it for now.
I am not happy with the various ways that blocks are broken up and separated from wrapping elements (because of how the code is wrapped with spans).

For example:

```
<style>
  code
</style>
```
all 3 of those lines end up being sibling elements, which makes any sort of `display: inline-*` not great. _but_, we need inline-flex for align-items: baseline. 
_but_, with inline-flex, _often_, entire sections of code are moved into one line, which is _worse_. :upside_down_face:

**Comment by joshgoebel** [comment]
Grrrr, I really thought I pushed a commit... let me take a look at this latest version.

**Comment by NullVoxPopuli** [comment]
@joshgoebel Rebased and fixed the text-alignment issue (I think)

**Comment by NullVoxPopuli** [comment]
image


There is also a compressed version if we want 🤷 
image

**Comment by joshgoebel** [comment]
Compressed please.

**Comment by NullVoxPopuli** [comment]
Spacing reduced and PR rebased

**Pull request merged**
