### PR TITLE
Add xtlang

### PR DESCRIPTION
**Pull request by cyblue9**
Support for [xtlang](https://extemporelang.github.io/docs/overview/philosophy/) language.
(Issue: https://github.com/extemporelang/highlight.js/issues/1)

xtlang syntax looks like scheme, but xtlang has type system and is compiler language.
It is used in [Extempore](https://extemporelang.github.io/).

This is inspired by [pygments one](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/lisp.py?at=default&fileviewer=file-view-default#lisp.py-2420).

Please review!

### CODE REVIEW

**Comment by benswift** [comment]
Hey, I'm one of the core [Extempore](https://github.com/digego/extempore) developers, so if you have any questions from that side of things I'm happy to help out 😄

**Comment by marcoscaceres** [comment]
Hi @cyblue9, @benswift, we are looking at moving languages into their own repositories, for example:
https://github.com/highlightjs/highlightjs-cshtml-razor

That way, they can be included seperately to our core library and can be maintained indecently. There are a few kinks we are still working out, but if you are interested, I can create a repository for you at the org level, and you can maintain your language there.

**Comment by marcoscaceres** [comment]
hehe, not "indecently" - independently. Autocorrect win!

**Comment by benswift** [comment]
Wow - a scandalous proposal 😉 

Sure, if that's the way it's going anyway then I'm happy to have it in a separate repo under the hljs org. That way we don't have to hassle the core team as we squash the edge cases (which I'm sure there'll be a few of initially).

Is it already possible to build hljs with support for one of these "language modules"? Or do I need to hack the build script manually?

**Comment by marcoscaceres** [comment]
@cyblue9, @benswift, gave you both admin over in https://github.com/highlightjs/highlightjs-xtlang 

Again, take a look at the structure for:
https://github.com/highlightjs/highlightjs-cshtml-razor

Basically, you should hopefully be able to copy that. Apologies for not having proper instructions yet, we are super resource restrained on the project as it's just a small handful of people in the community trying to maintain it.

**Comment by benswift** [comment]
Great, acknowledged. @cyblue9 , are you happy to look at that **cshtml-razor** repo and package up the xtlang one in a similar way?

Re: resource constraints, I get it - we appreciate all the work you guys do 🙌

**Comment by marcoscaceres** [comment]
@cyblue9, we have a Slack channel that I can invite you to if you have any questions or need some additional help. I'll need an email to invite you. You can either email me (marcos@marcosc.com) or post it here and I'll send you an invite.

**Comment by cyblue9** [comment]
@marcoscaceres 
Thank you to create highlightjs-xtlang repo. Good job!😁
> You can either email me (marcos@marcosc.com) or post it here and I'll send you an invite.

OK! This is my email address.
cy.blue.9@gmail.com
Thank to invite me.

@benswift 
> are you happy to look at that cshtml-razor repo and package up the xtlang one in a similar way?

Yes! I will try it!
After I package up it, please review it.🙏

**Comment by benswift** [comment]
>  After I package up it, please review it.🙏

Will do for sure 🙂

**Comment by cyblue9** [comment]
Hi, @marcoscaceres @benswift!

Finished creating [highlightjs-xtlang repo](https://github.com/highlightjs/highlightjs-xtlang) !
(Sorry, to be late...)

Plase review and PR!

- [ ] Sentence of README

**Comment by benswift** [comment]
Great, really nice work. I'll be finished marking next week and will have a look at this asap.

**Comment by yyyc514** [comment]
@benswift @cyblue9 

> Is it already possible to build hljs with support for one of these "language modules"? Or do I need to hack the build script manually?

This is possible now with my new build system PR:

https://github.com/highlightjs/highlight.js/pull/2312

And related discussion on 3rd party repos:

https://github.com/highlightjs/highlight.js/issues/2328

As marcoscaceres mentioned you also have options with just `npm` and basic requires stuff as well (assuming you also publish your 3rd party module as a npm package)... what my PR makes easy is if you want to build a SINGLE monolithic`highlight.js` that includes 3rd party languages, or want to easily publish your own CDN modules, or build your own custom npm package from scratch.

Closing this PR since we now have https://github.com/highlightjs/highlightjs-xtlang.  Always happy to answer any questions or concerns though!

**Comment by benswift** [comment]
Great, thanks @yyyc514 

Sorry about the delayed reply - I've been on holidays.

**Comment by cyblue9** [comment]
@yyyc514 

Nice! Good job! Thank you😀

**Pull request closed without merging**
