### PR TITLE
Add new language COBOL

### PR DESCRIPTION
**Pull request by FrankR85**

### CODE REVIEW

**Comment by NicolasStr** [comment]
I'm in a urgent need of this. I can see the implementation have been done on an old version on of highlightjs. I will make a new PR with your implementations if you're okay with that @marcoscaceres ?

**Comment by NicolasStr** [comment]
Looks like there's still some problemes with the implementation. I'll check it out tonight.

**Comment by marcoscaceres** [comment]
Hi @NicolasStr (and @FrankR85), sorry for the slowness here... we are moving languages to their own repos so they can be maintained independently and don't get stuck in review queues like this. 

If I make you are repo under the highlightjs org, can you maintain the language definition? Here is an example of what a common set up looks like:
https://github.com/highlightjs/highlightjs-GN

**Comment by NicolasStr** [comment]
Yeah, I think I could work on this.
It will take some time like 1 month but yes.

**Comment by marcoscaceres** [comment]
Ok, ping me when ready.

**Comment by NicolasStr** [comment]
Ok!

**Comment by yyyc514** [comment]
CC: @WASAB95 @FrankR85 

https://github.com/highlightjs/highlight-cobol

As mentioned earlier, we have a repo all ready to go.  I'm not sure which of you has permission to it (or both), but whenever one of you is ready to get the ball rolling if you don't have access ping @marcoscaceres or @egor-rogov and they'll take care of it for you.  Hopefully we can work together and merge the best of both PRs in the single repo.

If you have any questions or need any help, feel free to ask.

As we're not merging either of these PRs into core, I'm closing them both in my efforts to tidy up things before the new year.  Happy Holidays!

---

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Pull request closed without merging**
