### PR TITLE
Support for GN

### PR DESCRIPTION
**Pull request by petrhosek**
This change implements support for [GN](https://gn.googlesource.com/gn)
build system language syntax highlighting.

### CODE REVIEW

**Comment by petrhosek** [comment]
Ping, would it be possible to review this change?

**Comment by juliehockett** [comment]
pinging again, I'd love to see this go through. Would definitely be a strong improvement for me personally.

**Comment by marcoscaceres** [comment]
Hi, we are currently moving new languages out into their own repositories. @petrhosek or @juliehockett, if make you a repository, would you be willing to maintain the language definition? 

See: https://github.com/highlightjs/ for example repositories.

**Comment by petrhosek** [comment]
Yes, I'd be happy to do that. Can you please the repository for us?

**Comment by marcoscaceres** [comment]
Done. @petrhosek, you might like to copy what's in https://github.com/highlightjs/highlightjs-terraform  ... it includes testing. You can just replace things as needed. Once you are happy, you can `npm publish` it.

**Pull request closed without merging**
