### PR TITLE
Add support for TLA+ specification language

### PR DESCRIPTION
**Pull request by All-less**
Hi there,

I added support [TLA+ specification language](https://lamport.azurewebsites.net/tla/tla.html), which is proposed by Leslie Lamport and is widely used in both industry and academia. Please review.

### CODE REVIEW

**Comment by japgolly** [comment]
What's required to get this merged? Is there anything I can do to help?

**Comment by rberenguel** [comment]
@japgolly likewise, I checked the PR and everything seemed correct... aside from that, not sure what else we can do :/

**Comment by All-less** [comment]
The PR says "At least 1 approving review is required by reviewers with write access." Do you have the write access to this repo? @rberenguel @japgolly

**Comment by rberenguel** [comment]
@All-less no, so we can't do much more than check that the list of keywords is correct and the example sound

**Comment by yyyc514** [comment]
@All-less 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-tla-plus.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
@japgolly @rberenguel Thanks for trying to help out!  If @All-less isn't open/available for maintaining this as a 3rd party grammar, would either of you two want to help?

**Comment by rberenguel** [comment]
Hi @yyyc514, thanks for your work on this. Sadly I don't have the bandwidth to keep this up to date, but I'm glad to see there is a new way to add languages to highlight-js.

**Comment by yyyc514** [comment]
> I'm glad to see there is a new way to add languages to highlight-js.

It's not exactly a new way, but we're making it much easier to do with tooling and documentation (coming soon). :-)

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Pull request closed without merging**
