### PR TITLE
New language - CSHTML Razor

### PR DESCRIPTION
**Pull request by romanresh**
This PR contains a parser for the Razor CSHTML language. CSHTML is a markup language created by Microsoft for ASP.NET MVC and ASP.NET Core applications. It allows to create markup containing both C# and HTML code. 

If a cshtml file contains only HTML markup and doesn't contain any razor expressions or C# code its content will be rendered as plain HTML text.

See more about the CSHTML Razor syntax here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor.

### CODE REVIEW

**Comment by romanresh** [comment]
The modified version of highlight.js (with Razor support implemented in this PR) is used on the following site: https://demos.devexpress.com/aspnetcore-bootstrap/GridView-Templates. 

You can obtain more examples of Razor code highlighting on other pages of this site (use the left navigation panel to find all demos).

**Comment by romanresh** [comment]
Hi @marcoscaceres . Would you please review this PR?

**Comment by marcoscaceres** [comment]
Hi @romanresh, we are looking at splitting languages out into their own repositories. If make you a repository within this hljs organization, would you be willing to maintain the language?

**Comment by romanresh** [comment]
Should I do smth to help you with the new repository?

**Comment by marcoscaceres** [comment]
no, I’ll set things up for you. What’s a good name for the repo? “cshtml-razor”?

**Comment by romanresh** [comment]
yes, "cshtml-razor" is OK. 
Perhaps, the "vbhtml-razor" will also appear in a while, if there is enough interest.

**Comment by marcoscaceres** [comment]
sorry it too me a little long to get to this, @romanresh. Now done. Check your inbox.

**Comment by marcoscaceres** [comment]
Closing as this now has its own repo. https://github.com/highlightjs/highlightjs-cshtml-razor

**Pull request closed without merging**
