### PR TITLE
(puppet) Support Puppet's Epp templating engine

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by isagalaev** [comment]
This looks exactly like ERB. Is it indeed the same language?

**Comment by binford2k** [comment]
It is close, but not quite. Variables are decorated with `$`, curly braces instead of `do`/`end`, arguments for blocks are in slightly different position, interpolated strings use `${...}` instead of the `#`, etc.

It's the same idea as ERB, but with Puppet 4 as the backing language.

**Comment by paladox** [comment]
Needs rebasing and test needs fixing.

**Comment by yyyc514** [comment]
@binford2k 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-epp.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by binford2k** [comment]
@yyyc514 imho, this should not be a standalone module. It should be integrated with the same repository that hosts puppet.js, maybe even in the same file, because anyone writing Puppet code is also going to be writing epp code. In the same way that Ruby and erb are really the same language, Puppet and epp are really the same language.

**Comment by yyyc514** [comment]
Though I disagree that Ruby and ERB are "the same language", I do take your point.  Having related thing grouped can be helpful.

Is EPP part of Puppet's standard library or an add-on?

**Comment by paladox** [comment]
It's standard at least i didn't have to install anything extra to gain epp :)

**Comment by yyyc514** [comment]
I decided a while back that I would permit `pycon` (python console output) if someone ever submits it under the reasoning that we already have Python, and adding it is truly more of an "extension" of our Python support than an "addition of a new language".  This could fall under that same reasoning.  We do have ERB for Ruby (Ruby's standard templating engine).  And while I hate to say this will NEVER require maintenance in the future the scope of this is very tiny as it's just a wrapper for two sublanguages (xml and Puppet).  

So I will review this again with all that in mind.

**Comment by yyyc514** [comment]
@binford2k First I'd really need this rebased onto master and all the tests passing.  I am a little worried about auto-detection conflicts with ERB, but right now seems you're conflicting with routeros for some reason.  Though it has been quite some time.

If you just rebase and then run all the tests again it could be they'll pass.

**Comment by binford2k** [comment]
For sure. Rebased, waiting for tests. I'll be honest, I don't really grok how the autodetection works, so will completely defer to your judgement on that. EPP is part of core Puppet for the last few years.

**Comment by yyyc514** [comment]
> I don't really grok how the autodetection works, so will completely defer to your judgement on that.

Every language "competes" over all the detection samples so see which scores higher.  In a perfect world Ruby would always score higher for Ruby files.  The auto-detect tests REQUIRE this.

So `routeros` is detecting your file and saying it looks more like a router OS fie than a Epp file, so you might have to take a look at what Router OS looks like and WHY it thinks your sample file is a Router OS file and perhaps tweak or extend your sample.

**Comment by yyyc514** [comment]
@binford2k That's another small piece of the contribution puzzle, and part of the reason why things have changed.  It's really not enough to just whip up a grammar that supports your language (which sometimes can be the easy part).  To properly exist in core you have to understand the larger auto-detection picture and make sure your language doesn't conflict with others AND that others don't conflict with it.  That requires a very delicate balancing act - and it's even hard for the core maintainers sometimes.

It's very complex and a bit unfair, but we're stuck with it for now.  It seems to be one of the core selling features of Highlight.js. :-)

**Comment by yyyc514** [comment]
Closing again (for now). I just don't like to leave things hanging unresolved forever.

We can continue discussion and reopen whenever you have time and we figure out a PR that passes CI.  No rush.

**Comment by hashar** [comment]
My understanding is the blocker was the detect test case was erroneously recognized as `routeros`, with latest `main` it is `mel`. I could not find out how to reopen this pull request or amend it (I guess it is not possible) so I reproposed it with additions as #3805 3805

**Pull request closed without merging**
