### PR TITLE
Support multiline comments in protobuf

### PR DESCRIPTION
**Pull request by Paxa**
Fixes https://github.com/highlightjs/highlight.js/issues/2561

### CODE REVIEW

**Comment by Paxa** [comment]
@yyyc514 here is PR

**Comment by yyyc514** [comment]
Looks nice. Please add mention to CHANGES.md. :)

**Comment by Paxa** [comment]
Done

**Comment by yyyc514** [comment]
@Paxa Not that painful, eh? :-)

Thanks for much for your contribution!

**Pull request merged**
