### PR TITLE
Fixing the version and correcting the old paths

### PR DESCRIPTION
**Pull request by gusbemacbe**
* The README used the old version (9.4.0) and I replaced for 9.12.0. Review the main page and the usage page of the site. 
* I corrected the old paths, replacing siagalev for highlightjs.

### CODE REVIEW

**Comment by gusbemacbe** [comment]
@SirCmpwn, the README and the site needs new rework, because they both used the old version. The main page uses 9.12.0, but the usage page uses 9.4.0.

**Comment by ldct** [comment]
The changes to the README look good to me, but why is there an added file `an-old-hope.css`? Can you split this into a separate PR?

**Comment by isagalaev** [comment]
+1 to doing separate changes in separate branches in the future. @gusbemacbe I'm pretty sure GitHub has some intro docs on how you can work with separate branches in your fork and submit different PRs. It's a useful skill regardless :-)

**Comment by gusbemacbe** [comment]
@isagalaev, I am going to check the documentation for knowing how to separating correcting two different branches without using the branch master.

**Comment by ldct** [comment]
@gusbemacbe what I always do is  to create a new branch on my fork of a project (e.g. `git checkout -b`) and then open a PR from that branch

**Comment by gusbemacbe** [comment]
@ldct 

If I want to create two branches, one for theme and another for README, it means:

```
git checkout -b theme
git checkout - b readme
```

Then does it create two separate branches, avoiding to push to origin and to pull all files of two branches together? 

@isagalaev 

I think you must check the usage page:

image

It still uses the old version.

**Comment by isagalaev** [comment]
The page will change upon the next release.

**Pull request merged**
