### PR TITLE
chore(package): update deps

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes all security alerts except `knox > debug`, where [`knox`](https://github.com/Automattic/knox) is dead.

### CODE REVIEW

**Comment by saschanaz** [comment]
Woops, something's wrong. Fixing...

**Comment by marcoscaceres** [comment]
All green. @saschanaz, you ok for me to merge?

**Comment by saschanaz** [comment]
Absolutely!

**Comment by marcoscaceres** [comment]
Ok, will get this out tomorrow... and hopefully we don't break the intermanets again 😬😅😇

**Pull request merged**
