### PR TITLE
enh(reasonml) Improve highlighting of modules and content, remove function annotation

### LINKED ISSUE #1836: Pull out reasonml integration?
Hello! I'm a maintainer of Reason. @gmmorris has created to the reasonml highlight recently, and in order to iterate on it faster, I've pulled it out into https://github.com/reasonml-editor/reason-highlightjs.  I've been using it in place of the first-party one, and it's been solid.
Pulling the plugin out also makes it so that folks don't have to build highlightjs master to obtain it (which isn't always easily doable since it might be a transitive dependency). Last release was a year ago. Additionally, it seems that highlightjs would like to externalize the language plugins anyway; this would already be done.
So I'm wondering if we should just remove the reasonml plugin from this repo; if not, then I can sync that plugin back in if you'd like.

Thanks!

### PR DESCRIPTION
**Pull request by chenglou**
Fixes #1836

Building up to the work of #1793:

- Change reasonml to reason
- Improve highlighting of modules and content
- Temporarily remove the annotation for functions (many false positives)

### CODE REVIEW

**Comment by chenglou** [comment]
Not sure why these two tests are failing. Works fine locally

**Comment by marcoscaceres** [comment]
Build for target  “browser” seems to be failing.

**Comment by chenglou** [comment]
Worked locally

**Comment by yyyc514** [comment]
@chenglou Are you still around to work on this if I review it?  First it would need to be updated and resolve the conflicts with master.  And please don't rename the language file... that's a breaking change because people of CDN usage, etc...

**Comment by chenglou** [comment]
@yyyc514 so what would be the way to go to move toward `reason` instead of `reasonml`? For markdown code snippets etc.

**Comment by yyyc514** [comment]
> @yyyc514 so what would be the way to go to move toward reason instead of reasonml? For markdown code snippets etc.

For now just add `reason` as another alias... that way we don't break all the people already using `reasonml`.  If the ML is truly `wrong` now we could add this to the 10.0 list to "break" it officially.

**Comment by yyyc514** [comment]
You still out there?

**Comment by yyyc514** [comment]
Closing for inactivity (cleaning out old PRs for the new year).  If you return and have time to work on this again we could pick up the discussion at that point.  Happy new Year!

**Pull request closed without merging**
