### PR TITLE
fix(fsharp) Prevent `(*)` from being detected as a multi-line comment

### LINKED ISSUE #2697: (fsharp) `(*)` operators uncorrected detected as multi-line comment
**Describe the issue**
Using Discord's codeblock i posted a short snippet of F# code in which i used the Operators.(*) function. This led the highlighter to believe that the rest of the codeblock was part of a multiline comment. In F# a multi-line comment is writting with (* Comment Here *). 

**Which language seems to have the issue?**
fsharp and fs both produce this bug.

**Sample Code to Reproduce**
```fsharp
let decimator str =             
    match String.length str with
    | 0 -> ""                   
    | 1 -> str                  
    | len ->                    
        let index =             
            len 
            |> float        
            |> Operators.(*) 0.1          
            |> ceil             
            |> int              
            |> Operators.(+) 1            
            |> Operators.(-) len          
        str.[..index] 
printfn "%A" (decimator "1234567890") // => "123456789"
printfn "%A" (decimator "1234567890AB") // => "1234567890"
printfn "%A" (decimator "123") // => "12"
;;
```

**Expected behavior**
I expect there to be no highlighted comments in this code, aside from the inline comments in the last 3 lines.

**Additional context**

image

### PR DESCRIPTION
**Pull request by joshgoebel**
Resolves #2697

### CODE REVIEW

**Review by Eliemer — APPROVED** [review]

**Review by allejo — COMMENTED** [review]
Not sure how much effort you want to invest into the accuracy of F# comment parsing. I did some digging and found different examples online of comments.

According to [try.fsharp.org](https://try.fsharp.org/), the following code is valid F#. However, it looks like even GitHub doesn't get the highlighting correct.

```fsharp
// single line comments use a double slash
(* I can talk about the operator (*) without ending my comment *)
(* multi line comments use (* . . . *) pair -end of multi line comment- *)

// ======== "Variables" (but not really) ==========
// The "let" keyword defines an (immutable) value
let myInt = 5
let myFloat = 3.14
let myString = "hello"	//note that no types needed
```

And VS Code gets it slightly better

image

Here's how highlight.js behaves

image

**Comment by joshgoebel** [comment]
I don't understand:

```
(* I can talk about the operator (*) without ending my comment *)
```

Must the closing `*)`always be preceeded by whitespace also to be valid? Can anyone confirm?

**Comment by joshgoebel** [comment]
If this can't be 100% resolve/answered in a few days I will merge as-is as this is a huge improvement already.

**Comment by allejo** [comment]
Found the F# spec, https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf

Here are the relevant sections.

image

image

I think we can get away with the closing `*)` cannot have a `(` before it.

**Comment by joshgoebel** [comment]
Except we can't do negative look-behind... so we have to match `*)` or `\s*)`... and I don't understand the whitespace rules and I"m not going to read ALL that (I already skimmed) to have a 100% certainty. :-)  So I'm looking for an actual F-sharp coder to clear this up I think.

**Review by allejo — APPROVED** [review]

**Comment by joshgoebel** [comment]
👍  When the final edge case finally comes up and someone has the EXACT answer we'll re-review. :-)

**Pull request merged**
