### PR TITLE
chore: prepare for release 9.14.0

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Thanks @egor-rogov! I wasn't particularly rigorous with the enhancements, so might have missed some.

**Comment by marcoscaceres** [comment]
Release [failed](https://highlightjs.org/api/release/) unfortunately. I've asked @isagalaev to take a quick look.

**Comment by marcoscaceres** [comment]
9.14.1 was released. @isagalaev should be all good.

**Comment by isagalaev** [comment]
Sorry, I've been dealing with a family emergency at the moment, couldn't react in time.

The logs from https://highlightjs.org/api/release/ show that the version in the changelog wasn't updated to match the tag. But it looks like you've figured it out!

```
Traceback (most recent call last):
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 104, in handle
    self._handle(version)
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 43, in _handle
    assert lib.version(settings.HLJS_SOURCE) == version
AssertionError
```

**Comment by marcoscaceres** [comment]
@isagalaev sorry to hear that. Hope all is ok! Thanks regardless for taking time to look into it.

**Pull request merged**
