### PR TITLE
Add riscvasm assembler language

### PR DESCRIPTION
**Pull request by ckdur**
Greetings.

I needed to do a highlight for a new architecture named RISC-V for demo purposes. So I want to share with your awesome project.
I did a very-fast highlight language named 'riscvasm'. Tested personally and everything seems ok.
Hope this get accepted. Thank you.

Ckristian Durán

### CODE REVIEW

**Comment by Sannis** [comment]
@ckdur, are you have plans to fi detection tests for riscvasm?

**Comment by ckdur** [comment]
Sorry. I delayed doing this.

**Comment by ckdur** [comment]
Sorry but I don't know what "fi detection test" means or how to do it.

**Comment by yyyc514** [comment]
@ckdur 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-riscvasm.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
@ckdur @Sannis 

I think they meant "are you have plans to do detection tests for riscvasm?"

Meaning provide a sample file that your language properly detects and tune it's auto-detection so that it's balanced against other languages.  If not you should probably disable auto-detection for your language so it's not incorrectly detected.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Pull request closed without merging**
