### PR TITLE
Add .properties syntax

### PR DESCRIPTION
**Pull request by egor-rogov**
This PR adds support for .properties syntax (issue #1713).
Originally proposed by @bostko in #1717.

### CODE REVIEW

**Comment by egor-rogov** [comment]
@marcoscaceres Yes it can, although it's reasonably small and likely will not require maintenance.
I'd prefer to have it near Java (both in core or in separate repo).

**Comment by bostko** [comment]
@egor-rogov please rebase your pull request and exclude PostgreSQL commits from this PR.
Also it would be nice if you cherry-pick my commit from #1717

**Comment by marcoscaceres** [comment]
@bostko, @egor-rogov, I'm going to squash-n-merge it, so no problem if this doesn't get rebased. 

Let me know when you are good and if you are cherry-picking @bostko's commit.

**Comment by egor-rogov** [comment]
As far as I understand, cherry-picking another commit doesn't make sense in case of squash-n-merge?

**Comment by marcoscaceres** [comment]
Depends if there is something useful in the cherry-picked commit. Is there from the original PR missing?

**Comment by marcoscaceres** [comment]
Thanks for the ✅ @bostko. Taking that is all good to go.

**Pull request merged**
