### PR TITLE
[pkg] Fix to be able to minify with closure compiler. 

### PR DESCRIPTION
**Pull request by saksmt**
Calling addEventListener on window instead of nothing/global scope

### CODE REVIEW

**Comment by yyyc514** [comment]
What does the closure compiler do without this change?

**Comment by saksmt** [comment]
Complain about missing function (it reproduces only with ADVANCED compilation level)

**Comment by yyyc514** [comment]
And is there not some option you can pass to tell it how to treat addEventListener?  This is very common JS code and convention going back forever.  Sounds like it's closure that's broken here, not us?

**Comment by saksmt** [comment]
No, there is no such option. Also it's better not to rely on functions/variables from window scope to be present in global scope. Also if my memory not falling me such code will fail if `"use strict"` is enabled.

**Comment by yyyc514** [comment]
> Also it's better not to rely on functions/variables from window scope to be present in global scope. 

@marcoscaceres Is this a thing?  I'm not super familiar with the many "best practices" in JS.  AFAIK it's always been this way and I didn't realize this was a problem.

> Also if my memory not falling me such code will fail if "use strict" is enabled.

Do you have a reference for that?  Pretty sure our existing library works in some "use strict" safe environments as it stands now, so not sure this is correct.

**Comment by marcoscaceres** [comment]
> @marcoscaceres Is this a thing? I'm not super familiar with the many "best practices" in JS. AFAIK it's always been this way and I didn't realize this was a problem.

Yes, definitely a thing. ... I don't know about "use strict" failing - don't think that's the case... but being explicit about `window` is "a good thing"™️

**Comment by saksmt** [comment]
> Do you have a reference for that?

Sorry, can't find anything about this, probably I was wrong (in my defense I'm not a JS dev at all, just use it when I need to do something on frontend, which is pretty rare case) or I just always used JS with both strict mode and closure compiler every time and it got in my head that this restriction is from strict mode.

Anyways this fix is really small and affect nothing except for best practices and stuff. So why don't we just merge this and be done with it? So I could happily go and write in scalajs without worrying too much about size of a bundle :)

**Comment by yyyc514** [comment]
> Anyways this fix is really small and affect nothing except for best practices and stuff. So why don't we just merge this and be done with it? 

We will, I just wanted marco to sign off on the best practices stuff.  I'm worried if we made tiny [ultimately] unnecessary changes for every little build tool that's a rabbit hole I'd rather avoid.  But if it's best practice anyways... then sure, lets do it.

@saksmt Can you please add an entry to the changelog?

**Comment by yyyc514** [comment]
@saksmt Thanks!

**Pull request merged**
