### PR TITLE
themes: add new felipec theme

### PR DESCRIPTION
**Pull request by felipec**
Autogenerated with [vim-felipec](https://github.com/felipec/vim-felipec).

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please show results of running `check-theme` utility.

**Comment by felipec** [comment]
Hello, here are the results.

I noticed the tool checks for `template-tag` and `formula`, but one is barely used, and the other doesn't seem to be **ever** used.

```
Templates/HTML/XML, etc.
- Theme does not fully support.
- scope template-tag is not highlighted
  (css: .hljs-template-tag)

Markup (Markdown, etc)
- Theme does not fully support.
- scope formula is not highlighted
  (css: .hljs-formula)

nice to haves (optional, but many grammars use)
- Theme does not fully support.
- scope meta keyword is not highlighted
  (css: .hljs-meta .hljs-keyword)
- scope meta string is not highlighted
  (css: .hljs-meta .hljs-string)

high fidelity highlighting (this is optional)
- Theme does not fully support.
- scope title.class is not highlighted
  (css: .hljs-title.class_)
- scope title.class.inherited is not highlighted
  (css: .hljs-title.class_.inherited__)
- scope title.function is not highlighted
  (css: .hljs-title.function_)
- scope char.escape is not highlighted
  (css: .hljs-char.escape_)
- scope variable.language is not highlighted
  (css: .hljs-variable.language_)

Accessibility Report
┌───────┬────────────────────────────────────────┬──────────┬──────────┐
│ ratio │ selector                               │ fg       │ bg       │
│ 12.27 │ .hljs                                  │ #dddde1  │ #1e1e22  │
│ 6.64  │ .hljs::selection,.hljs ::selection     │ #1e1e22  │ #bf8fef  │
│ 4.75  │ .hljs-comment,.hljs-code,.hljs-quote   │ #888896  │ #1e1e22  │
│ 7.12  │ .hljs-number,.hljs-literal,.hljs-dele… │ #ef8f8f  │ #1e1e22  │
│ 9.9   │ .hljs-punctuation,.hljs-meta,.hljs-op… │ #efbf8f  │ #1e1e22  │
│ 13.78 │ .hljs-type                             │ #efef8f  │ #1e1e22  │
│ 12.63 │ .hljs-tag,.hljs-title,.hljs-selector-… │ #bfef8f  │ #1e1e22  │
│ 11.8  │ .hljs-string,.hljs-regexp,.hljs-addit… │ #8fef8f  │ #1e1e22  │
│ 12.08 │ .hljs-class,.hljs-property             │ #8fefbf  │ #1e1e22  │
│ 12.47 │ .hljs-name,.hljs-selector-tag          │ #8fefef  │ #1e1e22  │
│ 8.6   │ .hljs-keyword,.hljs-built_in           │ #8fbfef  │ #1e1e22  │
│ 5.81  │ .hljs-section,.hljs-bullet             │ #8f8fef  │ #1e1e22  │
│ 6.64  │ .hljs-selector-pseudo                  │ #bf8fef  │ #1e1e22  │
│ 7.79  │ .hljs-variable,.hljs-params,.hljs-att… │ #ef8fef  │ #1e1e22  │
│ 7.4   │ .hljs-symbol,.hljs-link                │ #ef8fbf  │ #1e1e22  │
└───────┴────────────────────────────────────────┴──────────┴──────────┘
```

**Comment by felipec** [comment]
Also, my theme was using `background-color` which is more proper than `background`, but the `checkTheme` crashed with that.

**Comment by joshgoebel** [comment]
I'm not sure it's more "proper". More exact, perhaps. We'd be open to a PR making the tool smarter. It shouldn't have crashed in any case.

**Comment by felipec** [comment]
@joshgoebel Well, it is more precise: `background` is a shorthand property for a bunch of other properties, which include `background-color`, the actual property we care about.

I've sent a pull request to check for that too: #3449.

**Comment by felipec** [comment]
Do I need to add `template-tag` and `formula`? Or what is missing for consideration?

**Comment by joshgoebel** [comment]
I need to find time to pull it up and at least have a  quick glance at it... holidays.  You haven't been forgotten.  Just busy.

**Comment by felipec** [comment]
All right. Here's a screenshot if it helps: [screenshot](https://pasteboard.co/BJUMAqx5mlie.png).

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
Approved, please add CHANGELOG entry?

**Comment by felipec** [comment]
@joshgoebel Done. I followed the steps of `intellij-light` and updated `tools/developer.html` too.

BTW. I think my generator might be useful to other theme creators, for example:
```yml
palette:
  red: '#ef8f8f'

blocks:
  - - number literal deletion
    - color: red
```

Gets converted to:

```css
.hljs-number,
.hljs-literal,
.hljs-deletion {
  color: #ef8f8f;
}
```

The full YAML code I used to generate my theme is this: [felipec.yml](https://github.com/felipec/vim-felipec/blob/master/other/highlight.js/felipec.yml). I use HSL instead of hex triplets, but they get automatically converted.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
Thanks.

**Pull request merged**
