### PR TITLE
Add linting for AUTHORS.txt

### PR DESCRIPTION
**Pull request by allejo**
Related to #3030

### Changes

Add a linting option to our CI

### Checklist

- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

**Comment by joshgoebel** [comment]
Wow.  This is nice, but it makes me wonder if we're going to a bunch of trouble here for no real reason... is it perhaps sufficient to have a list in authors?  Do we really need to add every single person to contributors in package.json that is published to npm?  Could it be that idea was overthought?  Do other libraries do this?  Is anyone going to be offended if we stopped?

Does the linter allow for simple things like:

```
- Josh Goebel <hello@joshgoebel.com> (maintainer)
- Ivan Sagalaev <maniac@softwaremaniacs.org> (original author)
```

**Comment by joshgoebel** [comment]
Seems to.  Can it be enhanced to actually SHOW the content of the line that is causing the validation error, not just its number?  If so I think we can merge these and see how it goes. :)

**Comment by allejo** [comment]
> Do other libraries do this? Is anyone going to be offended if we stopped?

I see a lot of other projects simply point to: [github.com/highlightjs/highlight.js/graphs/contributors](https://github.com/highlightjs/highlight.js/graphs/contributors) and an `AUTHORS.txt` would be reserved for collaborators to the project and not just one-time PR contributors.

**Comment by joshgoebel** [comment]
> I see a lot of other projects simply point to: github.com/highlightjs/highlight.js/graphs/contributors and an AUTHORS.txt would be reserved for collaborators to the project and not just one-time PR contributors.

I could easily to talked into this. :)   Thoughts?

**Comment by allejo** [comment]
I don't really think our AUTHORS file does much other than burden us with manual maintenance. I would argue that being listed in the top 100 contributors (via a native GH feature) to a project would feel better than being on a list that can be updated just for a quick PR.

**Comment by joshgoebel** [comment]
You gonna feel bad about us not needing this PR then?

**Comment by allejo** [comment]
Not one bit. It's one 1 less thing to maintain

**Pull request closed without merging**
