### PR TITLE
Add SuperCollider language

### PR DESCRIPTION
**Pull request by brianlheim**
For whatever reason adding these files caused Swift to be misdetected as Kotlin when I ran tests locally, so I tried to boost relevance for Swift by emphasizing optional-using types (!, ?). This means Swift is highlighted differently. If that's not acceptable please let me know how you'd like to resolve that.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
I think we should probably split this into two parts. The Swift changes could be their own pull request.  

For the new language, we've been moving languages out of the core rep into their own repositories (see https://github.com/highlightjs/). @brianlheim, would you be willing to maintain the SuperCollider language repo?

**Comment by brianlheim** [comment]
Without the swift changes the tests don't pass locally, that's why I didn't split this into separate PRs. We can try and see what happens on Travis if you want.

And yes, i'd be willing to maintain the SC language repo provided there are clear instructions for doing so.

**Comment by marcoscaceres** [comment]
@brianlheim, sorry, I wasn't clear. Is it possible to just send 4d08751 as a PR? Then we can deal with  SuperCollider separately.

**Comment by brianlheim** [comment]
@marcoscaceres Any update on this or #1919? Let me know if there's anything else I should do. :)

**Comment by marcoscaceres** [comment]
Apologies for the delay, trying to get back into the swing of things...

**Comment by brianlheim** [comment]
@marcoscaceres np. I've rebased this branch to pull in the merge from #1919

**Comment by marcoscaceres** [comment]
@brianlheim, sent you an invite to:
https://github.com/highlightjs/hljs-supercollider

If you copy what is done here: 
https://github.com/highlightjs/highlightjs-cshtml-razor

And just change the names of the files, "it should work" 🤞. 

See also the changes needed in the main language file to make sure the new language gets registered.

**Comment by marcoscaceres** [comment]
closing due to inactivity.

**Comment by brianlheim** [comment]
hi @marcoscaceres , thanks for updating this PR, I had forgotten about it. I have time to work on it now!

did you delete the hljs-supercollider repo? I don't see it when I click your link.

**Comment by marcoscaceres** [comment]
Hi @brianlheim, that's awesome to hear. I'll set up the repo again. I removed it as didn't want to leave it handing empty.

**Comment by marcoscaceres** [comment]
ok, all set at https://github.com/highlightjs/highlightjs-supercollider

**Comment by brianlheim** [comment]
Hey @marcoscaceres -- thanks! How does it look now? I looked around but I couldn't find instructions for how to test it. JS is not my main language so i'm probably missing something obvious.

**Comment by marcoscaceres** [comment]
Hi @brianlheim, only just getting back to this now... I've completed setting up the repo and the testing:
https://github.com/highlightjs/highlightjs-supercollider

**Comment by marcoscaceres** [comment]
I've also published the language to npm for you.

**Comment by brianlheim** [comment]
Hey @marcoscaceres -- sorry for the long delay, I'm getting back around to open source development now. is supercollider supported by highlightjs now or not? I saw https://github.com/highlightjs/highlightjs-supercollider/issues/1, does that mean it still needs to be fully integrated?

**Comment by yyyc514** [comment]
That means you can easily use it by just pulling in the external JS file and registering it as a new language.  You can see a better example on some of the other repos:

https://github.com/highlightjs/highlightjs-robots-txt

**Comment by brianlheim** [comment]
not sure I understand... the whole point of this was to get syntax highlighting on Discourse. should I ask them to include this?

**Comment by yyyc514** [comment]
More context:

https://github.com/highlightjs/highlight.js/issues/2149

We don't currently maintain any type of consolidated or "super kitchen sink" build for languages.  Many of the non-core languages are simple "drop-in" languages and easy to add via JS, so to answer your question, yes Discource would have to decide that they wished to support Supercollider and intentionally load it as a language plug-in or compile it into the main JS bundle.

**Comment by brianlheim** [comment]
thanks.. i'll contact them about it.

**Pull request closed without merging**
