### PR TITLE
Add Cobol

### PR DESCRIPTION
**Pull request by WASAB95**
hi, 
I would like to add the language cobol to highlightjs 
thanks

### CODE REVIEW

**Comment by marcoscaceres** [comment]
dup of https://github.com/highlightjs/highlight.js/pull/1752

**Comment by WASAB95** [comment]
Hi @marcoscaceres, 
Thank you for your replay I'm using Mattermost, which uses highlightjs for code highlighting. I need to add the language Cobol to this repo so that it can be imported in Mattermost. I've already seen the contribution of Nicolas but I was wondering when this will be merged with the repo so that it's also can be used in Mattermost or do you have another way how to do this?. Anyway, I'll merge my contribution with that from #1752. 
thanks

**Comment by marcoscaceres** [comment]
Ok, let’s go with this one, but are you willing to maintain the COBOL language definition? If so, we can spin up a repo for it.

**Comment by WASAB95** [comment]
yes, sure I could do this.

**Comment by yyyc514** [comment]
@WASAB95 You may be interested in:

https://github.com/highlightjs/highlight.js/issues/2328

**Comment by yyyc514** [comment]
So we have https://github.com/highlightjs/highlight-cobol now, but who owns is?  The author of this PR or the author of the previous PR?

@marcoscaceres

**Comment by yyyc514** [comment]
The sample in #1752 seems nicer, so I'd consider pulling that into your repo.

**Comment by marcoscaceres** [comment]
Whomever puts their hand up, I would guess :) Otherwise, see they can be merged somehow.

**Comment by yyyc514** [comment]
CC: @WASAB95 @FrankR85 

https://github.com/highlightjs/highlight-cobol

We have the repo ready.  I'm not sure which of you has permission to it (or both), but whenever one of you is ready to get the ball rolling if you don't have access ping @marcoscaceres or @egor-rogov and they'll take care of it for you.  Hopefully we can work together and merge the best of both PRs in the single repo.

If you have any questions or need any help, feel free to ask.

As we're not merging either of these PRs into core, I'm closing them both in my efforts to tidy up things before the new year.  Happy Holidays!

---

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Pull request closed without merging**
