### PR TITLE
log error when requiring an unavailable language

### PR DESCRIPTION
**Pull request by AlbyIanna**
Solves #1899

### CODE REVIEW

**Comment by yyyc514** [comment]
OMG, thanks for running with this but I imagined a little more general solution.  Hmmmm, though it seems that right now Arduino is the only language that depends on another (though that may not be true for 3rd party languages).  What I had imagined:

- Add `requireLanguage` API in addition to `getLanguage`.
- While getLanguage might or might not return a language
- requireLanguage always would, or would console.log that error (but generic to whichever langue was requested)...
- So we don't need to catch any errors... if the language requested isn't found, that's a hard error and should be logged.

Thoughts?

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/pull/2236/

You might want to piggy back on this.

**Comment by AlbyIanna** [comment]
@yyyc514 So what do you suggest?

**Comment by yyyc514** [comment]
Same idea, just now you can reuse the error message.

**Comment by yyyc514** [comment]
Closing this for inactivity.  I'll circle back around to this eventually myself or if you want to try your hand at implementing a generic solution (as suggested above) you can always simply open another PR (or we can reopen this one).  Thanks.

**Pull request closed without merging**
