### PR TITLE
enh(css-like) Add support for CSS Grid properties

### PR DESCRIPTION
**Pull request by monochromer**
PR adds correct highlight for [CSS Grid Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)

### CODE REVIEW

**Review by joshgoebel — APPROVED** [review]
Please update changelog also.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
@monochromer Thanks so much!  Can the related issue be closed or do you plan to follow up with additional PRs?

**Comment by monochromer** [comment]
@joshgoebel I do not know about additional PR. I just solved a problem for my project. If there is time, I will try to add properties for [this issue](https://github.com/highlightjs/highlight.js/issues/3308).

**Comment by joshgoebel** [comment]
Awesome. Thanks!

**Pull request merged**
