### PR TITLE
enh(csharp) add keywords `record` and `init` (C# 9.0)

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please show examples of how both of these are used... sometimes it's not just as simple as adding them to the keywords list.

**Comment by Youssef1313** [comment]
```
using System;
public record MyRecord
{
    public string SomeMember { get; set; }
}
```

Not sure if it requires some complex rules or not.

**Comment by joshgoebel** [comment]
Yes, it's more like a class.  See lines 148 or 159.  We'd expect that `MyRecord` was highlighted as a `title` as well, which requires a custom rule.

`init` looks like more a normal boring keyword, at least from https://csharp.christiannagel.com/2020/04/21/c-9-positional-or-nominal-creation/ this.

**Comment by joshgoebel** [comment]
So we'd need a new rule for `record`, plus a simple expects test to prove that the rule works as expected.

**Comment by Youssef1313** [comment]
I'm not familiar with making `rule`s. :(
May I keep this PR for `init` only and open an issue to track adding `record`, or you'd like to close it all together and open an issue to track both keywords?

**Comment by joshgoebel** [comment]
> May I keep this PR for init only and open an issue to track adding record

This please.  Thought you should consider giving it a try, it's not hard.  I'm happy to help.

It'd look pretty much like:

```ts
      {
        beginKeywords: 'record', end: /[{;=]/,
        illegal: /[^\s:]/,
        contains: [
          TITLE_MODE,
          // are generics allowed?
          hljs.C_LINE_COMMENT_MODE,
          hljs.C_BLOCK_COMMENT_MODE
        ]
      },
```

**Comment by joshgoebel** [comment]
Either way this would need a mention in CHANGES.md. :-)

**Comment by Youssef1313** [comment]
That doesn't seem hard.

It looks like generics are allowed based on what I'm getting in sharplab.
I've updated *csharp.js* and will add the test and update *CHANGES.md* soon.

@joshgoebel Thanks for helping!

**Comment by joshgoebel** [comment]
@Youssef1313 Thanks so much for your contribution!  Wasn't so hard, was it?

**Pull request merged**
