### PR TITLE
(build) browser build is CommonJS and IIFE (global)

### LINKED ISSUE #2291: highlightjs.org build seems to differ from `./tools/build.js -t browser :common`
**Expected behavior: The build would be identical to building locally using the build process.**

Copying from https://github.com/highlightjs/highlight.js/issues/1245

> I've asked few times before, where is the code which is responsible for creating the download and/or concatenating the fragments into a single download?

You'd think it was the build process, but it seems the results are different. Only @isagalaev knows I think. The code generated on the website is putting hljs.registerLanguage OUTSIDE the original enclosure and the code generated by the build process places it inside. @isagalaev Is the website using a special build system instead of the one in the repo for some reason? hljs as a global only works in the web environment (where anything on window is treated as a global), so that is why it's failing in node.js.

### LINKED ISSUE #2505: Require using AMD broken in 10.0.0
Loading via SystemJS in AMD used to work with v9.18.1. Broken in v10:

```
system.js:4 Uncaught (in promise) ReferenceError: hljs is not defined
    at eval (highlight.js:1566)
    at eval (highlight.js:6322)
    at eval (<anonymous>)
    at Qe (system.js:4)
    at system.js:4
    at async Promise.all (:63342/Kidoju.Widgets/src/js/widgets/index 10)
```

hljs is undefined when calling  L1566

```
hljs.registerLanguage('apache', function () {
   ...
}());
```

In System.config.js, I have:

```
packages: {
    'src/js': {
        defaultExtension: 'js',
        meta: {
           '*.js': {
                babelOptions: {
                    es2015: false,
                    stage2: false,
                    stage3: false,
                },
                format: 'amd',
            },
            '*.es6': {
                format: 'esm',
            },
            '*.jsx': {
                format: 'esm',
            },
            '*.mjs': {
                format: 'esm',
            },
         },
      },
 },
```

A workaround for now is to add an exception in meta:

```
 'vendor/highlight/highlight.js': {
      // Note: AMD broken as of v10
      format: 'global',
},
```

### PR DESCRIPTION
**Pull request by yyyc514**
- dropping support for AMD, which we never truly supported
  in the first place

  Resolves #2505. Also think this will close #2291

### CODE REVIEW

**Comment by yyyc514** [comment]
Essentially this is just IIFE (global) with a small footer to support CommonJS (since I didn't see the harm):

```
var hljs = (function () {
  'use strict';

  ...

}());
if (typeof module !== 'undefined') { module.exports = hljs; }
```


Attaching a file for testing:

[highlight.js.zip](https://github.com/highlightjs/highlight.js/files/4534086/highlight.js.zip)

**Comment by avih** [comment]
I find it a bit hard to understand from the description, does this merge mean that the concatenated web-download can now work in node.js? does it have an effect on #1245

Thanks in advance.

**Comment by yyyc514** [comment]
> does this merge mean that the concatenated web-download can now work in node.js?

@avih YES, AFAIK it SHOULD now work when used like that. **I'm still not sure that's optimal**, but it was an easy thing to enable in hindsight. There is a chance in the future we might compile the web build ES5 which would make it larger/slower than the Node.js build... but for now...

If you test it and it works, please let me know and I'll bump that thread with an update.

**Comment by avih** [comment]
Thanks a lot! I'll bump this thread once I have tested it (not right away, but I intend to)

**Comment by avih** [comment]
> @avih **YES, AFAIK it should now work when used like that.**

Indeed it seems to be working :)

I went to https://highlightjs.org/download/ , created some custom package (the default languages and few more), and it seems to be loading fine and working in node.js as is.

Thank you! (even it it won't last forever, but then again, what does last forever? ;) )

**Comment by yyyc514** [comment]
> As a side note, any chance you can add a button at the download page to select all/default checkboxes?

That'd be a task for @isagalaev ... but the page should default to the defaults by default and remember custom choices in a  cookie.

**Comment by avih** [comment]
> the page should default to the defaults by default and remember custom choices in a cookie.

Correct, but if someone wants to download everything then it's quite tedious.

**Comment by yyyc514** [comment]
Literally everything isn’t even advised. It will be huge and slow to autodetect anything.

**Comment by avih** [comment]
You could make exactly the same argument that anything beyond what you need exactly would be a waste of cpu cycles and storage space or network bandwidth, and yet your default includes 38 languages.

**Comment by yyyc514** [comment]
I would say that’s entirely correct, yet we need some defaults so as to be immediately useful to people as something you can easily load via CDN and just quickly get started easily.

I think we’re still pretty conservative with qhat we include by default with regard to how large some JS libraries are there days.  Of course if someone knows they are NEVER going to need to highlight a given language it’d be better to not use the library with that language compiled in. That’s just common sense.

Anyways, as I said any changes to the website are fully up to @isagalaev and his time.

_It’s already super easy with the main build tool to build a tiny or HUGE package, whatever one desires._

**Comment by avih** [comment]
You provide a useful thing, but you limit your users to what you think would be reasonable usage. Let users go wild, maybe someone uses it locally with enough space and cpu cycles to spare? maybe they don't do autodetection? etc.

**Comment by yyyc514** [comment]
No limits.  People can do whatever they want.  :-). The defaults work well for “most people”.

**Pull request merged**
