### PR TITLE
Updated .hljs-comment, .hljs-string color

### PR DESCRIPTION
**Pull request by Nikhar444**
Fixes the source file so that using the highlightjs, won't require to change the colors separately.

### CODE REVIEW

**Comment by yyyc514** [comment]
Context?  Why are these colors changing?

**Comment by yyyc514** [comment]
If the Atom theme recently change please provide us a link to confirm/cross-check, otherwise I'm not sure what is happening here.

**Comment by yyyc514** [comment]
Closing this without additional context.  If context is provided this can always be reopened.

**Comment by Nikhar444** [comment]
@yyyc514, check this [PR](https://github.com/w3c/respec/pull/2738). @marcoscaceres told me to make the same changes as I did in that PR.

**Comment by yyyc514** [comment]
Ok, this context is a start... but I'm still a bit confused.  Is this theme intended to be a match for the Atom One Light theme (from the Atom editor) or not?  **If so then I'd expect it to be correct when it matches that theme.**  Many of our themes make questionable choices with colors/contrast IMHO, but that's why we have so many - there is something for everyone.

So has the official Atom One theme recently made changes to their color scheme that we should follow?  Otherwise I'm not sure we should just be changing the theme because not everyone agrees with the contrast. Am I missing something here?

@marcoscaceres

**Pull request closed without merging**
