### PR TITLE
(sql) Backslash should not escape in string

### LINKED ISSUE #1748: (sql) single backslash inside a string literal seems to not be valid
I opened a ticket against VS Code for a colorization issue (https://github.com/Microsoft/vscode/issues/50059).  They closed it as upstream to this project.

It boils down to the following gets incorrect highlighting due to the backslash.

\```sql
select '\\' + foo from bar
\```

Same issue displays here on github:

```sql
select '\' + foo from bar
```
vs
```sql
select 'hello' + foo from bar
```

### PR DESCRIPTION
**Pull request by schallm**
Remove backslash_escape with in strings in standard SQL

Closes #1748.

### CODE REVIEW

**Comment by yyyc514** [comment]
Please add all 3 string types and examples of escapes to the expects test.  And we need a changeling entry also. :)

Thanks!

**Comment by egor-rogov** [comment]
Hmm, strings in backticks are out of standard altogether. Anyone knows what database uses them?

**Comment by yyyc514** [comment]
MySQL allows them for strings: https://stackoverflow.com/questions/11321491/when-to-use-single-quotes-double-quotes-and-backticks-in-mysql

**Comment by yyyc514** [comment]
@egor-rogov Thoughts?  If there is still a separate issue here might we keep this focused on the original issue and perhaps create a new issue for the backtick issue?  

I think this solves the original issue, yes?

**Comment by egor-rogov** [comment]
> @egor-rogov  Thoughts?  If there is still a separate issue here might we keep this  focused on the original issue and perhaps create a new issue for the  backtick issue? I think this solves the original issue, yes?

Absolutely.
As for backticks, looks like we cannot remove it until MySQL gets its own grammar, so let them be.

**Pull request merged**
