### PR TITLE
add languages to the :common list

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
Discussion here.  

https://github.com/highlightjs/highlight.js/issues/1119

Once we're decided I can type up a nicer changelog message.

**Comment by yyyc514** [comment]
> And what about coffeescript?

I say leave it, it's small. These files are all so small. :-)  Powershell is the only pseudo-popular annoying sized package, but even it blends in decently.

> I am worried a bit by lack of a clear criterion though. Maybe we can/should get access to some statistics from github or something like that?

Sure, whatever. :-)  Suggestion?

**Comment by yyyc514** [comment]
Screen Shot 2019-10-14 at 7 12 15 PM

**Comment by yyyc514** [comment]
We don't even have SQLPL or HCL. :-)

**Comment by egor-rogov** [comment]
> > I am worried a bit by lack of a clear criterion though. Maybe we can/should get access to some statistics from github or something like that?
> 
> Sure, whatever. :-) Suggestion?

Just a thought for the future. It requires some research and I don't feel like doing it now. I'm personally fine with the list you suggested.

**Comment by yyyc514** [comment]
Would you want to go ahead and add Powershell (because it's popular) and bump the minimal build from 70kb to 105kb or so?

**Comment by egor-rogov** [comment]
Honestly I have no definite opinion on this. It's up to you (:

**Pull request merged**
