### PR TITLE
Add Lightfair style

### PR DESCRIPTION
**Pull request by TristianK3604**

### CODE REVIEW

**Comment by gusbemacbe** [comment]
@ldct should we keep 9.12.0 or 9.13.0 in the CHANGE.md?

**Comment by gusbemacbe** [comment]
Só, you have said to keep the version in other files, @ldct.

**Comment by ldct** [comment]
@gusbemacbe this is in the changelog though, and this PR will not be included in 9.12 (since that's already released)

**Comment by ldct** [comment]
Ah I'm sorry - just looked through the old releases, the header should say `Master` instead of `Version 9.13.0`

**Comment by TristianK3604** [comment]
Done again

**Pull request merged**
