### PR TITLE
Add GDScript(Godot script) language support

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by zatherz** [comment]
Bump

**Comment by MutantOctopus** [comment]
As a user of Godot I'd like to state my support for this.

**Comment by klerpi** [comment]
Was sad to see that GDScript wasn't included in the supported languages. I hope this gets merged soon.

**Comment by marcoscaceres** [comment]
We are looking to move languages into their own repositories - however, we are lookin for people to maintain their own language definitions. See, for example:
https://github.com/highlightjs/highlightjs-cshtml-razor

Would anyone be interested in being a language maintainer?

**Comment by TheCire** [comment]
What's the status on this?

**Comment by padreputativo** [comment]
Please

https://github.com/highlightjs/highlightjs-gdscript

**Pull request closed without merging**
