### PR TITLE
endWithParent inside a starts block needs it's own mode and starts mode deep cloned (with handlebars converted)

### PR DESCRIPTION
**Pull request by nknapp**
@yyyc514 I have rebased your branch onto the master and converted the function calls in the handlebars-language into variables. Works like a charm. 

Replaces #2201

### CODE REVIEW

**Comment by yyyc514** [comment]
I'll review later when I have more focus, but looks about right!  Thanks!  And thanks for the deregister fix also... did you also want to yank the API from hilightjs code?

**Comment by yyyc514** [comment]
@egor-rogov There, now we have the change that this makes possible in the PR also, is that better for you?

**Comment by egor-rogov** [comment]
> @egor-rogov There, now we have the change that this makes possible in the PR also, is that better for you?

Almost (:
We don't need `deregisterLanguage()` anymore, do we?
I see your point on the test case and agree. The only thing `test/bugs` doesn't seem a good name to me. This is all about bugs. Maybe `test/parser`?

**Comment by yyyc514** [comment]
yes  It should be safe to remove now. That is a better name for sure

**Comment by yyyc514** [comment]
@nknapp Do you want to finish up or you want me to take this to the finish line?

**Comment by nknapp** [comment]
It would be great if you could finish this.

**Comment by yyyc514** [comment]
There has got to be some easier way for two people to collaborate on one PR.

**Comment by yyyc514** [comment]
Pushing a new PR of my own now that I'm taking this back.

**Comment by nknapp** [comment]
As a collaborator of the repo, you can push on my branch. The other way around is the difficult way

**Comment by yyyc514** [comment]
I didn’t see how.

**Comment by nknapp** [comment]
You have to add the remote URL of my fork to your local clone. Then you can pushbto the PR branch. GitHub allows this when a PR author has checked "allow maintainers to push to my branch". But it only works if you have push access to the repo that the PR was created for, so I couldn't have pushed to your branch

**Comment by nknapp** [comment]
At least I believe it works that way

**Comment by yyyc514** [comment]
So you're saying I could have pushed to your master? Interesting.  I almost considered just trying it... I will next time. :)

**Comment by nknapp** [comment]
To "nknapp:deep_clone...", yes. I think you still can. But I'm not sure

**Comment by yyyc514** [comment]
At the time it said it was from your master IIRC.  But I could be mistaken.

**Pull request closed without merging**
