### PR TITLE
fixed the spacing issue in primary key and similar combos

### LINKED ISSUE #4057: (sql) 'foreign key' and 'primary key'  do not highlight 'key'.
**Describe the issue**
When I write `foreign key` or `primary key` is sql language, `primary` or `foreign` is highlighted, however `key` is not.

**Which language seems to have the issue?**
sql.

**Are you using `highlight` or `highlightAuto`?**

`highlightAll()`.

**Sample Code to Reproduce**

```
<!DOCTYPE html>
<html lang="en">
<head>
<title>test</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/agate.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script>
hljs.highlightAll();
</script>
</head>
<body>
<pre>
<code class="sql">
create table Book (
    bookId      int,
    publisherId int,
    primary key(bookId),
    foreign key(PublisherId) references Publisher(id)
);
</code>
</pre>
</body>
</html>
```

**Expected behavior**
'key' is also highlighted.

**Additional context**
Even though I add the following to my script to force the word 'key' as keyword,

```
const custom_keywords = ['key'];
hljs.getLanguage('sql').keywords.keyword.push(...custom_keywords);
```
`key` won't be highlighted.  (However this addition will now highlights `foreign  key` or `foreign&nbsp;key`  `primary&#8288; key` etc when the separator is not a single space.)

I think the regexp using in COMBO does not recognize space as a part of keyword, that is the problem.
Supposing the intention of this code is to treat `foreign key` as one keyword.
In my script, changing the regexp so as to include space character

```
hljs.getLanguage('sql').contains[0].keywords.$pattern = /\b[\w\. ]+/;
```

solve the problem.  

However I have not understand yet why `create table` is working as intended, so I am not sure this is correct fix.

Also it does not highlights when I write `foreign  key` using 2 spaces etc, unless I added the `key` in keyword.

Though I have not understand the whole code yet, my suggestion would be the regexp at

https://github.com/highlightjs/highlight.js/blob/15d3b627fa7c99cb98d7b6760a6fbdbfd519d1a0/src/languages/sql.js#L660

should be changed to recognize space as a part of keyword. (Also it need to add `key` in reserved word list 

https://github.com/highlightjs/highlight.js/blob/15d3b627fa7c99cb98d7b6760a6fbdbfd519d1a0/src/languages/sql.js#L99

in case there are 2 or more whitespaces `between` foreign and `key`.)

### PR DESCRIPTION
**Pull request by Dxuian**
Resolves #4057

before 
image

after 
image

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Could you please test my iteration?  It passes all your tests - as well as adding support for multi-word type modifiers also (for flexible spacing).

**Comment by Dxuian** [comment]
> Could you please test my iteration? It passes all your tests - as well as adding support for multi-word type modifiers also (for flexible spacing).

i tested your code and it ran into problems as it started identifying comments as non-commented code 
but i understood your apporach and integrated it with the commits i made 
your approach with comments 
your approach:
image
highlighted comment:
image
updated approach:
image
doesnt highlight comments  apporach:
image

**Comment by Dxuian** [comment]
ive made a commit regarding the fixes pls review @joshgoebel

**Comment by joshgoebel** [comment]
Simple typo... I think you're using another grammar... here is what I have now:

Screen Shot 2024-09-23 at 10 46 52 PM

Looks right to me.

**Comment by joshgoebel** [comment]
Now I'm thinking some of these should be types (since they modify the type), not keywords... such as:

"primary key",
    "foreign key",
    "not null",

**Comment by Dxuian** [comment]
> Simple typo... I think you're using another grammar entirely... here is what I have now:
> 
> Screen Shot 2024-09-23 at 10 46 52 PM
> Looks right to me.

> Simple typo... I think you're using another grammar entirely... here is what I have now:
> 
> Screen Shot 2024-09-23 at 10 46 52 PM
> Looks right to me.

  apologies i changed to a different style and thought comment were being highlighted wrong
this seems to work fine can you merge and close this issue ?

**Comment by joshgoebel** [comment]
So all good now?

**Comment by Dxuian** [comment]
yes

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
