### PR TITLE
Add Lean language

### PR DESCRIPTION
**Pull request by PatrickMassot**
Adds support for a new language: [Lean](http://leanprover.github.io/). It would be really nice to have because gitter relies on highlight.js and the [Lean channel](https://gitter.im/leanprover_public/Lobby) is pretty active and uses a lot of  code blocks.

### CODE REVIEW

**Comment by yyyc514** [comment]
@PatrickMassot 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-lean.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by yyyc514** [comment]
**Closing for inactivity;** (also finally cleaning all these old PRs out for the new year).

As mentioned above if you're interested in becoming the maintainer of a 3rd party module, please respond [whenever you find time] and we'd be happy to help you get started.

**Comment by RaitoBezarius** [comment]
@yyyc514 Thank you for your time, please note that this makes it impossible to add Lean support on Discord, as they use an unknown version of highlightjs (which they apparently sync to upstream sometimes). :/

**Comment by yyyc514** [comment]
Indeed.  Unfortunate.  If you know anyone on the Discord technical team I'd love to at least have a conversation with them - but not sure there is anything we can do about this for now.

**Comment by RaitoBezarius** [comment]
@yyyc514 If I find someone willing, I'll send him your way :) — thank you for your time (and super fast answer) again!

**Comment by eric-wieser** [comment]
@night, I notice you committed to https://github.com/discord/highlight.js - do you have any ideas for how supporting third-party languages in discord highlighting could work?

**Comment by eric-wieser** [comment]
> Thank you so much for desiring to contribute and writing a language grammar. Unfortunately, we currently are no longer accepting new languages into the core repository.

@joshgoebel, is this policy no longer in effect? I notice that #3531 was recently merged.

**Comment by joshgoebel** [comment]
Look at the PR, it's just updating SUPPORTED_LANGUAGES.md (a docs update)...  Lean is certainly welcome in that list as well (if it's not already).  What we aren't accepting it merges of new languages into the core library.

**Comment by eric-wieser** [comment]
My apologies, I didn't look closely enough at that PR. What I should have linked to is #3448, which apperas _does_ add a new language into the core library.

**Comment by joshgoebel** [comment]
Library maintainers are always free to make exceptions to the rules - for languages we feel are vital and/or are personally willing to support (bugs, fixes, etc).  That doesn't change the policy.

I've merged both GraphQL and WebAssembly because they are hugely popular web technologies with wide, wide scope and application.  I've merged Wren and NestedText out of personal whim as maintainer.

**Comment by eric-wieser** [comment]
Thanks for the clarification; I just wanted to check those were exceptions to the "rules" rather than the rules changing.

**Pull request closed without merging**
