### PR TITLE
Add missing Swift keywords

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by ldct** [comment]
All but one of the additions look like preprocessor directives; can we use something like https://github.com/highlightjs/highlight.js/blob/master/src/languages/cpp.js#L43 instead of marking them as keywords?

**Comment by marcoscaceres** [comment]
Oops, I missed 
https://github.com/highlightjs/highlight.js/pull/1719#issuecomment-408458134

Seems like a better solution.

**Comment by hartbit** [comment]
@marcoscaceres I've been very busy lately but still plan to fix those issues.

**Comment by marcoscaceres** [comment]
Thanks for the update, @hartbit!

**Comment by marcoscaceres** [comment]
Closing due to inactivity. Happy to reopen if updated tho.

**Pull request closed without merging**
