### PR TITLE
Add grammar Feature/language sparql ttl

### PR DESCRIPTION
**Pull request by VladimirAlexiev**

### CODE REVIEW

**Comment by VladimirAlexiev** [comment]
This PR #1746 adds better support for SPARQL and Turtle (#1553), namely fixes problems in #1736

**Comment by VladimirAlexiev** [comment]
I fixed two conflicts (relevance problems) with xml and objectivec, but I am stuck at this one:

@isagalaev can you help diagnose https://travis-ci.org/isagalaev/highlight.js/jobs/376860564#L917?
It says elixir is detected instead of ttl. But when I try test/detect/ttl/default.txt in tools/developer.html, I get score 46 for elixir (and ruby) and 98 for ttl: so how come elixir is detected?

Thanks in advance!

**Comment by gusbemacbe** [comment]
@VladimirAlexiev, see https://github.com/isagalaev/highlight.js/issues/1678#issue-289222064.

**Comment by gusbemacbe** [comment]
No, because he doesn't intend anymore to merge. You can see here that most of pull requests were not merged and hundred issues were not solved. This repository is abandoned.

**Comment by gusbemacbe** [comment]
@VladimirAlexiev, this repository became an organisation and has new maintainers. Please back up the files and rebase the latest version.

**Comment by VladimirAlexiev** [comment]
@gusbemacbe Sorry, I'm not very fluent with git, so how do I do that?
Is it enough if I just merge the 3 conflicting files reported above?

**Comment by yyyc514** [comment]
Closing, seems to be superseded by #1844

**Pull request closed without merging**
