### PR TITLE
Add new language Structured Text (ST) according to IEC 61131-3

### PR DESCRIPTION
**Pull request by Serhioromano**
This language is part of IEC 61131-3 standard to program PLC. I am writing a book in gitbook and I need highlight compatibility.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@Serhioromano we are in the process of moving languages into their own repositories. Would you be able to maintain the language definition?

**Comment by marcoscaceres** [comment]
Here is an example: https://github.com/highlightjs/highlightjs-solidity

**Comment by Serhioromano** [comment]
@marcoscaceres this is a very good idea to have a repo for every language. And of course, I'll be able and willing to support this language definitions. I support the most popular [VS Code extension for this language support](https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-st) and I'll be happily supporting this one. 

Although it raises a question of how one will pass tests and how to develop a definition in a separate repository. Right now I can launch the test environment and watch as I develop.

**Comment by marcoscaceres** [comment]
Still trying to figure out the best testing set up... however, the way the terraform repo does it seems ok:
https://github.com/highlightjs/highlightjs-terraform

It uses jasmine and just compares the output to a static file.

**Comment by Serhioromano** [comment]
So what is the next step I should take?

**Comment by marcoscaceres** [comment]
@Serhioromano, I'd suggest just copying the repository structure from highlightjs-terraform and replacing the "Terraform" parts with this language.

**Comment by Serhioromano** [comment]
@marcoscaceres but how do I PR it here? It is completely different structure the new language and you root hl repository. You will have to bind it as a submodule?

**Comment by Serhioromano** [comment]
As I understand you will copy my repository as separate repo, so there is no sense in PR. I've created new repo without forking highlightjs 

https://github.com/Serhioromano/highlightjs-structured-text

You can use it to create your own repository and then set me as admin for that repository so I can bring changes fast without PRs.

**Comment by marcoscaceres** [comment]
@Serhioromano, thanks for getting everything set up! So we don't lose history, can you transfer the repository over to this org (better than copying)?: 

1. add me (@marcoscaceres) as a Contributor via the Repo's Settings. 
2. Go to "Options" -> scroll down to "Danger Zone" -> "Transfer ownership", and transfer ownership to the "highlightjs" organization. 

Once that's done, I'll add you back as admin.

**Comment by Serhioromano** [comment]
I did it but I've got an error

You don’t have the permission to create repositories on highlightjs

Not sure it worked.

**Comment by marcoscaceres** [comment]
Oops! Sorry about that. I thought I’d granted you permission to create repos. It should work now.

**Comment by Serhioromano** [comment]
@marcoscaceres Same error

> You don’t have the permission to create repositories on highlightjs

Did you grant me permission for highlightjs organization or for your personal page?

**Comment by marcoscaceres** [comment]
argh, sorry @Serhioromano! I'm terribly embarrassed. I don't know what I did previously. You should have now gotten an org invite, which _should_ 🤞🙏 let you create the repo. Sorry again about this...

**Comment by Serhioromano** [comment]
Repo is created. 

https://github.com/highlightjs/highlightjs-structured-text

Suggestion, for better organisation, let's unify descriptions of repos. For example, all descriptions start with something like this

- highlight.js syntax definition for ***
- highlight.js language support for ***

But all repos have to have the same description.

**Comment by marcoscaceres** [comment]
Agree... need to also update the docs to make sure people can easily find these external languages. Just. Need. To. Find. Time.

**Comment by Serhioromano** [comment]
May we close this already?

**Comment by marcoscaceres** [comment]
Yes, I think we are good to continue in the other repo. Thanks again for your help getting that to happen!

**Comment by egor-rogov** [comment]
> Agree... need to also update the docs to make sure people can easily find these external languages. Just. Need. To. Find. Time.

Btw @marcoscaceres, what do you think about moving the languages list into a separate page in the docs? "CSS classes reference" doesn't seem a right place for it imo.

**Comment by marcoscaceres** [comment]
Yeah, would be good to actually move the languages to the README. It's fairly core information for anyone wanting to use the library.

**Comment by Serhioromano** [comment]
@marcoscaceres it is an off topic but I see now why you move languages to separate repos. I went to issues of main repo, I thought may be I can help someone but it is overwhelmed with language specific questions. That would be great to move all those questions to different languages. 👍

**Comment by marcoscaceres** [comment]
Yeah, the  other option I was thinking is finding who the original authors of each language were and asking if they can help. Even if we get a 10-20% response rate, that's still pretty good.

**Comment by Serhioromano** [comment]
Authors will eventually be discovered. I am sure in few month more than half of repos will have it's own admin who will answer questions. At least active languages like php, js, css, ...

**Pull request closed without merging**
