### PR TITLE
Adding Hakaru language

### PR DESCRIPTION
**Pull request by zaxtax**
This commit adds the Hakaru language (https://github.com/hakaru-dev/hakaru)

### CODE REVIEW

**Comment by yyyc514** [comment]
@zaxtax 

**First of all, truly sorry for the long delay in anyone responding to this PR.**

Thank you so much for desiring to contribute and writing a language grammar.  Unfortunately, we currently are no longer accepting new languages into the core repository.  The existing maintainers simply don't have time to maintain new languages (fixing bugs, dealing with issues, etc).  **We'd still love to host your language as a 3rd party module though** - if you're willing to help maintain it.  

It's easy to turn your language into a module that anyone who likes can easily integrate with Highlight.js using a single line of code:

```html
<script src="/path/to/highlight.min.js"></script>
<!-- they'd simply add your language modules -->
<script src="/path/to/highlightjs-Hakaru.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
```

It's also possible for users to rebuild the `highlight.js` library to include specific 3rd party modules, all in a single file (vs loading a bunch of 3rd party languages one at a time).

If you'd like to become the maintainer for this language then we're happy to create a new repository in the `highlightjs` organization and host the repository there.  That assumes you'd be open to reviewing issues and fixing bugs as they arise.  You're also welcome to host the repo yourself and we'll link to it from our README.

There isn't much in the way of how to docs on this yet, but there are sample repositories and it's honestly pretty easy.  We're still fleshing out an [official "spec" for 3rd party modules](https://github.com/highlightjs/highlight.js/issues/2328), but even after that's done it should require minimal changes from the examples we have already.  IE, if you wanted to get started now there isn't any big reason to wait.

My own `robots.txt` grammar repository is a great, simple example:

https://github.com/highlightjs/highlightjs-robots-txt

If you have any questions feel free to ask.

**Comment by zaxtax** [comment]
Yea, I'm happy to have the language in a contrib repo and do maintenance. Let me look at your example, and I suspect it shouldn't be too bad to get everything setup just right.

**Comment by yyyc514** [comment]
Would you like me to go ahead and setup a repo for you then?

**Comment by zaxtax** [comment]
Yea sure!

**Comment by yyyc514** [comment]
@zaxtax https://github.com/highlightjs/highlightjs-hakaru

Invite sent. :-)  Let us know if you have any further questions.  Closing this PR.

**Comment by zaxtax** [comment]
Thanks!

**Pull request closed without merging**
