### PR TITLE
(scheme) Add 'racket' alias

### PR DESCRIPTION
**Pull request by elihunter173**
### Changes

Add `racket` alias to the scheme language since scheme highlighting is also used for racket. https://github.com/highlightjs/highlight.js/issues/2890

### Checklist
- [x] Added markup tests, or they don't apply here because... Single alias added
- [ ] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

### CODE REVIEW

**Comment by joshgoebel** [comment]
I'm not actually sure this would be good.  From their site:

> Racket is ... a dialect of Lisp and a descendant of Scheme

_But aren't their many descendants of Scheme and dialects of Lisp?_  I'm not sure we want to start adding aliases every time a new variant of scheme pops up (even if our highlighting is compatible).  In a way I see this as scope creep because now it  forces us in a way to *continue* to be Racket compatible, even if that might be an onerous burden in the future. And even if we aren't truly compatible now - but just aren't aware of it yet.

I'd perhaps rather continue to say "we don't support Racket officially, but Scheme works pretty well".  If one is using a scheme-like language it's easy enough to just specify the language as `scheme` OR if that's not enough to add this alias manually with a single line of JS using `registerAlias`.

I'm not sure we want to start codifying this into the core library.

@allejo Thoughts?

**Comment by joshgoebel** [comment]
@elihunter173 Are you aware of us doing something similar with any of our other aliases (perhaps we do)?  If so then perhaps it's time we reviewed the entire policy around this (with v11 around the corner) vs dealing with this as a one-off.

**Comment by joshgoebel** [comment]
Trying to make this less nebulous: As a general rule _I feel an aliases should NOT expand the assumed scope of a grammar._  Aliases should literally be an alias or an equivalency, ie:

- JS is an alias of JavaScript.
- But TypeScript (assume we had no built-in support) is NOT an alias for JavaScript, it's a very different superset.
- Atom is an alias of XML.  Atom is literally XML code.
- Delphi is Object Pascal code, making Pascal a valid alias.
- FreePascal and Lazarus are not aliases of Delphi.  They are not Delphi code, they are other Pascal implementations.
- Zsh is not a bash alias.  Zsh is shell code, but NOT bash code.
- Racket is not a Scheme alias.  Racket is a descendant of Scheme with it's own unique differences.

This reasoning feels pretty consistent to me.

---

- `scheme` may work well, for racket, but that doesn't imply it should be an alias.
- `js` may work well for TypeScript (in a pinch),but that doesn't imply it should be an alias.
- `delphi` may work well for FreePascal, but that doesn't imply it should be an alias.

**Comment by elihunter173** [comment]
That seems totally reasonable to me, after all I won't be the one maintaining this. Feel free to close the PR.

My path to this PR was I wanted to add racket support to my discord bot. Since discord uses highlight.js for syntax highlighting, I match my language codes with the classes of highlight.js. I saw racket wasn't a class but the scheme class was used/modified to support racket and I knew zsh was an alias of bash, so I thought that was the pattern this package followed. I don't have much stake in this PR to be honest, just thought this would be a nice quality of life improvement.

**Comment by joshgoebel** [comment]
> Since discord uses highlight.js for syntax highlighting, I match my language codes with the classes of highlight.js. 

I'd suggest building this mapping into your bot so it knows if it's pasting racket to use scheme.  Probably only a few lines of code (if that).

> I knew zsh was an alias of bash, so I thought that was the pattern this package followed

Indeed, a reasonable deduction.  I'll leave this open a bit longer and it'll likely result in a new issue to fix some of those more ambiguous aliases when we release version 11.

**Pull request closed without merging**
