### PR TITLE
(docs) Added 3rd party MKB Support

### PR DESCRIPTION
**Pull request by Dereavy**
MKB short for the Macro-Keybind mod is a BASIC like scripting language used to automate actions within the minecraft game.
The language was created by Mumfrey in 2011 and has since then grown into a language that is used by a large community of users for its ease of use and basic functionality.

### Changes

  Added 3rd party MKB grammar to SUPPORTED_LANGUAGES 
### Checklist
- [Y] Added markup tests.
- [Y] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by Dereavy** [comment]
Added browser tests

**Review by Dereavy — COMMENTED** [review]
Followed submission guidelines to add support for the MKB language.

**Comment by joshgoebel** [comment]
Awesome.  Thanks for much for this, but please see our documentation on how to submit a 3rd party grammar:

https://highlightjs.readthedocs.io/en/latest/language-contribution.html

It should be in it's own repo, not part of our source tree, etc... we do not merge languages into the core library (for many reasons) but we're happy to have as many 3rd party grammars as people want to spend time maintaining them.

See https://github.com/highlightjs/highlightjs-robots-txt for what a stand-alone published repo might look like.

**Comment by Dereavy** [comment]
Moved files to their own module: https://github.com/Dereavy/highlightjs-mkb

**Comment by Dereavy** [comment]
Added 3rd party grammar to SUPPORTED_LANGUAGES.md

**Comment by joshgoebel** [comment]
Looks good! Please revert your changes to the package lock file though.

**Comment by Dereavy** [comment]
Reverted changes to the package lock file.

**Comment by joshgoebel** [comment]
Done!

**Pull request merged**
