### PR TITLE
[Waiting for org repo] Add lang to changes.md

### LINKED ISSUE #3690: (request org repo) highlightjs-lang
I would like to request the creation of a `highlightjs-lang` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: `lang`
- Link to repo: https://github.com/AdamRaichu/highlightjs-lang

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

### PR DESCRIPTION
**Pull request by AdamRaichu**
> **Note**: This is pending the approval of an org repo.

Fixes #3690 

### Changes

Adds lang to supported language and updates changes.md. 

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Thanks, once you push to the repo I can merge this.

**Comment by AdamRaichu** [comment]
image

**Comment by joshgoebel** [comment]
You forgot LICENSE.

**Comment by AdamRaichu** [comment]
Ah. Does it matter which license I use? I usually use MIT.

**Comment by joshgoebel** [comment]
> Ah. Does it matter which license I use? I usually use MIT.

Not really.  MIT is a great choice.

**Comment by AdamRaichu** [comment]
Done.

**Comment by AdamRaichu** [comment]
When can I expect `lang` to be listed on the website?

**Comment by joshgoebel** [comment]
When the next release happens the website will auto-update.  Not sure on release timing ATM.

**Pull request merged**
