### PR TITLE
Add C# as an alias.

### LINKED ISSUE #1880: C# not working as an alias for CS programing language
For more context: https://github.com/Microsoft/vscode/issues/61240

### PR DESCRIPTION
**Pull request by atitoa93**
Fixes #1880

### CODE REVIEW

**Comment by atitoa93** [comment]
@marcoscaceres Added one unit test making sure that `c#` is an alias along with `csharp`. Happy to add more tests if required.

**Comment by marcoscaceres** [comment]
@atitoa93 sorry for the delay, I'm at a conference all this week.

**Comment by marcoscaceres** [comment]
@atitoa93 sorry, one last thing to ask from you. Could you add this "improvement" to the CHANGES.md file please? Otherwise, I'll add it when I'm back.

**Comment by atitoa93** [comment]
No worries. Have a good time 😄.

**Pull request merged**
