### PR TITLE
Added Fortran block statement.

### PR DESCRIPTION
**Pull request by interkosmos**
Added `block` keyword, as described in issue #2342.

### CODE REVIEW

**Comment by yyyc514** [comment]
Please add to CHANGELOG.

If the `endblock` form without a space also allowed?  I see a lot of other keywords done like that.

**Comment by interkosmos** [comment]
> Is the `endblock` form without a space also allowed? I see a lot of other keywords done like that.
Yes, `endblock` is accepted, even if `end block` should be preferred.

**Comment by yyyc514** [comment]
You'll need to add `endblock` as a keyword also then.

**Comment by interkosmos** [comment]
Can I somehow change the current PR?

**Comment by yyyc514** [comment]
Just add a second commit.

**Comment by yyyc514** [comment]
Yep. Nice.  Now just a `CHANGES` entry please.

**Comment by yyyc514** [comment]
@interkosmos Thanks so much for this contribution!

**Pull request merged**
