### PR TITLE
Add Flix to SUPPORTED_LANGUAGES.md

### PR DESCRIPTION
**Pull request by jaschdoc**
### Changes
This PR adds the Flix language to the list of supported languages.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please include a common JS CDN build in the dist folder of your repo so users who know and care nothing about build systems can just drop a single file into their website that "just works". 

If you follow the recommended build process we generate this file automatically.

**Comment by jaschdoc** [comment]
Should this file also include the common languages (built by `node tools/build.js -t cdn :common`)?

**Comment by jaschdoc** [comment]
Ready for review. Thank you for your patience :)

**Comment by joshgoebel** [comment]
How would you feel about renaming the repo to `highlightjs-flix` for parity with all the others?

**Comment by jaschdoc** [comment]
> How would you feel about renaming the repo to `highlightjs-flix` for parity with all the others?

We've now renamed the repo to `highlightjs-flix`.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
Thanks!

**Pull request merged**
