### PR TITLE
(docs) clarify use of continuation

### LINKED ISSUE #2259: Incremental line-by-line highlighting breaks some languages
highlight.js supports highlighting text incrementally via the `continuation` parameter to the `highlight` function. Gerrit uses this to highlight line-by-line. However, this causes some features, notably C++ raw string matching, to break. See the discussion [here](https://bugs.chromium.org/p/gerrit/issues/detail?id=7748#c27).

(Ironically, raw string matching partially worked in #1825 and then I broke it again for us when I tried to make it more featureful in #1897.)

I changed the tests to feed all the markup samples line-by-line to demonstrate the issue. Things mostly work, but when a begin or end element crosses a line boundary, things break.
https://github.com/highlightjs/highlight.js/compare/master...davidben:line-by-line-tests

This suggests that the strategy in #1897 was wrong and probably C++ raw strings should have separate `begin` and `end` units. But `endSameAsBegin` doesn't seem quite flexible enough, unless there's some trick I'm missing. One thought is `begin` matches `R"<blah>(` and then we have a `endFromBegin` attribute which takes a callback and will compute `)<blah>"` for the `end` pattern given a `begin`.

But it's not entirely clear what the general API contract here is. Supposing incremental highlight is a thing highlight.js wants to support (I assume yes, given the `continuation` parameter), it seems there's basically no hope in allowing a `begin` or `end` unit to span an input boundary. The API needs to return something for the text that was passed in, so you can't lookahead across chunks. That means highlight.js needs to have opinions about what input boundaries need to be supported by languages (One call per character obviously cannot do anything useful. Line-by-line seems reasonable?), or we change the incremental highlight API altogether.

Thoughts?

### PR DESCRIPTION
**Pull request by yyyc514**
Closes #2259.

### CODE REVIEW

**Comment by yyyc514** [comment]
If it’d been markdown I probably would have. Don’t know how to do that in rst. Lol. 

I’ll look it up next time.

**Comment by egor-rogov** [comment]
> If it’d been markdown I probably would have. Don’t know how to do that in rst. Lol.
 
AFAIK `*italics*` and `**bold**`.

**Comment by yyyc514** [comment]
Know a good editor/previewer for rst files on Mac?

**Comment by egor-rogov** [comment]
Nope.

**Pull request merged**
