### PR TITLE
New Languages: SPARQL and Turtle

### PR DESCRIPTION
**Pull request by ellismarkf**
[Turtle](https://www.w3.org/TR/turtle/#sec-diff-sparql) is a terse RDF Triple langauge, used in the data graph space.
[SPARQL](https://www.w3.org/TR/sparql11-query/) is a data graph query language, and an extension of Turtle syntax.

This PR includes modes for both.

### CODE REVIEW

**Comment by ellismarkf** [comment]
Fixing relevance issues currently breaking the build.

**Comment by VladimirAlexiev** [comment]
@ellismarkf Thanks! We also need highlighting for semantic languages. 
1. Is this similar to https://github.com/clarkparsia/highlight-node?
2. Would it be possible if you also add Manchester notation (see the above repo)?

@isagalaev Do you have an ETA for accepting this PR? It was submitted 10 months ago.

cc @nikolatulechki

**Comment by azaroth42** [comment]
Any chance that this can be updated and reviewed?

**Comment by marcoscaceres** [comment]
@ellismarkf, @VladimirAlexiev, @azaroth42 we are moving languages out to their own repositories, so they can be loaded externally. Then basically all you need is something like this: 

https://github.com/highlightjs/highlightjs-solidity

Would some of you be willing to maintain the language? If yes, I can spin up a repository for you.

**Comment by VladimirAlexiev** [comment]
@cygri is also asking for it.

@marcoscaceres I'm willing to maintain it so please make a repo. Do we need separate repos for the 3 langs I've included: `turtle`, `sparql` and `pie` (the GraphDB rules lang)?

Currently CI test fails because of some silly auto detection conflict with something called `arcade`. I need help figuring out how to fix it; but actually I think auto detection of a gazillion langs is a bad idea and nobody needs it.
https://github.com/highlightjs/highlight.js/pull/1844

**Comment by marcoscaceres** [comment]
> @marcoscaceres I'm willing to maintain it so please make a repo. Do we need separate repos for the 3 langs I've included: turtle, sparql and pie (the GraphDB rules lang)?

Up to you how you want to manage it. It could be that they are all closely related enough to warrant a single repo. Generally, we have been doing one repo per language. 

I'll set up a repo now,  as "highlighjs-turtle" - but please rename it to whatever you'd like. And if you think 3 repos is best, also happy to set that up!

**Comment by marcoscaceres** [comment]
Done: https://github.com/highlightjs/highlightjs-turtle ... please feel free to invite folks above if they'd be willing to help!

**Comment by cygri** [comment]
Great to see this moving forward! Thanks @marcoscaceres and @VladimirAlexiev.

To me, Turtle and SPARQL in the same repo makes sense as they share a lot of syntax, are often used together, and are both W3C standards. Pie also shares a lot of syntax, but is a single-vendor language and has a different audience, and a different set of people who would be interested in contributing.

Either way, I can help with setting up the repo, testing and documentation, but we'll probably still need someone else to do the actual coding.

**Comment by marcoscaceres** [comment]
@cygri, helping with basic usage documentation would really help. Take a look at   https://github.com/highlightjs/highlightjs-solidity and you can basically just adapt that. 

Good suggestion about Pie. I'll wait for @VladimirAlexiev for instructions on what he suggests we do - but can definitely just spin up another repository.

**Comment by VladimirAlexiev** [comment]
@marcoscaceres I don't have write access there, can't edit the description, and can't add people. Could you please give me the appropriate rights?
- Agree with cygri, please make another repo `highlightjs-pie`.
- While you're at it, also make a repo `hjighlightjs-shexc` and give @ericprud write rights: he did https://github.com/highlightjs/highlight.js/pull/2001

**Comment by marcoscaceres** [comment]
On it!

**Comment by marcoscaceres** [comment]
@VladimirAlexiev please navigate to 
https://github.com/highlightjs/highlightjs-turtle/invitations

Once you accept, you should have admin.

**Comment by marcoscaceres** [comment]
Done. Invites should be in your inbox.

**Comment by yyyc514** [comment]
Ok, I didn't see this before commenting on #1844.  Glad to see we've already made some progress here!

I see we have https://github.com/highlightjs/highlightjs-turtle and https://github.com/highlightjs/highlightjs-pie now so I'm going to close both PRs as completed (since we aren't merging them and I'm trying to finally clean out all the old language PRs for the new year).   _Of course they both look pretty empty still_, **so if you all have any questions, please let us know!**

> To me, Turtle and SPARQL in the same repo makes sense as they share a lot of syntax, are often used together, and are both W3C standards. 

I dunno if "used together" or "shares syntax" are great reasons to group them in a single repo, but if you use both and are going to help maintain them long-term and that's easier for you, then I can't grumble too much. :-)  

It's also a great opportunity to figure out how to have multiple languages in a single repo.  I've been working on that: https://github.com/highlightjs/highlight.js/issues/2328

I'd suggest you go with the very familiar highlight.js layout as it's familiar and my work on the new build system already supports it:

```
/src/languages/turtle.js
/src/languages/sparql.js
/test/detect/turtle/...
/test/detect/sparql/...
```

**Pull request closed without merging**
