### PR TITLE
Adds Google Closure Templates (soy) support

### PR DESCRIPTION
**Pull request by jbalsas**
This PR adds support for Google [Closure Templates (soy)](https://developers.google.com/closure/templates/)

/cc @zenorocha

### CODE REVIEW

**Comment by zenorocha** [comment]
That's awesome! Can we get this merged @isagalaev?

**Comment by paladox** [comment]
+1, needs rebase.

**Comment by jbalsas** [comment]
Rebased and push-forced, @paladox!

**Comment by jbalsas** [comment]
Hey @isagalaev, is there anything else we'd need to do to see this merged in? We want to switch to `highlight.js` in [Electric](http://electricjs.com/) and this is currently the only thing preventing us to do so.

**Comment by isagalaev** [comment]
In fact, I'm going to throw the towel officially soon on maintaining the project (gotta still find time to write an informational post about it). At this moment your best bet would be to simply build your fork yourself. It's actually quite simple: http://highlightjs.readthedocs.io/en/latest/building-testing.html

**Comment by jbalsas** [comment]
Hey @isagalaev, that's really sad to hear, but of course, totally understandable. Are you planning to open this up to see if someone else could pick it up and become a maintainer?

**Comment by isagalaev** [comment]
Well, it's already opened up, technically :-) Anyone can fork and develop any project on GitHub, and highlight.js' BSD license is probably the most permissive of all for that.

However I actually want to do it properly, with transferring the rights for the name, switching the links to the organizational account, giving the control of the Web site… And that requires some coordination. And time :-)

**Comment by jbalsas** [comment]
Hahaha... yeah, I know :) 

Forking, however, comes with additional burdens as well in the form of maintenance and synchronization, so I'd rather push to an upstream maintained original than fork it.

I didn't intend to rush or push in any way for you to reach a conclusion, so sorry if it came across that way. I'll keep an eye on future developments on this.

Good luck with it and thanks for all the hard work you've already devoted to this!

**Comment by isagalaev** [comment]
Thanks for the kind words :-)

**Comment by zenorocha** [comment]
Friendly ping. Any news about when we can get this merged?

**Comment by paladox** [comment]
This repo I doint think is maintained any more.

**Comment by paladox** [comment]
@isagalaev hi, any news on who your going to give the repo to please?

highlight.js is really the only repo that returns a string of highlighted code without the need to supply an element. :).

**Comment by paladox** [comment]
Needs rebasing to fix merge conflict.

**Comment by paladox** [comment]
this needs rebasing.

(the project has new maintainers)

**Comment by paladox** [comment]
@marcoscaceres Hi, wondering if you could review this please?

We would like to use this at https://gerrit-review.googlesource.com/ .

**Comment by jbalsas** [comment]
Hey @paladox, I've rebased this so it's ready to get picked up. This is no longer a priority for us, so I might be slow to respond if changes are needed. Feel free to use this as a starting point and make any modifications you might need in the future.

Thanks!

**Comment by paladox** [comment]
@egor-rogov hi, could you review/merge this change please? :)

**Comment by egor-rogov** [comment]
Hi @paladox, I'm not sure if we still accept new languages in core. @marcoscaceres started to detach new languages to separate repos, although AFAIK this process is still in beta. What do you think, Marcos?

**Comment by marcoscaceres** [comment]
Yeah, I still think we should be moving to externalize new languages (even though we are still working out the details). Example:
https://github.com/highlightjs/highlightjs-cshtml-razor

**Comment by egor-rogov** [comment]
So, the question is: are you guys ready to maintain a separate repo for this language?

BTW, I had a glance into the PR and it looks fine to me. I didn't test it though.

**Comment by jbalsas** [comment]
Hey @egor-rogov, I'm not really interested in maintaining a separate repo, but maybe @paladox is. I'm fine if anyone wants to scrap this PR and repurpose it.

Should I close this, then?

**Comment by isagalaev** [comment]
To clarify, the original motivation for not bundling languages with highlight.js was exactly that they should me maintained by their contributors, not the core team. So simply moving them in a separate repo within the org doesn't do anything.

**Comment by jbalsas** [comment]
Hey @isagalaev, I assumed that was the end goal and that even if the repos would live in the `highlight` organization, contributors would be expected to maintain them. That's the reason why I declined, because I don't think I'd be able to dedicate proper level of attention to this.

@paladox, are you interested in picking this up? Otherwise, I'll simply close this in a couple of days.

Thanks!

**Comment by paladox** [comment]
@jbalsas Sorry for late reply. I doin't mind picking this up.

But i doin't see many repos being created for seperate languages yet?

**Comment by marcoscaceres** [comment]
@paladox, it's a slow process that we are just starting up. Hopefully better than our pull request back-queue that goes back years 😿

**Comment by paladox** [comment]
@marcoscaceres can we still accept new languages and then when the process is sorted out move the langs into there seperate repo?

(including a bin program to pull the langs so it would still be easy to build them?)

**Comment by marcoscaceres** [comment]
Well, I'm trying to force the the process to get sorted out by forcing things new languages out. The only way this happens is to actually move things out and to deal with the fallout.

**Comment by paladox** [comment]
@yyyc514 or @Marcocanc hi, would you be able to create a repo for this please? :)

**Comment by yyyc514** [comment]
@paladox I think only @egor-rogov can do that now.  Marco has gotten caught up in other things so isn't around so much.

**Comment by paladox** [comment]
Ah, ok, thanks!

**Comment by egor-rogov** [comment]
@paladox I've set up a repo for this language: https://github.com/highlightjs/highlightjs-closure-templates

**Comment by paladox** [comment]
Thanks!

**Comment by yyyc514** [comment]
Closing this as complete since we have a new repository all setup. :-)

**Pull request closed without merging**
