### PR TITLE
Add supercollider language

### PR DESCRIPTION
**Pull request by ledhed2222**

### CODE REVIEW

**Comment by ledhed2222** [comment]
Any word on this guys?

**Comment by isagalaev** [comment]
First of all, thank you for the contribution! Ours is the usual place of many open source project: a long queue of things to look at and not enough people-time to do it. Hopefully, we'll get to everything eventually!

**Comment by ledhed2222** [comment]
All good. Any way I can help do reviews? Would like to help now that I
understand the project a bit.

**Comment by marcoscaceres** [comment]
Duplicate of:
https://github.com/highlightjs/highlight.js/pull/1913

Which is being moved to: 
https://github.com/highlightjs/hljs-supercollider 

@ledhed2222, if you'd like to help maintain that repo, let me know!

**Comment by marcoscaceres** [comment]
> Looks like the repo is empty.

Yep, just waiting on @brianlheim to find a bit of time to move things over.  

> What is the rationale for splitting it out? 

We have a very small community of volunteer maintainers for hljs core :( Given that we are doing everything in our spare time, it's not feasible for us to maintain the actual languages, so we are asking folks who know and use those languages to help maintain them. 

> And what would you need help with to start?

I would imagine @brianlheim would probably need some help with reviews. Maybe start by seeing what he made in #1913 and how it aligns with your PR... If stuff from this PR improves things from his PR, then consider merging. I'll add you to other repo, so you both can work together. 

Eventually, it would be great if you guys could `npm publish` the syntax definition.

**Pull request closed without merging**
