### PR TITLE
New language: Robot Framework

### PR DESCRIPTION
**Pull request by Harri**
This PR adds support for Robot Framework (http://robotframework.org/). While RF supports multiple different formats, this PR only handles white space separated format; http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#space-separated-format.

### CODE REVIEW

**Comment by chubinou** [comment]
great, works for me.

**Comment by GLMeece** [comment]
Why has this not been merged into Master yet? The P.R. was made March 8, 2017.  That was almost 7 months ago. Bump? :anguished:

**Comment by gusbemacbe** [comment]
@GLMeece, I also wanted to know. It is why I emailed one of major contributors and asked what happened with Ivan. There are many unsolved issues and unmerged pull requests here.

**Comment by Harri** [comment]
Any chance on getting this approved?

**Comment by gusbemacbe** [comment]
@Harri, @SirCmpwn and @ldct must approve this weekend.

**Comment by Harri** [comment]
Is there something I can do to help get this merged?

**Comment by gusbemacbe** [comment]
Hi @Harri !

* Back up of your file
* Remove your repository that you have forked.
* Fork again the most recent repository
* Drag your file and drop on your newly forked repository
* In your repository, create your pull request, select this repository "to" and "master" and select your repository to "from" and "master". Apply
* Ready

**Comment by Harri** [comment]
New PR is here: https://github.com/highlightjs/highlight.js/pull/1928

I'll close this. Thank you.

**Comment by gusbemacbe** [comment]
You are welcome.

**Pull request closed without merging**
