### PR TITLE
Fixes issue #3536

### PR DESCRIPTION
**Pull request by shikhar13012001**
(JSON) null/booleans are keywords but should be literals

[issue#3536](https://github.com/highlightjs/highlight.js/issues/3536)

### Changes

Removed literals object 
### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
You said they should be literals, why did you removed them?

**Comment by shikhar13012001** [comment]
@joshgoebel  I think I have done some mistake please let do a fix in this. Also I am having trouble as to what to do in particular? can you please help me a bit?

**Comment by joshgoebel** [comment]
You need to change/add the `scope` to the existing `LITERAL` mode, not remove the mode entirely - and after that you'll need to update the test suite as well.  You may need to read the docs: https://highlightjs.readthedocs.io/en/latest/index.html  Perhaps read some of the other grammars (some are quite simple) to get an idea how they work.

I really can't really help further.  It would take longer to provide step-by-step instructions than to just fix it myself.    Good luck! 👍🏼

**Comment by joshgoebel** [comment]
Please push what you have so I can review it with Github's tooling.

**Comment by shikhar13012001** [comment]
> Please push what you have so I can review it with Github's tooling.

I have pushed the code

**Comment by joshgoebel** [comment]
The comment above explains why this cannot be changed to use `keywords`.  I have fixed.

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
Can you please add changelog entry and I'll still give you credit for the fix since you put in the time...

**Comment by shikhar13012001** [comment]
> Can you please add changelog entry and I'll still give you credit for the fix since you put in the time...

Yes sure, thanks ! 🎉

**Pull request merged**
