### PR TITLE
Add Nord Style

### PR DESCRIPTION
**Pull request by arcticicestudio**
Added [Nord][nord-highlightjs] style.

The package is also [available on npm][npm] to simplify the usage in Node based projects.

![][hero]

[nord-highlightjs]: https://github.com/arcticicestudio/nord-highlightjs
[hero]: https://raw.githubusercontent.com/arcticicestudio/nord-highlightjs/develop/assets/scrot-hero.png
[npm]: https://www.npmjs.com/package/nord-highlightjs

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Could you kindly fix the merge conflict?

**Comment by gusbemacbe** [comment]
@marcoscaceres, he is not available anymore since June when he tweeted he is busy with his college.

**Comment by marcoscaceres** [comment]
Ok, no problem. Can fix these manually.

**Comment by arcticicestudio** [comment]
@gusbemacbe There have been more updates (e.g. https://twitter.com/arcticicestudio/status/1030741488458780672) about my current RL situation, but this is off-topic here.

@marcoscaceres I've resolved both conflicts. I've moved the latest entry in `CHANGES.md` from the top of the file under the `## Master` heading because I think that's where it was supposed to be placed. If not please let me know so I can revert it and then squash these commits.

**Comment by marcoscaceres** [comment]
Thanks @arcticicestudio. Happy to read you are refreshed after what sounds like a well earned vacation.

**Pull request merged**
