### PR TITLE
Introducing the new C# 9 keywords

### PR DESCRIPTION
**Pull request by IEvangelist**
Hi 👋🏼 highlight.js friends!

I'd like to introduce several new C# keywords. These are being added as part of C# 9.

- `init`
- `record`
- `and`
- `not`
- `or`
- `nint`
- `nunit`
- `with`

See our official docs: https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-9

### CODE REVIEW

**Comment by joshgoebel** [comment]
Looks good. Could you add a CHANGES.md entry please?

Also, is there any chance you'd mind grouping all the "datatype" keywords as well (since you seem to know C#) and perhaps it'd be quick for you to do?

In the future we should probably highlight them as data types instead of keywords proper, what do you think?

**Comment by IEvangelist** [comment]
Hi @joshgoebel - I can update the CHANGES.md, no problem. I'm not sure I follow the other suggestions - as I'm not that familiar with how some of the internals work in highlight.js.

- What is this `datatype` keyword you speak of and how do I group things as that?

**Comment by joshgoebel** [comment]
>  I'm not sure I follow the other suggestions - as I'm not that familiar with how some of the internals work in highlight.js.

Well for starters I just meant grouping them literally, with a comment (like the keywords are already grouped a bit into categories)... but really we probably should highlight them as "type" or "built_in"... but getting them grouped first would be a step in that direction.

**Comment by IEvangelist** [comment]
I'm going to close and reopen a new PR, properly forking the repo.

**Comment by IEvangelist** [comment]
Hey @joshgoebel - see #2679

**Pull request closed without merging**
