### PR TITLE
added yara rule support

### LINKED ISSUE #1571: Add Yara grammar (needs maintainer)
Add syntax highlighting for [Yara](https://github.com/VirusTotal/yara) rules.

You might be able to make use of the regexes in the [Yara syntax highlighter for Atom](https://github.com/blacktop/language-yara).

yara-example

### PR DESCRIPTION
**Pull request by d-demirci**
### Related Issue
Resolves #1571

### Changes

added yara.js

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

### Markup

Rendered YARA Rule

<pre><output>&lt;span class="hljs-keyword"&gt;rule&lt;/span&gt; CISA_3P_10301706_01 : HiddenCobra ECCENTRICBANDWAGON backdoor keylogger reconnaissance screencapture spyware trojan   
   &lt;span class="hljs-punctuation"&gt;{&lt;/span&gt;   
      &lt;span class="hljs-keyword"&gt;meta&lt;/span&gt;:   
          Author &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;CISA Trusted Third Party&amp;quot;&lt;/span&gt;   
          Incident &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;10301706.r1.v1&amp;quot;&lt;/span&gt;   
          Date &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;2020-08-11&amp;quot;&lt;/span&gt;   
          Actor &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;Hidden Cobra&amp;quot;&lt;/span&gt;   
          Category &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;Backdoor Keylogger Reconnaissance Screen-Capture Spyware Trojan&amp;quot;&lt;/span&gt;   
          Family &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;ECCENTRICBANDWAGON&amp;quot;&lt;/span&gt;   
          Description &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;Detects strings in ECCENTRICBANDWAGON proxy tool&amp;quot;&lt;/span&gt;   
          MD5_1 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;d45931632ed9e11476325189ccb6b530&amp;quot;&lt;/span&gt;   
          SHA256_1 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;efd470cfa90b918e5d558e5c8c3821343af06eedfd484dfeb20c4605f9bdc30e&amp;quot;&lt;/span&gt;   
          MD5_2 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;acd15f4393e96fe5eb920727dc083aed&amp;quot;&lt;/span&gt;   
          SHA256_2 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;32a4de070ca005d35a88503717157b0dc3f2e8da76ffd618fca6563aec9c81f8&amp;quot;&lt;/span&gt;   
          MD5_3 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;34404a3fb9804977c6ab86cb991fb130&amp;quot;&lt;/span&gt;   
          SHA256_3 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;c6930e298bba86c01d0fe2c8262c46b4fce97c6c5037a193904cfc634246fbec&amp;quot;&lt;/span&gt;   
          MD5_4 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;3122b0130f5135b6f76fca99609d5cbe&amp;quot;&lt;/span&gt;   
          SHA256_4 &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;9ea5aa00e0a738b74066c61b1d35331170a9e0a84df1cc6cef58fd46a8ec5a2e&amp;quot;&lt;/span&gt;   
      &lt;span class="hljs-keyword"&gt;strings&lt;/span&gt;:   
          &lt;span class="hljs-variable"&gt;$sn1&lt;/span&gt; &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;{&lt;/span&gt; &lt;span class="hljs-number"&gt;FB&lt;/span&gt; &lt;span class="hljs-number"&gt;19&lt;/span&gt; &lt;span class="hljs-number"&gt;9D&lt;/span&gt; &lt;span class="hljs-number"&gt;57&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-6&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;9A&lt;/span&gt; &lt;span class="hljs-number"&gt;D1&lt;/span&gt; &lt;span class="hljs-number"&gt;D6&lt;/span&gt; &lt;span class="hljs-number"&gt;D1&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-6&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;42&lt;/span&gt; &lt;span class="hljs-number"&gt;9E&lt;/span&gt; &lt;span class="hljs-number"&gt;D8&lt;/span&gt; &lt;span class="hljs-number"&gt;FD&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;}&lt;/span&gt;   
          &lt;span class="hljs-variable"&gt;$sn2&lt;/span&gt; &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;{&lt;/span&gt; &lt;span class="hljs-number"&gt;4F&lt;/span&gt; &lt;span class="hljs-number"&gt;03&lt;/span&gt; &lt;span class="hljs-number"&gt;43&lt;/span&gt; &lt;span class="hljs-number"&gt;83&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-6&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;48&lt;/span&gt; &lt;span class="hljs-number"&gt;E0&lt;/span&gt; &lt;span class="hljs-number"&gt;1A&lt;/span&gt; &lt;span class="hljs-number"&gt;2E&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-6&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;3B&lt;/span&gt; &lt;span class="hljs-number"&gt;FD&lt;/span&gt; &lt;span class="hljs-number"&gt;FD&lt;/span&gt; &lt;span class="hljs-number"&gt;FD&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;}&lt;/span&gt;   
          &lt;span class="hljs-variable"&gt;$sn3&lt;/span&gt; &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;{&lt;/span&gt; &lt;span class="hljs-number"&gt;68&lt;/span&gt; &lt;span class="hljs-number"&gt;56&lt;/span&gt; &lt;span class="hljs-number"&gt;68&lt;/span&gt; &lt;span class="hljs-number"&gt;9A&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-12&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;4D&lt;/span&gt; &lt;span class="hljs-number"&gt;E1&lt;/span&gt; &lt;span class="hljs-number"&gt;1F&lt;/span&gt; &lt;span class="hljs-number"&gt;25&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-12&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;3F&lt;/span&gt; &lt;span class="hljs-number"&gt;38&lt;/span&gt; &lt;span class="hljs-number"&gt;54&lt;/span&gt; &lt;span class="hljs-number"&gt;0F&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-12&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;73&lt;/span&gt; &lt;span class="hljs-number"&gt;30&lt;/span&gt; &lt;span class="hljs-number"&gt;62&lt;/span&gt; &lt;span class="hljs-number"&gt;A1&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;[&lt;/span&gt;&lt;span class="hljs-number"&gt;1&lt;/span&gt;&lt;span class="hljs-number"&gt;-12&lt;/span&gt;&lt;span class="hljs-punctuation"&gt;]&lt;/span&gt; &lt;span class="hljs-number"&gt;DB&lt;/span&gt; &lt;span class="hljs-number"&gt;39&lt;/span&gt; &lt;span class="hljs-number"&gt;BD&lt;/span&gt; &lt;span class="hljs-number"&gt;56&lt;/span&gt; &lt;span class="hljs-punctuation"&gt;}&lt;/span&gt;   
          &lt;span class="hljs-variable"&gt;$sn4&lt;/span&gt; &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;%s\\chromeupdater_ps_%04d%02d%02d_%02d%02d%02d_%03d_%d&amp;quot;&lt;/span&gt; &lt;span class="hljs-keyword"&gt;wide&lt;/span&gt; &lt;span class="hljs-keyword"&gt;ascii&lt;/span&gt; &lt;span class="hljs-keyword"&gt;nocase&lt;/span&gt;   
          &lt;span class="hljs-variable"&gt;$sn5&lt;/span&gt; &lt;span class="hljs-operator"&gt;=&lt;/span&gt; &lt;span class="hljs-string"&gt;&amp;quot;c:\\windows\\temp\\TMP0389A.tmp&amp;quot;&lt;/span&gt; &lt;span class="hljs-keyword"&gt;wide&lt;/span&gt; &lt;span class="hljs-keyword"&gt;ascii&lt;/span&gt; &lt;span class="hljs-keyword"&gt;nocase&lt;/span&gt;   
      &lt;span class="hljs-keyword"&gt;condition&lt;/span&gt;:   
          &lt;span class="hljs-keyword"&gt;any&lt;/span&gt; &lt;span class="hljs-keyword"&gt;of&lt;/span&gt; &lt;span class="hljs-keyword"&gt;them&lt;/span&gt;   
   &lt;span class="hljs-punctuation"&gt;}&lt;/span&gt;</output></pre>

### CODE REVIEW

**Comment by joshgoebel** [comment]
Thanks so much for your contribution!  Sadly, due to lack of maintainer time we no longer merge additional languages into the core library - but we'd love to have your grammar as a 3rd party language module if you'd be willing to maintain it over time.  It's quite easy to convert what you've already got into a 3rd party module. (it really just involves moving some files around, building, then pushing into your own repository)

We can host that repository here at the `highlightjs` organization (and are happy to) or you can host it on your own GitHub. *The key thing is you need to be willing to maintain it, deal with any future issues, etc - i.e. become the de-facto maintainer of the module.*  Once you have your repository all setup we will happily accept a PR to add a link to our list of supported languages here in the official repo.

Please read https://github.com/highlightjs/highlight.js/blob/master/docs/language-contribution.rst.

An example 3rd party language repo:
https://github.com/highlightjs/highlightjs-robots-txt

**Comment by cchepeau** [comment]
Adding support for Yara syntax could be nice 👍 
Thanks

**Comment by joshgoebel** [comment]
Agree, the more 3rd party grammars we support the better.  We just need the people willing to not only build them but also maintain them, fix bugs, etc. :-)

**Comment by joshgoebel** [comment]
Closing.  Happy to rearview this is a 3rd party grammar is created and this is resubmitted as just a changelog + SUPPORTED_LANGUAGES change.

**Pull request closed without merging**
