### PR TITLE
Added Papyrus

### PR DESCRIPTION
**Pull request by Pickysaurus**
### Changes

Added link to my parser for Papyrus, the coding language used by Bethesda games.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md` (Does this apply here?)

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please add changelog entry as well.

Also typically the naming convention is `highlightjs-papyrus` not `highlight.js-papyrus`.

**Review by joshgoebel — APPROVED** [review]
Still need that changelog entry. :)

**Comment by Pickysaurus** [comment]
Sorry, I did this through the GitHub site, so it was easier to do it across several commits. If you left any more comments I'm unsure where they are. 

Thanks

**Comment by joshgoebel** [comment]
Could you add a usage example to your README like the other grammars have?

Example: 
https://github.com/highlightjs/highlightjs-robots-txt

**Comment by joshgoebel** [comment]
> If you left any more comments I'm unsure where they are.

I left them on the original commits.

**Comment by Pickysaurus** [comment]
Thanks, I'm having a few issues getting NPM to work (I've never used it before) but other than that I've made the changes. 

I'll see if I can improve it based on your suggestions when I have time. Currently, it spits out the code in a visually relevant way, so I'm happy with it.

**Comment by joshgoebel** [comment]
@Pickysaurus Thanks so much!

**Pull request merged**
