### PR TITLE
enh(clojure) Adds global definitions with class name `title`

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/issues/2420

**Comment by yyyc514** [comment]
@agrison Look good to you?

**Comment by agrison** [comment]
Awesome, looks good @yyyc514 I will take a close look this evening !

**Comment by yyyc514** [comment]
@agrison Did you have a change to take a look?

**Comment by agrison** [comment]
Yes it looks good, nice work !

**Pull request merged**
