### PR TITLE
Update readme snippets to es6

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
I appreciate what you've done here, but what would add significant value is getting rid of the jQuery code. @amilajack, would you be willing to do that?

**Comment by amilajack** [comment]
@marcominetti I'll take a look. Can you point me to the places where jQuery is used? I took a look and couldn't find where it's used. Thanks!

**Comment by marcoscaceres** [comment]
See:
https://github.com/highlightjs/highlight.js#custom-initialization

Anything with `$` on the front of it :)

**Comment by amilajack** [comment]
Ahh you're referring to upgrading the README from jQuery. For some reason I assumed you were referring to the codebase itself. Sure, I'll work on this now

**Comment by marcoscaceres** [comment]
@amilajack, sorry for not being clear. That would be awesome! appreciate your help.

**Pull request merged**
