### PR TITLE
add highlight style css.

### PR DESCRIPTION
**Pull request by takemori-kondo**
this is style like visual studio 2015 default for c-sharp.
---
Dear team
Thank you for a cool project.
I created css of the same color setting as the default setting (dark) of Visual Studio 2015.
If you do not mind, please use it.

### CODE REVIEW

**Comment by mariuszjamro** [comment]
I think you're missing color of the `.hljs-title` element. That's the green-one used for example for type names.

    .hljs-title {
        color: #45cab5;
    }

**Comment by yyyc514** [comment]
Is there not already vs2015?  How is this different?

**Comment by takemori-kondo** [comment]
> Yyyc 514
Thank you, thanks, I was able to notice.

> Mariuszjamro
Oh, sorry, I completely forgotten.

About .hljs-title seems to be highlighted elsewhere.
(Although it is originally a class name,  namespace & functions seem to be highlighted too.)

About .hljs-number, it is as pointed out. Thank you very much.

I'll apply only .hljs-number for now.
Thank you.

byvs2017

byhighlight js

**Comment by takemori-kondo** [comment]
I was misunderstanding.
Nicolas 01 was already creating vs 2015 dark style at https://github.com/highlightjs/highlight.js/pull/1517.
This pull requiest can be closed.

**Pull request closed without merging**
