### PR TITLE
Add support for NSIS 3.03

### PR DESCRIPTION
**Pull request by idleberg**
- adds new NSIS 3.03 syntax
- fix: add missing separator in compiler flags

### CODE REVIEW

**Comment by ldct** [comment]
why are some old keywords (e.g. `Int64Cmp`) deleted?

**Comment by idleberg** [comment]
They were added, not deleted

**Comment by ldct** [comment]
ah sorry; I meant things like `FunctionEnd`

**Comment by ldct** [comment]
seems like `SectionGroupEnd` was also removed

**Comment by ldct** [comment]
LGTM other than that

**Pull request merged**
