### PR TITLE
Add Dylan Language

### PR DESCRIPTION
**Pull request by pedro-w**
This PR is to add support for the Dylan language. Dylan is a multi-paradigm functional and object-oriented programming language. Version 2019.1 has recently been released.
https://opendylan.org/

### CODE REVIEW

**Comment by pedro-w** [comment]
OK I see it is also detecting AppleScript. I will look into this, sorry.

**Comment by pedro-w** [comment]
Should now pass all tests

**Comment by marcoscaceres** [comment]
hi @pedro-w. We are moving new languages out to their own repositories under the highlightjs organization. Would you be willing to maintain the Dylan language definition? 

Take a look under https://github.com/highlightjs/ to see other example languages.

**Comment by pedro-w** [comment]
Thanks for the response, @marcoscaceres . I read that you were restructuring that way but I couldn't figure out how to put in a PR for a whole new repository!
I'd be happy to maintain the Dylan definition. The background to this is that we have just started using Gitter for our development discussion. Currently Gitter, because it uses highlightjs, has no support for highlighting snippets of Dylan code.

**Comment by marcoscaceres** [comment]
> Thanks for the response, @marcoscaceres . I read that you were restructuring that way but I couldn't figure out how to put in a PR for a whole new repository!

Just start by moving the language file. 

Terraform provides a nice example of a single language to copy:
https://github.com/highlightjs/highlight-terraform

You can then add the test output and make sure it outputs what you expect. 

See "input.txt" and "expected.txt":
https://github.com/highlightjs/highlight-terraform/tree/master/spec

"default.txt" will be your "input.txt" so you will need to generate some "expected.txt".

**Comment by pedro-w** [comment]
See https://github.com/pedro-w/highlight-dylan

**Comment by marcoscaceres** [comment]
Looks great @pedro-w! We just need to transfer it over to this org. I think what you need to do is add me as a contributor (@marcoscaceres) in the settings. Then go to the danger area in the settings and select to transfer the repository to "highlightjs".

**Comment by pedro-w** [comment]
I transferred it to you because I don't have permissions to create repositories in 'highlightjs' - presumably you will now be able to move it to the organisation.

**Comment by marcoscaceres** [comment]
no problem... moving it now :)

**Comment by marcoscaceres** [comment]
@pedro-w done: https://github.com/highlightjs/highlight-dylan/ 🥳

**Comment by pedro-w** [comment]
Looks like it's done, thanks for that.

**Pull request closed without merging**
