### PR TITLE
Add Iptables Grammar

### PR DESCRIPTION
**Pull request by Checconio**
Added coloring for Iptables configurations

### Changes
New Grammar

### Checklist
- [X] Added markup tests.
- [X] Added detect tests.
- [X] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
Our general policy today is that we don't merge new grammars into the core library, ([see our contribution guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)) but I'm finding myself somewhat intrigued by `iptables`.  I can't imagine the maintenance would be very high across time, but would you be willing to work on improvements and fixes if people file issues against the grammar?

Also, could you please show us a snap of what the highlighting looks like right now?

**Comment by Checconio** [comment]
> Our general policy today is that we don't merge new grammars into the core library, ([see our contribution guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)) but I'm finding myself somewhat intrigued by `iptables`. I can't imagine the maintenance would be very high across time, but would you be willing to work on improvements and fixes if people file issues against the grammar?
> 
> Also, could you please show us a snap of what the highlighting looks like right now?

Hello,

My apologies for the missed procedure :)
If it's good for you I'll redo the request correctly

I am obviously ready to make corrections if necessary.

Here is a preview of an Iptables configuration file with my highlight
iptables

**Comment by joshgoebel** [comment]
Lose interest?

**Comment by Checconio** [comment]
No, I opened the request with the correct procedure https://github.com/highlightjs/highlight.js/issues/3771

**Pull request closed without merging**
