### PR TITLE
(elixir) Two of three issues fixed (which issues?)

### PR DESCRIPTION
**Pull request by Sannis**
Relates to #730.

@eksperimental, @isagalaev I suggest to merge this without full sigils support.

### CODE REVIEW

**Comment by eksperimental** [comment]
thank you :100: times @Sannis

**Comment by Sannis** [comment]
Current state:
screen shot 2015-09-10 at 13 06 29
I nedd to with issues with comments in sigils before merging this.

**Comment by eksperimental** [comment]
@Sanni sorry, but it is not clear what you say you need in your last comment.

here are some comments:

This is what the Elixir interactive shell (`iex`) interprets:

```elixir
iex(1)> ~R'this + i\s "a" regex too'
~r/this + i\s "a" regex too/

iex(2)> ~w(hello #{ ["has" <> "123", '\c\d', "\123 interpol" | []] } world)s
["hello", "has123c\d123", "interpol", "world"]

iex(3)> ~W(hello #{no "123" \c\d \123 interpol} world)s
["hello", "\#{no", "\"123\"", "\\c\\d", "\\123", "interpol}", "world"]

iex(4)> ~s{Escapes terminators \{ and \}, but no {balancing} # outside of sigil here }
"Escapes terminators { and }, but no {balancing"

iex(5)> ~S"No escapes \s\t\n and no #{interpolation}"
"No escapes \\s\\t\\n and no \#{interpolation}"
```

1. is working perfect!
2. Sigils, here is a link to [~w](http://elixir-lang.org/docs/master/elixir/Kernel.html#sigil_w/2) and [~W](http://elixir-lang.org/docs/master/elixir/Kernel.html#sigil_W/2). the w/W sigil splits everything inside the parenthesis taking a white space as a separator. These sigils can take a modifier at the end (that the "s" you see there).  The difference is that the lowercase version does interpolationation and character unescaping, and the uppercase version takes everything literal.

One thing to mention, is that elixir uses `#{ }` to interpolate variables and functions insie other strings. So not always everything that comes after `#` should be considered a comment.

so `~W(hello #{no "123" \c\d \123 interpol} world)s` will split the text inside the parenthesis by the whitespace. so "hello" "#{no" "\"123\"" ...etc. will be the elements of the list returns. this doesn't really matter for the highlighting, but just to explain it better.

You can see the example of how pygment highlights it as a reference: http://pygments.org/demo/1180634/

Example no.4: is perfect

Example no.5 : I think `#{interpolation}` should not be highlighted differently since it has no special meaning in `~S`. if the sigil would be ~s, It would be alright to highlight it different (interpolation will be a function or a variable)

Here's a modified version of the example above, using `~s` sigil.
```elixir
iex(6)> ~s"No escapes \s\tTabbed\n and no #{"interpolation"}"
"No escapes  \tTabbed\n and no interpolation"
iex(7)> IO.puts ~s"No escapes \s\tTabbed\n and no #{"interpolation"}"
No escapes      Tabbed
 and no interpolation
:ok
```
Characters are unescaped

Let me know if you need clarification on more issues.
I'm glad to help, or I can bring more people in, if you need further input that I am not able to provide.

thanks again for looking after this issue.

**Comment by eksperimental** [comment]
@Sannis hi, just poping back in to see if there is any more feedback from my side to help have this PR merged in master? please let me know if you need anything,
thanks for looking after this.

**Comment by eksperimental** [comment]
oh by the way, there was one more issue that was discovered by @memory: https://github.com/isagalaev/highlight.js/issues/730#issuecomment-157696731
> `&fun!/1` is interpreted as a regex

**Comment by yyyc514** [comment]
@Sannis You still around?  Could you add a summary in your original post about what 2 or 3 items this is improving so I know what to be looking for when reviewing this?

**Comment by yyyc514** [comment]
Ping. Anyone there?

**Comment by isagalaev** [comment]
> Anyone there?

Apparently not :-) I am frankly too far removed from thinking about this again, so I'd say use your best judgment what to do with it.

**Comment by yyyc514** [comment]
Closing in favor of: https://github.com/highlightjs/highlight.js/pull/2257

**Pull request closed without merging**
