### PR TITLE
Update agate.css

### PR DESCRIPTION
**Pull request by taufik-nurrohman**
#3134

### CODE REVIEW

**Comment by joshgoebel** [comment]
```
Missing selector .hljs-attr
Missing selector .hljs-template-tag
Theme does not fully support Templates/HTML/XML, etc..

Missing selector .hljs-selector-attr
Missing selector .hljs-selector-pseudo
Theme does not fully support CSS/Less/etc.

Missing selector .hljs-meta-keyword
Missing selector .hljs-meta-string
Theme does not fully support nice to haves (many code grammars use).

Missing selector .hljs-doctag
Missing selector .hljs-attr
Theme does not fully support program code.
```

See `tools/checkTheme`.  Please add the missing selectors or IF these are purposeful omissions add empty rules so we know that you're choosing not to highlight them.

**Comment by joshgoebel** [comment]
Also not wishing to draw any distinction between title.function and title.class?

**Comment by taufik-nurrohman** [comment]
Let me improve it tomorrow night GMT+07:00.

**Comment by taufik-nurrohman** [comment]
Arrgh!

**Review by joshgoebel — APPROVED** [review]

**Comment by joshgoebel** [comment]
@taufik-nurrohman Thanks so much!

**Pull request merged**
