### PR TITLE
Add the Lustre language

### PR DESCRIPTION
**Pull request by jahierwan**

### CODE REVIEW

**Comment by yyyc514** [comment]
Currently we're not accepting/merging new languages to the core repo, but if you'd like to become the long-term maintainer of this language we'd be happy to host a separate repo for you in the `highlightjs` organization and give you push access.  It's pretty easy for your language to exist as a stand-alone module that then people can just add themselves with `registerLanguage` (the README has examples of doing this).

Though there aren't really official docs or an official template yet...  You can find other examples already there:

https://github.com/highlightjs/

After the holidays I plan to work on making this whole process (or using and integrating 3rd party languages) a bit easier and more official.

**Comment by yyyc514** [comment]
Would you like us to create a `highlightjs-lustre` repo for you?

**Comment by yyyc514** [comment]
Sorry forgot to link the larger discussion of things: https://github.com/highlightjs/highlight.js/issues/2149

**Comment by jahierwan** [comment]
That would be nice. Thanks Josh.


R1

14 déc. 2019 15:38:28 Josh Goebel <notifications@github.com>:

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlightjs-lustre

I sent you an invite.  @egor-rogov Have we just been giving people "Write" permissions when we create new language repos? This is the first one I've done.

**Comment by yyyc514** [comment]
@jahierwan There ya go!

**Comment by egor-rogov** [comment]
I give admin permissions (e.g. to be able to invite new maintainers etc).
That's all what's needed.

**Comment by yyyc514** [comment]
Ok, admin it is then!

**Pull request closed without merging**
