### PR TITLE
chore(docs) Small fixes in language guide and mode reference

### PR DESCRIPTION
**Pull request by edemaine**
I found a couple of small typos, and references to the old `className`, while reading the docs, so thought I'd push them along here.

### Changes
* Change `className` to `scope`, "name" to "scope"
* Add link to Scopes Reference from Language Guide too (copied from Mode Reference). I don't know how to render reStructuredText so I assume this link renders OK but haven't verified.
* Fix typo "many" to "must"

### Checklist
- [ ] Added markup tests, or they don't apply here because just changing documentation
- [ ] Updated the changelog at `CHANGES.md`

### CODE REVIEW

**Comment by joshgoebel** [comment]
This would need to be rebased on https://github.com/highlightjs/highlight.js/pull/3159 where I think I've already got most of this... it's just not in `main` yet.

**Comment by joshgoebel** [comment]
@edemaine Any chance you'd like to possibly help out by doing some more reviewing of PRs?  That's the big road block right now to forward momentum.  If you'd like to help out there find me on Discord.

**Comment by edemaine** [comment]
I tried rebasing onto #3159, and these changes seem to still be relevant (no conflicts).

**Comment by joshgoebel** [comment]
Oh... maybe it's another PR then... we'll leave this be then until everything  merges and then have a fresh look.

**Comment by joshgoebel** [comment]
You were right, guess I missed these.  Thanks so much!

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
