### PR TITLE
[xquery] rewrite 

### LINKED ISSUE #1641: xquery language is missing node literal
Github catches the ``node()`` literal of first operand, 
```XQuery
declare function app:helloworld($node as node(), $model as map(*), $name as xs:string?) {
    if ($name) then
        <p>Hello {$name}!</p>
    else
        ()
};
```

highlight correctly catches xs:string, but not ``node()``

screenshot 2017-11-20 14 26 03

### PR DESCRIPTION
**Pull request by duncdrum**
feel free to squash n merge
-  refactored literals to types closes #1641 
-  reenable variable highlighting
-  enable code highlighting inside of function-bodies and xml constructor syntax
-  add title highlighting, missing prolog keywords, and removed inaccurate keywords
-  add tests
-  npm updates see #1648

### CODE REVIEW

**Comment by duncdrum** [comment]
``` 522 passing (9s)```
Not sure why the test suite still complains. Locally it passes \([see log here](https://www.dropbox.com/s/yy3ffv7ry425cw5/highlight-mocha.txt?dl=0)\). I noticed the same errors that travis is throwing when upgrading jsdom or mocha, so I doubt it has something to do with the contents of this PR.

**Comment by duncdrum** [comment]
some more poking around:
-  `node tools/build.js -t node` => `Finished build.`  passes mocha tests ` 522 passing (9s)`
-  `node tools/build.js -n xquery` => `Finished build.` all good in browser & no errors in console
-  `node tools/build.js xquery` => 
```bash
Compressing highlight.js pack file.
{ task: 'tasks',
  error: { task: 'replaceSkippingStrings', error: 'Unmatched quote' } }
```
when compressing the this line from [task.js](https://github.com/isagalaev/highlight.js/blob/cf4b46e5b7acfe2626a07914e1d0d4ef269aed4a/tools/tasks.js#L122) is giving me headaches. I've tested the regex in question in multiple other environments none reports any problems, but something is tripping. Any hints or suggestions?

**Comment by duncdrum** [comment]
1.  Ok, yes you may laugh at me.
2.  If the compressed package uses a different js, then the uncompressed one, maybe adding another test could safe others the same trouble I just had

**Comment by paladox** [comment]
This needs rebasing.

**Comment by duncdrum** [comment]
@paladox done

**Comment by duncdrum** [comment]
so it's been six months since the request for a rebase, the PR is open for over a year, but no review 😞   Anything that I can do to help along? We would really like to switch back to main highlight branch with our apps, but we need a working xquery highlighter for that.

**Comment by egor-rogov** [comment]
Hi @duncdrum,
I've had a look into the patch and generally it looks fine. I have some comments though:

1. I think `.gitinore` and `package.json` should not be changed in this PR as they are not related to the language definition.

2. I've tried a simple example from https://en.wikipedia.org/wiki/XQuery and it seems that highlighting is broken when XQuery is mixed up with XML. For the following input:
```xquery
<html><head/><body>
 {
   for $act in doc("hamlet.xml")//ACT
   let $speakers := distinct-values($act//SPEAKER)
   return
     <span>
       <h1>{ $act/TITLE/text() }</h1>
       <ul>
       {
         for $speaker in $speakers
         return <li>{ $speaker }</li>
       }
       </ul>
     </span>
 }
 </body>
</html>
```
I've got (notice the last 4 lines):
```html
<span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">html</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">head</span>/&gt;</span></span><span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">body</span>&gt;</span>
 </span><span class="xquery">{
   <span class="hljs-keyword">for</span> <span class="hljs-variable">$act</span> <span class="hljs-keyword">in</span><span class="hljs-built_in"> doc</span>(<span class="hljs-string">"hamlet.xml"</span>)//ACT
   <span class="hljs-keyword">let</span> <span class="hljs-variable">$speakers</span> :=<span class="hljs-built_in"> distinct-values</span>(<span class="hljs-variable">$act</span>//SPEAKER)
   <span class="hljs-keyword">return</span>
     <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">span</span>&gt;</span>
       </span><span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">h1</span>&gt;</span></span><span class="xquery">{ <span class="hljs-variable">$act</span>/TITLE/<span class="hljs-type">text</span>() }</span><span class="xml"></span></span><span class="xml"><span class="hljs-tag">&lt;/<span class="hljs-name">h1</span>&gt;</span></span><span class="xml">
       </span><span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">ul</span>&gt;</span>
       </span><span class="xquery"><span class="xml"></span><span class="xquery">{
         <span class="hljs-keyword">for</span> <span class="hljs-variable">$speaker</span> <span class="hljs-keyword">in</span> <span class="hljs-variable">$speakers</span>
         <span class="hljs-keyword">return</span> <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">li</span>&gt;</span></span><span class="xquery">{ <span class="hljs-variable">$speaker</span> }</span><span class="xml"></span></span><span class="xml"></span></span><span class="xml"><span class="hljs-tag">&lt;/<span class="hljs-name">li</span>&gt;</span></span><span class="xml">
       }
       <span class="hljs-tag">&lt;/<span class="hljs-name">ul</span>&gt;</span></span>
     &lt;/span&gt;
 }
 &lt;/body&gt;
&lt;/html&gt;
```

**Comment by duncdrum** [comment]
@egor-rogov thanks for the response. The example that you used from wikipedia is tricky for a number of reasons. Technically speaking it's not xquery but xml (missing the Xquery declaration at the top) such mixed files have never been properly highlighted by highlight.js . See [https://highlightjs.org/static/demo/](https://highlightjs.org/static/demo/) and the screenshot in #1641

I m not opposed on working on a new feature to implement proper highlighting of mixed xml/xquery files. But I'm not sure that these mixed cases should prevent the changes in this PR from going in. IIRC the xml highlighter is also used for html, so before tweaking it for these corner cases I d rather have the tests from this PR available.

**Comment by egor-rogov** [comment]
> The example that you used from wikipedia is tricky for a number of reasons.

Yeah, I see.

> I m not opposed on working on a new feature to implement proper highlighting of mixed xml/xquery files. But I'm not sure that these mixed cases should prevent the changes in this PR from going in. 

No, they shouldn't. I'm going to merge it.

**Comment by egor-rogov** [comment]
Thanks for your efforts, merged.

> I m not opposed on working on a new feature to implement proper highlighting of mixed xml/xquery files.

Further improvements are welcome!

**Pull request merged**
