### PR TITLE
📦 Add Shades of Purple theme

### PR DESCRIPTION
**Pull request by ahmadawais**
This PR adds the new [Shades of Purple theme for Highlight.js](https://github.com/ahmadawais/Shades-of-Purple-HighlightJS).

image
Peace! ✌️

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Do you really need `!important` on every rule?

**Comment by gusbemacbe** [comment]
@SirCmpwn, the rule `!important` is for overwriting the original colours. Without it, the modified is ignored and the original is maintained.

**Comment by SirCmpwn** [comment]
You just need to ensure the theme's stylesheet is loaded after the main one. `!important` is a last resort and is almost never necessary.

**Comment by isagalaev** [comment]
I actually think we should simply outlaw `!important` in the library style. It's up to the web site author to arrange the stylesheet, the library can't unilaterally force its own colors over someone else's stylesheet.

**Comment by gusbemacbe** [comment]
@ahmadawais, Operator Mono is not free or open source. Not everybody can have the font Operator Mono. If Operator Mono is ruled as `!important`, the browser will not find the font and will declare it as lost and replace for a serif font.

**Comment by isagalaev** [comment]
… and fonts are actually already against the style guide: https://github.com/highlightjs/highlight.js/blob/master/docs/style-guide.rst#typography-and-layout-dos-and-donts

**Comment by gusbemacbe** [comment]
Ah, it is the hour of re-arranging the theme, @ahmadawais.

**Comment by ahmadawais** [comment]
`!important` is important for users who use the styles before highlight.js for some reason. 

I have adjusted the font option by commenting it and make the fallback options available. Now anyone who wants this option can uncomment it.

Let me know if this looks good to you folks. 

🤔 This repo is more active than I thought it would be.

**Comment by gusbemacbe** [comment]
@ahmadawais, without new collaborators and Ivan as the only maintainer, the repository was stopped for a year. Yesterday the new collaborators appeared, saying to be interested to be new collaborators, maintainers and reviewers. And he invited them today.

**Comment by gusbemacbe** [comment]
@ahmadawais, yes, `!important` is important to overwrite the original, but unfortunately @isagalaev does not allow us to use `!important`.

**Comment by ahmadawais** [comment]
@gusbemacbe that is impressive. I hope they stick around and improve this one. The syntax options are limited.

**Comment by ahmadawais** [comment]
Let me know if I should remove it. I can do that. Though in many many cases
we need it.

>

**Comment by gusbemacbe** [comment]
If they ask you to remove it, you can comment it, saying that if they want to overwrite the originals when they use JavaScript library and default style of Highlight.js. I am not sure if Ivan and the new collaborators will allow to comment it.

**Comment by isagalaev** [comment]
@gusbemacbe 
> yes, !important is important to overwrite the original, but unfortunately @isagalaev does not allow us to use !important.

It's not "unfortunately", it's exactly why it's so. You can't know the intention of the site's author who uses the library style. Without `!important` they can do whatever they like, with `!important` you're making their lives harder by forcing your choices on top of theirs.

@ahmadawais 
> The syntax options are limited.

If you mean the amount of various things you can highlight, then this is [by design](https://github.com/highlightjs/highlight.js/blob/master/docs/style-guide.rst#key-principle) (also see this http://softwaremaniacs.org/blog/2016/08/16/highlight-js-turns-10/)

**Comment by gusbemacbe** [comment]
> If you mean the amount of various things you can highlight, then this is by design (also see this http://softwaremaniacs.org/blog/2016/08/16/highlight-js-turns-10/)

I received the error:

Not Found
The requested URL /blog/2016/08/16/highlight-js-turns-10/ was not found on this server.

**Comment by gusbemacbe** [comment]
@ahmadawais, you forgot of authoring yourself. The repository's new policy requires it.

**Comment by ahmadawais** [comment]
> @ahmadawais, you forgot of authoring yourself. The repository's new policy requires it.

@gusbemacbe what?

Where are the policies? I didn't find anything nor a contribution guide.

**Comment by gusbemacbe** [comment]
https://github.com/highlightjs/highlight.js/blob/master/docs/style-guide.rst#contributing

**Comment by ahmadawais** [comment]
@gusbemacbe Done check now 👍

**Comment by gusbemacbe** [comment]
Also add to [AUTHOR.ru.txt](https://github.com/ahmadawais/highlight.js/blob/18f84c00b811b519a82661e5371c8349637bfb18/AUTHORS.ru.txt):

Ахмад Авайс <me@AhmadAwais.com>

**Comment by ahmadawais** [comment]
@gusbemacbe done. Looking forward to the merge now. 👀

**Comment by ahmadawais** [comment]
@SirCmpwn thanks for the approval. When can I expect it to be merged. I'd like to share it publicly.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
